import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'numeric',
    id: 'gre-frac-ops',
    lessonId: 'gre-fractions-decimals',
    difficulty: 2,
    prompt: '(3/4 − 1/6) ÷ 7/9 = ?\n\nGive your answer as a fraction.',
    answer: 3 / 4,
    answerDisplay: '3/4',
    fraction: true,
    explanation: '3/4 − 1/6 = 9/12 − 2/12 = 7/12. Dividing by 7/9 means multiplying by 9/7: 7/12 × 9/7 = 9/12 = **3/4**.',
  },
  {
    kind: 'mcq',
    id: 'gre-frac-compare',
    lessonId: 'gre-fractions-decimals',
    difficulty: 3,
    prompt: 'Which of the following is least?',
    options: ['5/9', '4/7', '0.56', '(0.75)²', '√0.3'],
    correctIndex: 4,
    explanation: 'Convert everything to decimals: √0.3 ≈ 0.548, 5/9 ≈ 0.556, 0.56, (0.75)² = 0.5625, 4/7 ≈ 0.571. The least is **√0.3**. When values are this close, benchmarks aren’t enough — convert and compare to three decimal places.',
    distractorNotes: [
      '≈ 0.556 — close, but slightly more than √0.3.',
      '≈ 0.571 — actually the greatest.',
      '0.56.',
      '0.5625.',
      'Correct — √0.3 ≈ 0.548 (0.55² = 0.3025, so √0.3 is just under 0.55).',
    ],
  },
  {
    kind: 'numeric',
    id: 'gre-frac-remain',
    lessonId: 'gre-fractions-decimals',
    difficulty: 2,
    prompt: 'A tank was full. On Monday 2/5 of the water was used, and on Tuesday 1/2 of the remaining water was used, leaving 120 liters. How many liters does the full tank hold?',
    answer: 400,
    answerDisplay: '400',
    suffix: 'liters',
    explanation: 'After Monday 3/5 remains; after Tuesday 1/2 of that: 3/5 × 1/2 = 3/10 of the tank. 3/10 of the tank = 120 L → the tank holds **400** L.',
  },
  {
    kind: 'mcq',
    id: 'gre-frac-sci',
    lessonId: 'gre-fractions-decimals',
    difficulty: 1,
    prompt: '(5 × 10⁴)(8 × 10⁻⁷) = ?',
    options: ['4 × 10⁻²', '4 × 10⁻³', '4 × 10⁻⁴', '40 × 10⁻²', '4 × 10²'],
    correctIndex: 0,
    explanation: '5 × 8 = 40 and 10⁴ × 10⁻⁷ = 10⁻³, so the product is 40 × 10⁻³ = **4 × 10⁻²** (0.04).',
    distractorNotes: [
      'Correct.',
      'Forgot to renormalize 40 → 4 × 10¹.',
      'Renormalized in the wrong direction.',
      'Equal in value, but not in scientific notation (and 40 × 10⁻² = 0.4 ≠ 0.04).',
      'Sign error on the exponent.',
    ],
  },
];
