import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'mcq',
    id: 'gre-ov-scale',
    lessonId: 'gre-overview',
    difficulty: 1,
    prompt: 'On the GRE, the Verbal and Quantitative sections are each reported on which scale?',
    options: ['0–6, in half-point steps', '130–170, in 1-point steps', '200–800, in 10-point steps', '1–36', '0–100 percent'],
    correctIndex: 1,
    explanation: 'Verbal and Quant are each scored 130–170 in 1-point increments. Analytical Writing is the one scored 0–6 in half points.',
    distractorNotes: [
      'That is the Analytical Writing scale.',
      'Correct.',
      'That is the old SAT section scale.',
      'That is the ACT scale.',
      'The GRE reports scaled scores, not a percentage.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-ov-adaptive',
    lessonId: 'gre-overview',
    difficulty: 2,
    prompt: 'Halfway through your second Quant section, the questions feel noticeably harder than in the first. What is the most reasonable interpretation?',
    options: [
      'You are doing badly, and the test is adapting question by question to trap you.',
      'You probably did well on the first Quant section, so you were given the harder second section.',
      'The second section is unscored, so difficulty doesn’t matter.',
      'The test randomly assigns difficulty, so it means nothing.',
      'You should slow down and spend extra time on each question to make up for it.',
    ],
    correctIndex: 1,
    explanation: 'The GRE adapts by section: your first-section performance picks the difficulty of the second. A harder second section usually means the first went well — and it is where high scores come from.',
    distractorNotes: [
      'The GRE does not adapt question by question.',
      'Correct.',
      'Both sections count; the current GRE has no unscored section.',
      'Difficulty is not random — it is based on your first section.',
      'Pacing rules still apply; slowing down costs you other questions.',
    ],
  },
  {
    kind: 'multi',
    id: 'gre-ov-types',
    lessonId: 'gre-overview',
    difficulty: 1,
    prompt: 'Which of the following question types appear in the Verbal Reasoning sections?\n\nIndicate all that apply.',
    options: ['Text completion', 'Quantitative comparison', 'Sentence equivalence', 'Reading comprehension', 'Numeric entry'],
    correctIndices: [0, 2, 3],
    explanation: 'Verbal has three types: text completion, sentence equivalence, and reading comprehension (which includes short argument paragraphs). Quantitative comparison and numeric entry are Quant types.',
    distractorNotes: ['✓ Verbal.', '✗ Quant.', '✓ Verbal.', '✓ Verbal.', '✗ Quant.'],
  },
  {
    kind: 'mcq',
    id: 'gre-ov-strategy',
    lessonId: 'gre-overview',
    difficulty: 1,
    prompt: 'With one minute left in a Verbal section, you have four questions you haven’t answered. What should you do?',
    options: [
      'Leave them blank, since a wrong answer costs points.',
      'Click an answer on all four, then use any remaining time on the one you can do fastest.',
      'Work carefully on the first one and hope for time on the others.',
      'Go back and double-check your earlier answers.',
      'Answer only the ones you are at least 50% sure about.',
    ],
    correctIndex: 1,
    explanation: 'There is no penalty for wrong answers, so a blank is always worse than a guess. Lock in guesses first, then use the leftover seconds to try to improve one of them.',
    distractorNotes: [
      'Wrong answers cost nothing on the GRE — blanks just throw away chances.',
      'Correct.',
      'Risks leaving three blanks.',
      'Unanswered questions are worth more attention than checked ones.',
      'Even a pure guess has positive expected value.',
    ],
  },
  {
    kind: 'numeric',
    id: 'gre-ov-pace',
    lessonId: 'gre-overview',
    difficulty: 1,
    prompt: 'The second Quant section has 15 questions in 26 minutes. If you have used 13 minutes and answered 6 questions, how many minutes per question do you have left for the remaining questions? Round to the nearest tenth.',
    answer: 13 / 9,
    answerDisplay: '1.4',
    roundTo: 0.1,
    explanation: '26 − 13 = 13 minutes remain for 15 − 6 = 9 questions: 13 ÷ 9 ≈ 1.4 minutes each — a bit below the 1.75-minute average, so it is time to speed up or skip a hard one.',
  },
];
