import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'mcq',
    id: 'gre-rw-avg',
    lessonId: 'gre-rates-work',
    difficulty: 2,
    prompt: 'A cyclist rides 20 miles uphill at 10 mph and returns the same 20 miles downhill at 40 mph. What is the average speed for the whole ride, in miles per hour?',
    options: ['16', '20', '25', '30', '50'],
    correctIndex: 0,
    explanation: 'Uphill: 2 hours. Downhill: 0.5 hour. Total: 40 miles in 2.5 hours = **16 mph**. (Formula: 2 × 10 × 40 / 50 = 16.)',
    distractorNotes: [
      'Correct.',
      'Not a meaningful average here.',
      'The plain average of 10 and 40 — ignores that far more time is spent uphill.',
      'Not supported.',
      'The sum of the speeds.',
    ],
  },
  {
    kind: 'numeric',
    id: 'gre-rw-work',
    lessonId: 'gre-rates-work',
    difficulty: 2,
    prompt: 'Pipe A fills a tank in 4 hours and pipe B fills it in 12 hours. Working together, how many hours do they take to fill the empty tank?',
    answer: 3,
    answerDisplay: '3',
    suffix: 'hours',
    explanation: 'Rates: 1/4 + 1/12 = 3/12 + 1/12 = 4/12 = 1/3 tank per hour → **3 hours**.',
  },
  {
    kind: 'numeric',
    id: 'gre-rw-mix',
    lessonId: 'gre-rates-work',
    difficulty: 2,
    prompt: 'How many liters of pure water must be added to 12 liters of a 30% acid solution to make a 20% acid solution?',
    answer: 6,
    answerDisplay: '6',
    suffix: 'liters',
    explanation: 'Acid stays fixed at 0.3 × 12 = 3.6 L. 3.6 = 0.2 × (12 + w) → 12 + w = 18 → w = **6** L.',
  },
  {
    kind: 'mcq',
    id: 'gre-rw-meet',
    lessonId: 'gre-rates-work',
    difficulty: 2,
    prompt: 'Train P leaves a station at noon traveling 60 mph. At 1:00 p.m., train Q leaves the same station on a parallel track in the same direction at 80 mph. At what time does Q catch up to P?',
    options: ['2:00 p.m.', '3:00 p.m.', '4:00 p.m.', '5:00 p.m.', '6:00 p.m.'],
    correctIndex: 2,
    explanation: 'At 1:00, P is 60 miles ahead. Q gains 80 − 60 = 20 mph, so it needs 60 ÷ 20 = 3 hours → **4:00 p.m.**',
    distractorNotes: [
      'Too early — Q gains only 20 miles per hour.',
      'Measured 2 hours from 1:00.',
      'Correct.',
      'Measured from noon plus an extra hour.',
      'Not supported.',
    ],
  },
];
