// Authored argument (critical reasoning) questions — the short-paragraph
// reading questions the GRE mixes into Verbal: find the assumption,
// weaken, strengthen, resolve a paradox, spot the flaw, evaluate, infer.
// Each argument carries two questions; every choice has a note.

import type { Candidate, Generator } from '../engine.ts';

type Diff = 1 | 2 | 3;
interface AQ {
  prompt: string;
  options: string[];
  answer: number;
  why: string;
  notes: string[];
}
interface Arg {
  id: string;
  difficulty: Diff;
  text: string;
  questions: AQ[];
}
const Q = (prompt: string, options: string[], answer: number, why: string, notes: string[]): AQ => ({ prompt, options, answer, why, notes });

export const ARGUMENTS: Arg[] = [
  {
    id: 'bike-lanes',
    difficulty: 1,
    text: 'After the city of Harlow painted bike lanes on its main avenue, the number of cyclists counted on that avenue doubled within a year. The city council concludes that painting bike lanes on other streets will increase the total number of people who cycle in Harlow.',
    questions: [
      Q('The council’s conclusion depends on which of the following assumptions?',
        ['The additional cyclists on the main avenue were not mostly people who had previously cycled on other Harlow streets.', 'Painting bike lanes is inexpensive.', 'Most residents of Harlow own bicycles.', 'Cyclists prefer avenues to side streets.', 'Traffic accidents declined after the lanes were painted.'],
        0,
        'The evidence is about ONE avenue; the conclusion is about TOTAL cycling. If the avenue’s gain just came from cyclists switching routes, total cycling didn’t rise. Negate the assumption (“the extra cyclists were mostly route-switchers”) and the argument collapses.',
        ['Right — rules out the “they just moved” explanation.', 'Cost is irrelevant to whether cycling increases.', 'Not required: new cyclists could buy bikes.', 'Irrelevant to the total.', 'Safety is not the conclusion.']),
      Q('Which of the following, if true, would most weaken the council’s conclusion?',
        ['Cycling counts on the streets parallel to the main avenue fell by about as much as the avenue’s count rose.', 'Other cities have also painted bike lanes.', 'The bike lanes were painted green.', 'Some drivers objected to the bike lanes.', 'Bicycle sales in Harlow rose slightly that year.'],
        0,
        'If parallel streets lost as many cyclists as the avenue gained, cyclists simply rerouted — no increase in the total.',
        ['Right — the gain was redistribution.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant to cycling totals.', 'If anything, this slightly supports the conclusion.']),
    ],
  },
  {
    id: 'reading-scores',
    difficulty: 1,
    text: 'Students at Westbrook School who participate in the after-school reading club score higher on standardized reading tests than students who do not. Therefore, requiring all Westbrook students to join the reading club would raise the school’s average reading score.',
    questions: [
      Q('Which of the following, if true, most seriously weakens the argument?',
        ['Students who join the club voluntarily are those who already read the most at home.', 'The reading club meets twice a week.', 'The club’s organizer is a former librarian.', 'Westbrook’s average reading score is above the state average.', 'Some club members also play sports.'],
        0,
        'Correlation vs. causation: if strong readers self-select into the club, the club may not be causing higher scores, so forcing others in may not help.',
        ['Right — self-selection explains the gap.', 'Irrelevant detail.', 'Irrelevant detail.', 'Irrelevant to whether the club causes gains.', 'Irrelevant.']),
      Q('The argument is most vulnerable to which criticism?',
        ['It treats a correlation as proof that one thing causes another.', 'It relies on a sample that is too small.', 'It attacks the character of the club’s critics.', 'It assumes what it sets out to prove by restating its premise.', 'It confuses a necessary condition with a sufficient one.'],
        0,
        'Club members score higher (a correlation), and the argument concludes the club causes higher scores.',
        ['Right.', 'Sample size is not the issue raised.', 'No one is attacked.', 'The conclusion is not a restatement.', 'Not the flaw here.']),
    ],
  },
  {
    id: 'restaurant-revenue',
    difficulty: 2,
    text: 'Last year Café Loma raised the price of every item on its menu by 10 percent. Yet the café’s total revenue for the year was lower than in the previous year.',
    questions: [
      Q('Which of the following, if true, best explains the apparent discrepancy?',
        ['After the price increase, the café served substantially fewer customers.', 'The café’s costs for ingredients rose last year.', 'Several nearby restaurants also raised their prices.', 'The café added two new items to the menu.', 'The café’s owner considered lowering prices.'],
        0,
        'Revenue = price × quantity. Higher prices can still yield lower revenue if the number of customers fell enough.',
        ['Right — fewer sales outweighed higher prices.', 'Costs affect profit, not revenue.', 'If anything, this would make customers less likely to leave.', 'New items would tend to add revenue.', 'Considering is not doing.']),
      Q('The information above most strongly supports which conclusion?',
        ['The café sold fewer menu items last year than in the previous year.', 'The price increase caused customers to go to other cafés.', 'The café will lower its prices this year.', 'The café’s profit fell last year.', 'The café’s prices are higher than its competitors’.'],
        0,
        'If every price rose 10% but revenue fell, the quantity sold must have dropped (by more than enough to offset the higher prices). That’s the only thing that must be true.',
        ['Right — must be true.', 'Possible, but the cause is not established.', 'A prediction not supported.', 'Profit depends on costs, which aren’t given.', 'No comparison with competitors is given.']),
    ],
  },
  {
    id: 'fish-oil',
    difficulty: 2,
    text: 'In a survey of adults over sixty, those who reported taking fish-oil supplements daily had significantly lower rates of heart disease than those who did not. A supplement company cites this survey as evidence that fish oil prevents heart disease.',
    questions: [
      Q('Which of the following, if true, most weakens the company’s argument?',
        ['People who take daily supplements are also more likely to exercise regularly and eat healthily.', 'Fish oil is available in capsule and liquid form.', 'Heart disease is more common among adults over sixty than among younger adults.', 'The survey was conducted in several countries.', 'Some fish-oil supplements are more expensive than others.'],
        0,
        'A confounding variable: healthy habits could explain both supplement use and lower heart disease.',
        ['Right — alternative cause.', 'Irrelevant.', 'Irrelevant to the comparison between groups.', 'Doesn’t affect the causal inference.', 'Irrelevant.']),
      Q('Which of the following would it be most useful to know in evaluating the company’s argument?',
        ['Whether a controlled experiment randomly assigning fish oil to some participants found a similar difference', 'The price of the company’s fish oil', 'How many people over sixty live in the surveyed regions', 'Whether fish oil tastes unpleasant', 'How many companies sell fish oil'],
        0,
        'Randomization removes self-selection; a similar result in a randomized trial would support causation, and no difference would undercut it.',
        ['Right — tests causation directly.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'museum-free',
    difficulty: 2,
    text: 'The city museum eliminated its admission fee last year, and attendance rose by 40 percent. However, the museum’s total income from its gift shop and café also rose, more than making up for the lost admission revenue. The director therefore argues that other city museums should also eliminate their admission fees.',
    questions: [
      Q('The director’s argument assumes that',
        ['other museums would see similar increases in visitors and spending if they eliminated fees', 'the city museum’s exhibits are better than those of other museums', 'visitors dislike paying for admission', 'the gift shop sells items at a loss', 'attendance will continue to rise every year'],
        0,
        'The evidence comes from one museum; the recommendation is for others. It assumes their results would be similar.',
        ['Right — generalizing from one case.', 'The argument would work better if this were false.', 'Not required.', 'Would undermine, not support, the argument.', 'Not required for the recommendation.']),
      Q('Which of the following, if true, would most weaken the director’s argument?',
        ['Most other city museums have no gift shop or café.', 'The city museum’s free admission was widely advertised.', 'Many visitors to the city museum were tourists.', 'The museum’s attendance had been falling before the change.', 'Admission fees at other museums are higher than the city museum’s former fee.'],
        0,
        'The city museum’s losses were offset by shop and café income. Museums without those can’t make up the lost revenue the same way.',
        ['Right — the offsetting mechanism is missing.', 'Irrelevant to other museums.', 'Doesn’t address other museums.', 'Makes the rise more impressive, if anything.', 'Would make eliminating fees costlier, but doesn’t address offsets as directly as (A).']),
    ],
  },
  {
    id: 'tree-disease',
    difficulty: 2,
    text: 'A fungal disease has killed many elm trees in the Harrow Valley. Researchers found that elms growing near roads were far more likely to be infected than elms deep in the forest. They conclude that road salt, used in winter, weakens elms and makes them more susceptible to the fungus.',
    questions: [
      Q('Which of the following, if true, most weakens the researchers’ conclusion?',
        ['The fungus is spread by beetles that are attracted to open, sunny areas such as road edges.', 'Road salt is also used in neighboring valleys.', 'Elm trees are common throughout the region.', 'The disease was first detected ten years ago.', 'Some forest elms have also died from drought.'],
        0,
        'An alternative explanation for the pattern: beetles spreading the fungus concentrate near roads, regardless of salt.',
        ['Right — another reason road-edge elms get infected more.', 'Doesn’t address the explanation.', 'Irrelevant.', 'Irrelevant.', 'A different cause of death, not infection.']),
      Q('Which of the following, if true, most strengthens the conclusion?',
        ['Elms near roads that are never salted are infected no more often than forest elms.', 'Road salt damages car bodies.', 'The fungus also infects oak trees.', 'Many roads in the valley were built recently.', 'Forest elms are generally older than roadside elms.'],
        0,
        'If unsalted roadside elms have normal infection rates, proximity to roads alone isn’t the cause — salt is.',
        ['Right — isolates the salt.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Introduces a possible confounder; doesn’t strengthen.']),
    ],
  },
  {
    id: 'crime-police',
    difficulty: 3,
    text: 'Towns in the region that employ more police officers per resident have higher crime rates than towns that employ fewer. A local commentator concludes that hiring more police officers does not reduce crime and may even increase it.',
    questions: [
      Q('Which of the following most accurately describes a flaw in the commentator’s reasoning?',
        ['It overlooks the possibility that high crime rates lead towns to hire more police.', 'It relies on data from only one town.', 'It assumes that all police officers are equally effective.', 'It confuses the number of crimes with the number of arrests.', 'It fails to define what counts as a crime.'],
        0,
        'Reverse causation: towns with more crime hire more police. The correlation doesn’t show police cause crime.',
        ['Right — the causal arrow may run the other way.', 'The data are regional, from many towns.', 'Not the central flaw.', 'Not suggested by the argument.', 'Not the central flaw.']),
      Q('Which of the following studies would best help evaluate the commentator’s conclusion?',
        ['Comparing crime rates within the same towns before and after they increased their police forces', 'Surveying residents about their opinions of the police', 'Counting the number of police stations in each town', 'Measuring the average salary of police officers', 'Recording how many officers retire each year'],
        0,
        'Before/after within the same towns controls for the fact that high-crime towns differ from low-crime towns.',
        ['Right.', 'Opinions don’t measure crime effects.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'ebook',
    difficulty: 2,
    text: 'Sales of e-books grew rapidly for several years but have recently leveled off, while sales of printed books have held steady. A publishing analyst concludes that readers have lost interest in e-books.',
    questions: [
      Q('Which of the following, if true, most weakens the analyst’s conclusion?',
        ['The number of people borrowing e-books from public libraries has grown sharply in recent years.', 'Printed books are more expensive to produce than e-books.', 'Some readers prefer printed books for gifts.', 'E-book readers were introduced over a decade ago.', 'Several publishers have raised e-book prices.'],
        0,
        'If e-book reading shifted to library borrowing, interest hasn’t fallen — sales just don’t capture it.',
        ['Right — interest continues through another channel.', 'Irrelevant to interest.', 'Irrelevant.', 'Irrelevant.', 'This offers another explanation for flat sales, but (A) shows ongoing interest more directly.']),
      Q('The analyst’s argument depends on the assumption that',
        ['e-book sales are a reliable measure of readers’ interest in e-books', 'printed books will soon disappear', 'e-books are cheaper than printed books', 'readers read fewer books overall', 'e-book prices have not changed'],
        0,
        'The conclusion is about interest; the evidence is about sales. The argument assumes sales track interest.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not strictly required.']),
    ],
  },
  {
    id: 'four-day-week',
    difficulty: 2,
    text: 'A software firm switched half of its teams to a four-day workweek for six months. Those teams completed as many projects as the teams that continued working five days. The firm’s managers conclude that switching every team to a four-day week would not reduce the firm’s output.',
    questions: [
      Q('Which of the following, if true, most weakens the managers’ conclusion?',
        ['The teams chosen for the trial were those whose projects were nearing completion when the trial began.', 'Employees on four-day teams reported higher job satisfaction.', 'The trial took place during the firm’s busiest season.', 'Other firms have adopted four-day weeks.', 'Four-day teams held fewer meetings.'],
        0,
        'If trial teams were finishing projects anyway, their output during the trial overstates what four-day teams can do — the comparison is biased.',
        ['Right — the trial groups weren’t comparable.', 'Satisfaction supports, not weakens.', 'Busy season would make the result more impressive.', 'Irrelevant.', 'Could explain how they kept up — doesn’t weaken.']),
      Q('Which of the following, if true, most strengthens the conclusion?',
        ['The teams in the trial were randomly selected and had comparable workloads to the others.', 'The firm plans to hire more programmers.', 'Most employees wanted to join the trial.', 'The firm’s competitors work five-day weeks.', 'The trial lasted six months.'],
        0,
        'Random selection with comparable workloads makes the two groups fair comparisons, so equal output is meaningful.',
        ['Right.', 'Irrelevant.', 'Could introduce self-selection concerns.', 'Irrelevant.', 'Already stated.']),
    ],
  },
  {
    id: 'vaccine-flu',
    difficulty: 3,
    text: 'This winter, a higher percentage of hospital patients with influenza had been vaccinated than in any previous winter. Some commentators take this as evidence that this year’s vaccine is ineffective.',
    questions: [
      Q('Which of the following, if true, best undermines the commentators’ reasoning?',
        ['A much higher percentage of the general population was vaccinated this winter than in previous winters.', 'The vaccine was produced using a new method.', 'Influenza patients are usually older adults.', 'This winter’s influenza season began early.', 'Some vaccinated people experience mild side effects.'],
        0,
        'If far more people were vaccinated overall, vaccinated people will make up a larger share of every group, including patients — even if the vaccine works. The base rate matters.',
        ['Right — base-rate explanation.', 'Irrelevant to effectiveness evidence.', 'Doesn’t address the reasoning.', 'Irrelevant.', 'Irrelevant.']),
      Q('To evaluate whether the vaccine was effective, it would be most useful to compare',
        ['the influenza rate among vaccinated people with the rate among unvaccinated people', 'the number of doctors who recommended the vaccine', 'the cost of this year’s vaccine with last year’s', 'hospital admissions for broken bones this winter and last', 'the number of vaccine doses shipped to each state'],
        0,
        'Effectiveness is about whether vaccinated people get sick at a lower RATE than unvaccinated people.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'solar-panels',
    difficulty: 2,
    text: 'Homeowners in Pinecrest who installed solar panels last year reduced their electricity bills by an average of 30 percent. A local installer argues that any Pinecrest homeowner who installs solar panels will save money.',
    questions: [
      Q('The installer’s argument is flawed because it',
        ['ignores the cost of buying and installing the panels', 'relies on data from a different town', 'assumes electricity prices will fall', 'confuses average savings with total savings', 'depends on the opinions of homeowners'],
        0,
        '“Save money” requires that bill reductions exceed the upfront cost. The argument considers only the reduction.',
        ['Right — costs are ignored.', 'The data are from Pinecrest.', 'No such assumption.', 'Not the main flaw.', 'The data are bill reductions, not opinions.']),
      Q('Which of the following, if true, would most weaken the installer’s claim that ANY homeowner will save?',
        ['The homes that installed panels last year were mostly those with large, south-facing roofs.', 'Electricity rates in Pinecrest are average for the state.', 'Solar panels last about twenty-five years.', 'Some homeowners installed panels for environmental reasons.', 'The installer offers financing.'],
        0,
        'If early adopters had the best roofs, homes without them may save far less — “any homeowner” overgeneralizes.',
        ['Right — unrepresentative sample.', 'Irrelevant.', 'Supports long-term savings.', 'Irrelevant to savings.', 'Irrelevant.']),
    ],
  },
  {
    id: 'language-apps',
    difficulty: 1,
    text: 'People who use the language-learning app Lingo for at least a year are more likely to pass a proficiency exam than people who use it for less than a month. The company concludes that using Lingo for a year makes people proficient.',
    questions: [
      Q('Which of the following, if true, most weakens the company’s conclusion?',
        ['People who keep using any study method for a year tend to be more motivated learners, who also study in other ways.', 'Lingo offers lessons in twelve languages.', 'The proficiency exam is widely recognized.', 'Many people download Lingo but never use it.', 'Lingo’s lessons take about ten minutes a day.'],
        0,
        'Persistence and motivation could explain both long app use and exam success — the app may not be the cause.',
        ['Right — confounding factor.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant to the comparison.', 'Irrelevant.']),
      Q('The argument assumes that',
        ['the difference in exam results is due to the app rather than to other differences between the groups', 'the exam is too difficult for most learners', 'people who stop using the app within a month learn nothing', 'all users study the same language', 'the app is free'],
        0,
        'The argument attributes the difference to the app itself.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not required.']),
    ],
  },
  {
    id: 'bakery-hours',
    difficulty: 1,
    text: 'Maple Street Bakery extended its closing time from 6 p.m. to 9 p.m., hoping to increase profits. But in the following month, profits fell, even though sales rose slightly.',
    questions: [
      Q('Which of the following, if true, most helps to explain how profits could fall even though sales rose?',
        ['The cost of staffing and lighting the bakery for the extra hours exceeded the revenue from the additional sales.', 'Most customers visit in the morning.', 'A new café opened nearby.', 'The bakery raised prices on bread.', 'Sales of cakes fell slightly.'],
        0,
        'Profit = revenue − cost. If the extra hours cost more than they brought in, profit falls even as sales rise.',
        ['Right.', 'Explains little about profit vs. sales.', 'Would reduce sales, but sales rose.', 'Would tend to raise revenue.', 'Overall sales still rose.']),
      Q('Which conclusion is most strongly supported by the information given?',
        ['The bakery’s costs rose more than its revenue during that month.', 'The bakery will return to its old hours.', 'Customers prefer shopping before 6 p.m.', 'Competitors’ profits rose.', 'The bakery’s prices were too low.'],
        0,
        'If sales (revenue) rose but profit fell, costs must have risen by more than revenue did.',
        ['Right — must be true.', 'A prediction.', 'Not supported.', 'Not discussed.', 'Not supported.']),
    ],
  },
  {
    id: 'traffic-cameras',
    difficulty: 2,
    text: 'After Brookfield installed cameras at five intersections to catch drivers running red lights, collisions at those intersections fell by 25 percent. The mayor proposes installing cameras at all fifty of the city’s signalized intersections, predicting a similar drop in collisions citywide.',
    questions: [
      Q('Which of the following, if true, most weakens the mayor’s prediction?',
        ['The five intersections were chosen because they had had the city’s highest collision rates the year before.', 'Cameras are expensive to maintain.', 'Some drivers dislike the cameras.', 'The cameras also photograph speeding vehicles.', 'Neighboring cities are considering cameras.'],
        0,
        'Regression to the mean: intersections picked for unusually high collision rates would likely improve anyway, and other intersections may have less room to improve.',
        ['Right.', 'Cost doesn’t affect collisions.', 'Irrelevant.', 'Would tend to strengthen.', 'Irrelevant.']),
      Q('Which of the following would be most useful to know in evaluating the prediction?',
        ['How collision rates changed during the same period at similar intersections without cameras', 'How many tickets the cameras issued', 'Who manufactured the cameras', 'How many residents own cars', 'Whether cameras are popular with voters'],
        0,
        'A comparison group shows whether the drop was due to the cameras or to something that affected all intersections.',
        ['Right.', 'Tickets don’t measure collisions.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'organic-sales',
    difficulty: 2,
    text: 'Grocers in Eastfield report that sales of organic produce have tripled over the past decade. Since organic produce is generally more expensive than conventional produce, the increase shows that Eastfield residents have become wealthier over the decade.',
    questions: [
      Q('Which of the following, if true, most weakens the argument?',
        ['Over the decade the price gap between organic and conventional produce narrowed substantially.', 'Eastfield grocers also sell organic dairy products.', 'Some residents grow their own vegetables.', 'The population of Eastfield has remained stable.', 'Organic produce is sold at farmers’ markets.'],
        0,
        'If organic got relatively cheaper, residents could buy more without becoming wealthier.',
        ['Right — alternative explanation.', 'Irrelevant.', 'Irrelevant.', 'Would slightly strengthen by ruling out population growth.', 'Irrelevant.']),
      Q('Which of the following, if true, provides the best alternative explanation for the increase in sales?',
        ['Awareness of the environmental benefits of organic farming grew among Eastfield residents.', 'Most Eastfield grocers are independently owned.', 'Organic produce spoils faster than conventional produce.', 'Conventional produce is sold in larger packages.', 'The decade included a recession.'],
        0,
        'Changing preferences, not wealth, could explain higher organic sales.',
        ['Right.', 'Irrelevant.', 'Would, if anything, reduce sales.', 'Irrelevant.', 'A recession would work against the argument’s conclusion but doesn’t explain rising sales.']),
    ],
  },
  {
    id: 'standing-desks',
    difficulty: 2,
    text: 'A company gave standing desks to employees in its marketing department. Six months later, employees in that department reported fewer back problems than they had before. The company concludes that standing desks reduce back problems.',
    questions: [
      Q('Which of the following, if true, most weakens the conclusion?',
        ['During the same six months, the company also began offering free weekly physical therapy sessions to all employees.', 'Standing desks cost more than ordinary desks.', 'The marketing department is the company’s largest.', 'Some employees did not use their standing desks.', 'The company’s other departments did not receive standing desks.'],
        0,
        'A simultaneous intervention (physical therapy) could explain the improvement.',
        ['Right — confounding change.', 'Irrelevant.', 'Irrelevant.', 'Weakens a little, but (A) offers a direct alternative cause.', 'This is the comparison that could help — not a weakener.']),
      Q('Which of the following would most help evaluate the conclusion?',
        ['Whether back problems also declined over the same period in departments that did not receive standing desks', 'The brand of the standing desks', 'The average age of marketing employees', 'How many hours per day the office is open', 'Whether employees liked the new desks'],
        0,
        'A comparison group reveals whether the improvement was specific to the desks.',
        ['Right.', 'Irrelevant.', 'Only marginally relevant.', 'Irrelevant.', 'Irrelevant to back problems.']),
    ],
  },
  {
    id: 'library-closing',
    difficulty: 2,
    text: 'Council member: The Oakdale branch library should be closed. Its circulation — the number of books checked out — has fallen by half over five years, which proves that residents no longer need it.',
    questions: [
      Q('Which of the following, if true, most weakens the council member’s argument?',
        ['Over the same five years, use of the branch’s computers, study rooms, and children’s programs has doubled.', 'The branch building is fifty years old.', 'Circulation has also fallen at the main library.', 'The branch is open fewer hours than the main library.', 'Oakdale’s population has grown slightly.'],
        0,
        'The argument equates “need” with circulation. Rising use of other services shows residents still need the branch.',
        ['Right.', 'Irrelevant to need.', 'Doesn’t show residents need this branch.', 'Might explain lower circulation, but doesn’t show need as directly.', 'Slightly relevant, but weak.']),
      Q('The argument assumes that',
        ['book circulation is an adequate measure of residents’ need for the branch', 'the main library can absorb all Oakdale’s patrons', 'the branch is too expensive to operate', 'books are the library’s only resource', 'residents prefer e-books'],
        0,
        'It moves from falling circulation to “no longer need it.”',
        ['Right.', 'Not stated or required.', 'Not stated.', 'Similar, but stronger than required; (A) is the needed assumption.', 'Not required.']),
    ],
  },
  {
    id: 'honey-bees-pesticide',
    difficulty: 3,
    text: 'In regions where a certain pesticide is widely used, honeybee colonies have declined sharply. Yet in several regions where the pesticide has never been used, colonies have also declined.',
    questions: [
      Q('Which of the following, if true, most helps to reconcile the two observations with the hypothesis that the pesticide harms bees?',
        ['Honeybee declines have multiple causes, including a parasitic mite that is present in all the regions studied.', 'The pesticide is expensive.', 'Some regions use different pesticides.', 'Beekeepers in all regions use similar hives.', 'Honeybees forage over several kilometers.'],
        0,
        'If another cause (mites) is present everywhere, colonies can decline without the pesticide — while the pesticide can still be an additional cause where it is used.',
        ['Right — multiple causes.', 'Irrelevant.', 'Possible but vaguer; doesn’t explain declines in untreated regions as clearly.', 'Irrelevant.', 'Could suggest drift, but the regions never used it.']),
      Q('Which of the following would provide the strongest evidence that the pesticide contributes to colony decline?',
        ['Within the same regions, colonies near treated fields decline faster than colonies far from them.', 'The pesticide is used on many crops.', 'Bees visit many kinds of flowers.', 'The pesticide’s manufacturer disputes the claim.', 'Declines were first noticed in the 1990s.'],
        0,
        'Comparing nearby vs. distant colonies within a region controls for regional factors like mites and climate.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Not evidence either way.', 'Irrelevant.']),
    ],
  },
  {
    id: 'remote-work',
    difficulty: 2,
    text: 'Employees at Norsk Corp who work from home at least three days a week report higher job satisfaction than those who work in the office full-time. Norsk’s management plans to require all employees to work from home three days a week, expecting overall satisfaction to rise.',
    questions: [
      Q('Which of the following, if true, most weakens management’s expectation?',
        ['The employees who currently work from home chose to do so, while many office workers have said they prefer the office.', 'Norsk’s offices are located downtown.', 'Remote employees use video conferencing.', 'Norsk has offices in three countries.', 'Some employees work from home only on Fridays.'],
        0,
        'Self-selection: current remote workers wanted to work from home. Forcing people who prefer the office may lower their satisfaction.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Management’s plan assumes that',
        ['the satisfaction gap is caused by working from home rather than by who chose to do it', 'employees will be more productive at home', 'office space is expensive', 'all employees have home internet', 'satisfaction can be measured precisely'],
        0,
        'The plan assumes that working from home causes satisfaction for anyone who does it.',
        ['Right.', 'Productivity is not the goal stated.', 'Not stated.', 'Plausibly needed in practice, but not the core logical assumption about satisfaction.', 'Not required.']),
    ],
  },
  {
    id: 'ancient-grain',
    difficulty: 3,
    text: 'Archaeologists found large quantities of charred barley in a Bronze Age settlement but almost no wheat. They concluded that the settlement’s inhabitants ate far more barley than wheat.',
    questions: [
      Q('Which of the following, if true, most weakens the archaeologists’ conclusion?',
        ['Barley was commonly parched over fire before storage, whereas wheat was not, so barley grains were far more likely to become charred and survive.', 'Barley grows well in poor soil.', 'Other Bronze Age settlements also grew barley.', 'The settlement was near a river.', 'Charred grain can be dated using radiocarbon methods.'],
        0,
        'Preservation bias: if barley was much more likely to be charred (and thus preserved), the record overstates barley relative to wheat.',
        ['Right — preservation bias.', 'Irrelevant to consumption.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('The archaeologists’ reasoning assumes that',
        ['the relative amounts of surviving charred grain reflect the relative amounts eaten', 'wheat was unknown in the Bronze Age', 'barley was imported', 'the settlement was abandoned suddenly', 'charred grain is easy to identify'],
        0,
        'They infer consumption from what survived.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not the key assumption.']),
    ],
  },
  {
    id: 'app-downloads',
    difficulty: 1,
    text: 'The fitness app StepUp was downloaded twice as many times this year as last year. Its developers conclude that twice as many people are exercising with StepUp this year.',
    questions: [
      Q('Which of the following, if true, most weakens the developers’ conclusion?',
        ['Most people who download StepUp stop using it within a week.', 'StepUp is available on two kinds of phones.', 'StepUp’s competitors also grew.', 'StepUp added a nutrition feature.', 'StepUp’s price did not change.'],
        0,
        'Downloads ≠ people exercising. If most downloaders quit quickly, doubling downloads doesn’t mean doubling active users.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Might explain downloads but doesn’t weaken.', 'Irrelevant.']),
      Q('The developers’ argument depends on the assumption that',
        ['the proportion of downloaders who actually exercise with the app did not fall', 'StepUp is the most popular fitness app', 'people who exercise download several apps', 'last year’s users all stopped using the app', 'downloads are free'],
        0,
        'To go from “twice the downloads” to “twice the exercisers,” the share of downloaders who exercise must not have dropped.',
        ['Right.', 'Not required.', 'Not required.', 'Not required, and would actually complicate the count.', 'Not required.']),
    ],
  },
  {
    id: 'cheaper-flights',
    difficulty: 3,
    text: 'Airline X cut its fares on the Denver–Boston route by 20 percent, and the number of passengers it carried on that route rose by 50 percent. Airline X’s executives conclude that cutting fares on all its routes would increase its total revenue.',
    questions: [
      Q('Which of the following, if true, most weakens the executives’ conclusion?',
        ['The Denver–Boston passengers gained were mostly travelers who switched from competitors that did not match the cut, while on most other routes competitors routinely match fare cuts.', 'The Denver–Boston route is one of Airline X’s longest.', 'Fuel prices rose during the period.', 'Airline X flies to thirty cities.', 'Some passengers paid for extra luggage.'],
        0,
        'The gain came from stealing competitors’ passengers who didn’t match. Where competitors match, a fare cut won’t attract many new passengers, and revenue may fall.',
        ['Right.', 'Irrelevant.', 'Affects costs, not revenue.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following can be properly concluded from the information about the Denver–Boston route?',
        ['Airline X’s revenue on that route increased after the fare cut.', 'Airline X’s profit on that route increased.', 'Competitors lost money on that route.', 'Fare cuts always increase revenue.', 'Passengers prefer Airline X to its competitors.'],
        0,
        '0.8 × price × 1.5 × passengers = 1.2 × the old revenue → revenue rose 20% on that route (assuming the 20% cut applied to all its fares there).',
        ['Right — 0.8 × 1.5 = 1.2.', 'Costs are unknown.', 'Not established.', 'Overgeneralization.', 'Not established.']),
    ],
  },
  {
    id: 'mayor-poll',
    difficulty: 1,
    text: 'An online poll on a political blog found that 80 percent of respondents disapprove of the mayor. The blog’s author concludes that the mayor is unpopular with most of the city’s residents.',
    questions: [
      Q('The author’s reasoning is most vulnerable to the objection that',
        ['the respondents may not be representative of the city’s residents', 'the poll asked too many questions', 'the mayor was recently elected', 'online polls are always illegal', '80 percent is not a majority'],
        0,
        'Readers of a political blog who choose to respond are a self-selected, likely unrepresentative sample.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Absurd.', '80% is a majority.']),
      Q('Which of the following, if true, most weakens the conclusion?',
        ['The blog is known mainly for criticizing the mayor and is read chiefly by the mayor’s opponents.', 'The poll was open for a week.', 'The blog has many readers.', 'The mayor has served two terms.', 'Some respondents left comments.'],
        0,
        'A readership of opponents would produce high disapproval regardless of citywide opinion.',
        ['Right.', 'Irrelevant.', 'Size doesn’t fix bias.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'wolf-reintro',
    difficulty: 3,
    text: 'After wolves were reintroduced to a national park, the number of elk declined and willow trees along the park’s streams, which elk browse, began to recover. Some ecologists concluded that wolves caused the willow recovery by reducing elk numbers.',
    questions: [
      Q('Which of the following, if true, would most strengthen the ecologists’ conclusion?',
        ['In areas of the park where wolves rarely hunt, willows have not recovered even though elk numbers there also declined somewhat.', 'Willows grow best near water.', 'Elk are the wolves’ main prey.', 'The park attracts many tourists.', 'Beavers eat willow bark.'],
        0,
        'Where wolves are absent, willows didn’t recover — linking recovery to wolves specifically (perhaps by changing elk behavior as well as numbers).',
        ['Right — links recovery to wolf presence.', 'Background.', 'Background; doesn’t link to willows.', 'Irrelevant.', 'Introduces another factor, not a strengthener.']),
      Q('Which of the following, if true, would most weaken the ecologists’ conclusion?',
        ['A series of unusually wet years, which favor willow growth, coincided with the period of recovery.', 'Wolves also prey on deer.', 'Elk migrate out of the park in winter.', 'Willows are common throughout the region.', 'The wolves were brought from another country.'],
        0,
        'An alternative cause: wet years could explain willow recovery.',
        ['Right.', 'Irrelevant.', 'Irrelevant to the causal claim.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'textbook-price',
    difficulty: 2,
    text: 'A university began offering free online textbooks for its introductory courses. In the first year, the average grade in those courses rose. The provost concludes that cost had been preventing some students from obtaining textbooks, which lowered their grades.',
    questions: [
      Q('Which of the following, if true, most strengthens the provost’s conclusion?',
        ['The grade increase was concentrated among students receiving financial aid, many of whom had previously reported going without textbooks.', 'The online textbooks are shorter than the printed ones.', 'Introductory courses are large.', 'Faculty liked the online textbooks.', 'The university raised tuition that year.'],
        0,
        'If gains were largest among students who had lacked textbooks for cost reasons, the explanation fits.',
        ['Right.', 'Might suggest another cause, if anything.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following, if true, most weakens the conclusion?',
        ['In the same year, the university changed its grading policy to allow students to retake exams.', 'Some students printed the online textbooks.', 'The online textbooks were written by the course instructors.', 'Students can access the textbooks on phones.', 'Enrollment in introductory courses rose.'],
        0,
        'A new retake policy is an alternative explanation for higher grades.',
        ['Right.', 'Irrelevant.', 'Could matter, but less direct than (A).', 'Irrelevant.', 'Irrelevant to average grades.']),
    ],
  },
  {
    id: 'noise-plants',
    difficulty: 2,
    text: 'An office manager placed large potted plants throughout an open-plan office. Afterward, employees’ complaints about noise dropped by half. The manager concluded that the plants absorbed enough sound to make the office quieter.',
    questions: [
      Q('Which of the following, if true, most weakens the manager’s conclusion?',
        ['Measurements taken before and after the plants were added showed no change in the office’s noise levels.', 'The plants required frequent watering.', 'Employees said the plants made the office more pleasant.', 'Some plants were placed near windows.', 'The office has forty employees.'],
        0,
        'If measured noise didn’t change, the plants didn’t make the office quieter; complaints fell for another reason.',
        ['Right.', 'Irrelevant.', 'Suggests a different reason complaints dropped — actually weakens too, but less decisively than a direct measurement.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following offers the best alternative explanation for the drop in complaints?',
        ['The plants made employees feel more comfortable, so they were less bothered by the same noise.', 'Plants release oxygen.', 'The plants were expensive.', 'Noise complaints are common in offices.', 'Some employees wear headphones.'],
        0,
        'Complaints reflect how bothered people are, not only noise level; a more pleasant space could reduce annoyance.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Would have been true before too — doesn’t explain a change.']),
    ],
  },
  {
    id: 'bridge-traffic',
    difficulty: 3,
    text: 'To reduce congestion, the city built a second bridge across the river. A year later, traffic on the original bridge was just as heavy as before, and the total number of vehicles crossing the river had increased substantially.',
    questions: [
      Q('Which of the following, if true, best explains these results?',
        ['The new crossing made trips across the river more convenient, so people made river crossings they previously would have avoided.', 'The new bridge is narrower than the original bridge.', 'Construction of the new bridge took three years.', 'Tolls on both bridges are the same.', 'The original bridge was recently repainted.'],
        0,
        'Induced demand: added capacity makes driving across easier, generating new trips that fill the old bridge again.',
        ['Right.', 'Doesn’t explain the increase in total crossings.', 'Irrelevant.', 'Doesn’t explain.', 'Irrelevant.']),
      Q('The results most strongly support which conclusion?',
        ['Adding road capacity does not necessarily reduce congestion on existing roads.', 'The second bridge should be demolished.', 'Tolls always reduce traffic.', 'Most drivers prefer the original bridge.', 'Public transit ridership fell.'],
        0,
        'Traffic on the original bridge didn’t fall even with a new bridge.',
        ['Right.', 'Not supported.', 'Tolls aren’t discussed.', 'Not supported.', 'Not discussed.']),
    ],
  },
  {
    id: 'chess-math',
    difficulty: 2,
    text: 'Children who belong to school chess clubs tend to score higher on math tests than children who do not. An education advocate argues that schools should add chess to the curriculum in order to improve math achievement.',
    questions: [
      Q('Which of the following, if true, most seriously undermines the advocate’s argument?',
        ['Children who are already strong in math are more likely than others to be drawn to chess clubs.', 'Chess sets are inexpensive.', 'Chess clubs meet after school.', 'Some chess players also play checkers.', 'Chess has been played for centuries.'],
        0,
        'Reverse causation / self-selection: math ability may lead to chess, not the other way around.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following findings would most support the advocate’s proposal?',
        ['In a study where students were randomly assigned to chess instruction or another activity, the chess group’s math scores improved more.', 'Many parents enjoy chess.', 'Professional chess players are paid well.', 'Chess clubs are popular in several countries.', 'Chess tournaments are held on weekends.'],
        0,
        'Random assignment removes self-selection and tests whether chess causes math gains.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'hospital-deaths',
    difficulty: 3,
    text: 'Mercy Hospital has a higher death rate among its patients than nearby Valley Hospital. A health reporter concludes that patients receive worse care at Mercy than at Valley.',
    questions: [
      Q('Which of the following, if true, most seriously weakens the reporter’s conclusion?',
        ['Mercy is the region’s trauma center and receives the most critically ill and injured patients.', 'Mercy is larger than Valley.', 'Valley opened more recently.', 'Both hospitals employ skilled surgeons.', 'Mercy’s parking lot is smaller.'],
        0,
        'Different patient mix: a hospital taking the sickest patients will have a higher death rate even with excellent care.',
        ['Right.', 'Size alone doesn’t explain a rate.', 'Irrelevant.', 'Doesn’t address the comparison.', 'Irrelevant.']),
      Q('Which comparison would provide the best evidence about quality of care?',
        ['Death rates for patients with similar conditions and similar severity at the two hospitals', 'The number of doctors at each hospital', 'Patient satisfaction surveys', 'Each hospital’s annual budget', 'The age of each hospital’s buildings'],
        0,
        'Comparing like with like controls for patient mix.',
        ['Right.', 'Irrelevant.', 'Measures satisfaction, not outcomes.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'sunscreen',
    difficulty: 2,
    text: 'A survey found that people who regularly use sunscreen are more likely to have been diagnosed with skin cancer than people who do not. The survey’s authors caution against concluding that sunscreen causes skin cancer.',
    questions: [
      Q('Which of the following, if true, best supports the authors’ caution?',
        ['People with fair skin, who are at higher risk of skin cancer, are also more likely to use sunscreen regularly.', 'Sunscreen is sold in many strengths.', 'Skin cancer is more common in sunny climates.', 'Some sunscreens are waterproof.', 'Most people apply too little sunscreen.'],
        0,
        'A common cause (fair skin) explains both higher sunscreen use and higher cancer risk.',
        ['Right.', 'Irrelevant.', 'Relevant background, but doesn’t link sunscreen use and risk.', 'Irrelevant.', 'Might weaken sunscreen’s protection, but doesn’t explain the correlation.']),
      Q('The situation described is most similar to which of the following?',
        ['Towns with more firefighters have more fires, but firefighters do not cause fires.', 'Students who study more get better grades because studying helps.', 'A drug reduced symptoms in a randomized trial.', 'Prices rose after a tax increase.', 'A car’s speed determines its travel time.'],
        0,
        'Both involve a correlation that doesn’t reflect a causal effect of the first factor on the second.',
        ['Right.', 'A plausible causal claim.', 'A controlled result.', 'A plausible causal claim.', 'A definitional relationship.']),
    ],
  },
  {
    id: 'price-match',
    difficulty: 2,
    text: 'Electronics retailer Voltra introduced a policy of matching any competitor’s lower price. Afterward, its sales rose, but so did the number of customers who returned items within a week.',
    questions: [
      Q('Which of the following, if true, best explains the increase in returns?',
        ['Some customers bought items at Voltra, found a lower price elsewhere, and returned the item rather than requesting a price match.', 'Voltra sells mostly televisions.', 'Voltra extended its store hours.', 'Competitors did not introduce similar policies.', 'Voltra’s return policy has not changed.'],
        0,
        'Price-matching encouraged comparison shopping; some who found a better deal returned items instead of claiming a match.',
        ['Right.', 'Irrelevant.', 'Irrelevant to returns.', 'Doesn’t explain returns.', 'Doesn’t explain the increase.']),
      Q('Which of the following would be most useful for Voltra to know in evaluating whether the policy has been profitable?',
        ['Whether the profit from the additional sales exceeded the cost of matched prices and processed returns', 'Whether competitors advertise on television', 'How many employees work at each store', 'Whether customers liked the store layout', 'The number of product brands Voltra carries'],
        0,
        'Profitability depends on the extra profit versus the extra costs the policy created.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'volunteers-health',
    difficulty: 2,
    text: 'A long-term study found that older adults who volunteer regularly live longer, on average, than those who do not. A columnist concludes that volunteering improves health.',
    questions: [
      Q('Which of the following, if true, most weakens the columnist’s conclusion?',
        ['People in poor health are less able to volunteer.', 'Volunteering is common in many countries.', 'Some volunteers work with children.', 'The study lasted twenty years.', 'Many volunteers are retired.'],
        0,
        'Poor health prevents volunteering — so volunteers may live longer because they were healthier to begin with (reverse causation).',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following, if true, would most strengthen the conclusion?',
        ['The longevity advantage persisted even when volunteers were compared with non-volunteers who had the same health at the start of the study.', 'Volunteers report feeling useful.', 'Volunteer organizations need more help.', 'Retirees have more free time.', 'Some people volunteer for decades.'],
        0,
        'Controlling for baseline health rules out the reverse-causation explanation.',
        ['Right.', 'Plausible mechanism but weaker evidence.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'recycling-bins',
    difficulty: 1,
    text: 'After the town of Kessler gave every household a free recycling bin, the amount of material recycled in the town doubled. A neighboring town, Linden, plans to do the same and expects its recycling to double as well.',
    questions: [
      Q('Which of the following, if true, most weakens Linden’s expectation?',
        ['Most Linden households already have recycling bins.', 'Kessler is larger than Linden.', 'Recycling bins are made of plastic.', 'Linden’s council supports recycling.', 'Kessler’s bins are collected weekly.'],
        0,
        'If Linden households already have bins, giving free bins won’t change behavior the way it did in Kessler.',
        ['Right.', 'Size is irrelevant to doubling.', 'Irrelevant.', 'Irrelevant.', 'Doesn’t address Linden.']),
      Q('Linden’s expectation depends on the assumption that',
        ['conditions in Linden are relevantly similar to those in Kessler before the bins were distributed', 'recycling is profitable', 'Kessler’s residents are wealthier', 'the bins will be the same color', 'recycled material is sold'],
        0,
        'Reasoning by analogy requires relevant similarity.',
        ['Right.', 'Not required.', 'Not required.', 'Irrelevant.', 'Not required.']),
    ],
  },
  {
    id: 'phone-ban',
    difficulty: 2,
    text: 'After Ridgeway High banned phones during class, the average test score rose by 6 points. The principal argues that phones had been distracting students and lowering their performance.',
    questions: [
      Q('Which of the following, if true, would most strengthen the principal’s argument?',
        ['At a demographically similar school that did not ban phones, scores were unchanged over the same period.', 'Most students own phones.', 'Some teachers used phones in class.', 'The ban was popular with parents.', 'Students can use phones at lunch.'],
        0,
        'A comparison school without the ban rules out a general trend as the cause.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following, if true, would most weaken it?',
        ['The state replaced its standardized test with an easier version the same year.', 'The ban was enforced strictly.', 'Students complained about the ban.', 'Phones can be used for research.', 'The school has a new library.'],
        0,
        'An easier test is an alternative explanation for higher scores.',
        ['Right.', 'Supports.', 'Irrelevant.', 'Irrelevant.', 'A minor alternative.']),
    ],
  },
  {
    id: 'coffee-shop',
    difficulty: 2,
    text: 'Owner: Our café should stop offering free Wi-Fi. Customers who use it stay for hours while buying only a single coffee, occupying tables that other customers could use.',
    questions: [
      Q('Which of the following, if true, most weakens the owner’s argument?',
        ['The café’s tables are rarely all occupied, even at the busiest times.', 'Wi-Fi costs the café little each month.', 'Some customers bring their own internet devices.', 'Other cafés offer free Wi-Fi.', 'Coffee prices have risen.'],
        0,
        'The argument assumes Wi-Fi users crowd out other customers. If tables are rarely full, no one is being turned away.',
        ['Right.', 'Irrelevant to the crowding argument.', 'Irrelevant.', 'Suggests a competitive risk, but doesn’t attack the reasoning as directly.', 'Irrelevant.']),
      Q('The owner’s argument assumes that',
        ['customers who would use the freed-up tables would spend more than the Wi-Fi users do', 'all customers use Wi-Fi', 'coffee is the café’s only product', 'Wi-Fi is expensive', 'customers prefer quiet'],
        0,
        'Removing Wi-Fi only helps if replacement customers would bring in more.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not required.']),
    ],
  },
];

const letters = 'ABCDE';

function build(a: Arg): Candidate[] {
  return a.questions.map((q, i) => ({
    key: `${a.id}:${i}`,
    group: `arg:${a.id}`,
    q: {
      kind: 'mcq' as const,
      prompt: q.prompt,
      options: q.options,
      correctIndex: q.answer,
      explanation: `${q.why} (Answer: ${letters[q.answer]}.)`,
      distractorNotes: q.notes.map((n, j) => (j === q.answer ? `✓ ${n}` : n)),
      difficulty: a.difficulty,
      stimulus: { passage: a.text },
    },
  }));
}

const crArguments: Generator = {
  id: 'cr-arguments',
  track: 'verbal',
  topic: 'Argument questions (critical reasoning)',
  lessonId: 'gre-rc-arguments',
  count: ARGUMENTS.reduce((n, a) => n + a.questions.length, 0),
  all: () => [...ARGUMENTS].sort((x, y) => x.difficulty - y.difficulty).flatMap(build),
};

export const ARGUMENT_GENERATORS: Generator[] = [crArguments];
