// Authored argument (critical reasoning) questions — the short-paragraph
// reading questions the GRE mixes into Verbal: find the assumption,
// weaken, strengthen, resolve a paradox, spot the flaw, evaluate, infer.
// Each argument carries two questions; every choice has a note.

import { type Candidate, type Generator, hashStr, mulberry32, shuffle } from '../engine.ts';

type Diff = 1 | 2 | 3;
interface AQ {
  prompt: string;
  options: string[];
  answer: number;
  why: string;
  notes: string[];
}
interface Arg {
  id: string;
  difficulty: Diff;
  text: string;
  questions: AQ[];
}
const Q = (prompt: string, options: string[], answer: number, why: string, notes: string[]): AQ => ({ prompt, options, answer, why, notes });

export const ARGUMENTS: Arg[] = [
  {
    id: 'bike-lanes',
    difficulty: 1,
    text: 'After the city of Harlow painted bike lanes on its main avenue, the number of cyclists counted on that avenue doubled within a year. The city council concludes that painting bike lanes on other streets will increase the total number of people who cycle in Harlow.',
    questions: [
      Q('The council’s conclusion depends on which of the following assumptions?',
        ['Most of the avenue’s new cyclists had not simply moved over from other Harlow streets.', 'Painting bike lanes costs the city very little compared with other road projects.', 'Most residents of Harlow already own a bicycle that they could ride on the new lanes.', 'Cyclists in Harlow generally prefer riding on wide avenues to riding on side streets.', 'Traffic accidents on the main avenue declined after the bike lanes were painted.'],
        0,
        'The evidence is about ONE avenue; the conclusion is about TOTAL cycling. If the avenue’s gain just came from cyclists switching routes, total cycling didn’t rise. Negate the assumption (“the extra cyclists were mostly route-switchers”) and the argument collapses.',
        ['Right — rules out the “they just moved” explanation.', 'Cost is irrelevant to whether cycling increases.', 'Not required: new cyclists could buy bikes.', 'Irrelevant to the total.', 'Safety is not the conclusion.']),
      Q('Which of the following, if true, would most weaken the council’s conclusion?',
        ['Cyclist counts on streets parallel to the avenue fell by about as much as its count rose.', 'Several other cities in the region have also painted bike lanes on their main avenues.', 'The new bike lanes on the main avenue were painted bright green to make them visible.', 'Some drivers objected to the bike lanes, saying they made the avenue more crowded.', 'Bicycle sales in Harlow rose slightly in the year after the lanes were painted.'],
        0,
        'If parallel streets lost as many cyclists as the avenue gained, cyclists simply rerouted — no increase in the total.',
        ['Right — the gain was redistribution.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant to cycling totals.', 'If anything, this slightly supports the conclusion.']),
    ],
  },
  {
    id: 'reading-scores',
    difficulty: 1,
    text: 'Students at Westbrook School who participate in the after-school reading club score higher on standardized reading tests than students who do not. Therefore, requiring all Westbrook students to join the reading club would raise the school’s average reading score.',
    questions: [
      Q('Which of the following, if true, most seriously weakens the argument?',
        ['Students who join the club voluntarily are the ones who already read most at home.', 'The reading club meets twice a week, after classes end, in the school library.', 'The club’s organizer is a former librarian who chooses the books the club reads.', 'Westbrook’s average reading score is already above the average for the state.', 'Some members of the reading club also play on one of the school’s sports teams.'],
        0,
        'Correlation vs. causation: if strong readers self-select into the club, the club may not be causing higher scores, so forcing others in may not help.',
        ['Right — self-selection explains the gap.', 'Irrelevant detail.', 'Irrelevant detail.', 'Irrelevant to whether the club causes gains.', 'Irrelevant.']),
      Q('The argument is most vulnerable to which criticism?',
        ['It treats a correlation as proof that one thing causes another.', 'It relies on a sample of students that is too small to be meaningful.', 'It attacks the character of the people who criticize the reading club.', 'It assumes what it sets out to prove by simply restating its premise.', 'It confuses a condition that is necessary with one that is sufficient.'],
        0,
        'Club members score higher (a correlation), and the argument concludes the club causes higher scores.',
        ['Right.', 'Sample size is not the issue raised.', 'No one is attacked.', 'The conclusion is not a restatement.', 'Not the flaw here.']),
    ],
  },
  {
    id: 'restaurant-revenue',
    difficulty: 2,
    text: 'Last year Café Loma raised the price of every item on its menu by 10 percent. Yet the café’s total revenue for the year was lower than in the previous year.',
    questions: [
      Q('Which of the following, if true, best explains the apparent discrepancy?',
        ['After the price increase, the café served substantially fewer customers.', 'The café’s costs for coffee beans and other ingredients rose last year.', 'Several nearby restaurants also raised their menu prices by 10 percent.', 'The café added two new items to its menu partway through the year.', 'The café’s owner considered lowering prices again late in the year.'],
        0,
        'Revenue = price × quantity. Higher prices can still yield lower revenue if the number of customers fell enough.',
        ['Right — fewer sales outweighed higher prices.', 'Costs affect profit, not revenue.', 'If anything, this would make customers less likely to leave.', 'New items would tend to add revenue.', 'Considering is not doing.']),
      Q('The information above most strongly supports which conclusion?',
        ['The café sold fewer menu items last year than in the previous year.', 'The price increase drove many of the café’s customers to other cafés.', 'The café will lower its prices this year to win back its customers.', 'The café’s profit fell last year along with its total revenue.', 'The café’s prices are now higher than those of its competitors.'],
        0,
        'If every price rose 10% but revenue fell, the quantity sold must have dropped (by more than enough to offset the higher prices). That’s the only thing that must be true.',
        ['Right — must be true.', 'Possible, but the cause is not established.', 'A prediction not supported.', 'Profit depends on costs, which aren’t given.', 'No comparison with competitors is given.']),
    ],
  },
  {
    id: 'fish-oil',
    difficulty: 2,
    text: 'In a survey of adults over sixty, those who reported taking fish-oil supplements daily had significantly lower rates of heart disease than those who did not. A supplement company cites this survey as evidence that fish oil prevents heart disease.',
    questions: [
      Q('Which of the following, if true, most weakens the company’s argument?',
        ['People who take daily supplements also tend to exercise more and eat better.', 'Fish oil is sold both as capsules and as a liquid that can be taken by spoon.', 'Heart disease is more common among adults over sixty than among younger adults.', 'The survey was conducted in several countries, in a number of languages.', 'Some brands of fish-oil supplements cost much more than others do.'],
        0,
        'A confounding variable: healthy habits could explain both supplement use and lower heart disease.',
        ['Right — alternative cause.', 'Irrelevant.', 'Irrelevant to the comparison between groups.', 'Doesn’t affect the causal inference.', 'Irrelevant.']),
      Q('Which of the following would it be most useful to know in evaluating the company’s argument?',
        ['Whether a randomized trial assigning fish oil found a similar difference', 'How the price of the company’s fish oil compares with that of rival brands', 'How many people over sixty live in the regions where the survey was conducted', 'Whether many people find the taste of fish-oil supplements unpleasant', 'How many different companies sell fish-oil supplements in the region'],
        0,
        'Randomization removes self-selection; a similar result in a randomized trial would support causation, and no difference would undercut it.',
        ['Right — tests causation directly.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'museum-free',
    difficulty: 2,
    text: 'The city museum eliminated its admission fee last year, and attendance rose by 40 percent. However, the museum’s total income from its gift shop and café also rose, more than making up for the lost admission revenue. The director therefore argues that other city museums should also eliminate their admission fees.',
    questions: [
      Q('The director’s argument assumes that',
        ['other museums would see similar rises in visitors and spending without fees', 'the city museum’s exhibits are better than those of the other city museums', 'most visitors dislike paying for admission and avoid museums that charge', 'the city museum’s gift shop sells most of its items for less than they cost', 'attendance at the city museum will keep rising every year from now on'],
        0,
        'The evidence comes from one museum; the recommendation is for others. It assumes their results would be similar.',
        ['Right — generalizing from one case.', 'The argument would work better if this were false.', 'Not required.', 'Would undermine, not support, the argument.', 'Not required for the recommendation.']),
      Q('Which of the following, if true, would most weaken the director’s argument?',
        ['Most other city museums have no gift shop or café.', 'The city museum’s free admission was widely advertised.', 'Many of the city museum’s new visitors were tourists.', 'The museum’s attendance had been falling before the change.', 'Other museums charge more than the city museum used to.'],
        0,
        'The city museum’s losses were offset by shop and café income. Museums without those can’t make up the lost revenue the same way.',
        ['Right — the offsetting mechanism is missing.', 'Irrelevant to other museums.', 'Doesn’t address other museums.', 'Makes the rise more impressive, if anything.', 'Would make eliminating fees costlier, but doesn’t address the offsetting shop and café income.']),
    ],
  },
  {
    id: 'tree-disease',
    difficulty: 2,
    text: 'A fungal disease has killed many elm trees in the Harrow Valley. Researchers found that elms growing near roads were far more likely to be infected than elms deep in the forest. They conclude that road salt, used in winter, weakens elms and makes them more susceptible to the fungus.',
    questions: [
      Q('Which of the following, if true, most weakens the researchers’ conclusion?',
        ['The fungus is spread by beetles that are drawn to open, sunny areas like road edges.', 'Road salt is also used heavily on the roads in the neighboring valleys every winter.', 'Elm trees are common throughout the region, both in forests and along its roads.', 'The disease was first detected in the Harrow Valley about ten years ago.', 'Some elms deep in the forest have also died, from drought rather than the fungus.'],
        0,
        'An alternative explanation for the pattern: beetles spreading the fungus concentrate near roads, regardless of salt.',
        ['Right — another reason road-edge elms get infected more.', 'Doesn’t address the explanation.', 'Irrelevant.', 'Irrelevant.', 'A different cause of death, not infection.']),
      Q('Which of the following, if true, most strengthens the conclusion?',
        ['Elms near roads that are never salted are infected no more often than forest elms.', 'Road salt also damages the bodies of cars that are driven on the valley’s roads.', 'The same fungus also infects oak trees growing in the forests of the valley.', 'Many of the roads in the valley were built within the last twenty years.', 'Elms growing deep in the forest are generally older than elms along roads.'],
        0,
        'If unsalted roadside elms have normal infection rates, proximity to roads alone isn’t the cause — salt is.',
        ['Right — isolates the salt.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Introduces a possible confounder; doesn’t strengthen.']),
    ],
  },
  {
    id: 'crime-police',
    difficulty: 3,
    text: 'Towns in the region that employ more police officers per resident have higher crime rates than towns that employ fewer. A local commentator concludes that hiring more police officers does not reduce crime and may even increase it.',
    questions: [
      Q('Which of the following most accurately describes a flaw in the commentator’s reasoning?',
        ['It overlooks that high crime rates may lead towns to hire more police.', 'It relies on crime data gathered from only one of the towns in the region.', 'It assumes that every police officer is equally effective at preventing crime.', 'It confuses the number of crimes committed with the number of arrests made.', 'It never defines clearly which kinds of offenses should count as crimes.'],
        0,
        'Reverse causation: towns with more crime hire more police. The correlation doesn’t show police cause crime.',
        ['Right — the causal arrow may run the other way.', 'The data are regional, from many towns.', 'Not the central flaw.', 'Not suggested by the argument.', 'Not the central flaw.']),
      Q('Which of the following studies would best help evaluate the commentator’s conclusion?',
        ['Comparing crime in the same towns before and after they added police', 'Surveying residents of each town about their opinions of the police', 'Counting the number of police stations in each town in the region', 'Measuring the average salary that each town pays its police officers', 'Recording how many police officers retire from each force every year'],
        0,
        'Before/after within the same towns controls for the fact that high-crime towns differ from low-crime towns.',
        ['Right.', 'Opinions don’t measure crime effects.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'ebook',
    difficulty: 2,
    text: 'Sales of e-books grew rapidly for several years but have recently leveled off, while sales of printed books have held steady. A publishing analyst concludes that readers have lost interest in e-books.',
    questions: [
      Q('Which of the following, if true, most weakens the analyst’s conclusion?',
        ['The number of people borrowing e-books from public libraries has grown sharply.', 'Printed books are more expensive for publishers to produce than e-books are.', 'Some readers prefer to buy printed books when they are giving them as gifts.', 'Dedicated e-book readers were first introduced more than a decade ago.', 'Several large publishers have raised the prices of their e-books recently.'],
        0,
        'If e-book reading shifted to library borrowing, interest hasn’t fallen — sales just don’t capture it.',
        ['Right — interest continues through another channel.', 'Irrelevant to interest.', 'Irrelevant.', 'Irrelevant.', 'This offers another explanation for flat sales, but library borrowing shows ongoing interest more directly.']),
      Q('The analyst’s argument depends on the assumption that',
        ['e-book sales are a reliable measure of readers’ interest in e-books', 'printed books will soon disappear as readers move to other formats', 'e-books are cheaper for readers to buy than the same printed books', 'readers are reading fewer books overall than they did a decade ago', 'the prices of e-books have not changed over the past several years'],
        0,
        'The conclusion is about interest; the evidence is about sales. The argument assumes sales track interest.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not strictly required.']),
    ],
  },
  {
    id: 'four-day-week',
    difficulty: 2,
    text: 'A software firm switched half of its teams to a four-day workweek for six months. Those teams completed as many projects as the teams that continued working five days. The firm’s managers conclude that switching every team to a four-day week would not reduce the firm’s output.',
    questions: [
      Q('Which of the following, if true, most weakens the managers’ conclusion?',
        ['The trial teams were those whose projects were nearly finished when it began.', 'Employees on the four-day teams reported higher job satisfaction than others.', 'The six-month trial took place during the firm’s busiest season of the year.', 'Several other software firms have recently adopted four-day workweeks.', 'The four-day teams held fewer and shorter meetings than the five-day teams.'],
        0,
        'If trial teams were finishing projects anyway, their output during the trial overstates what four-day teams can do — the comparison is biased.',
        ['Right — the trial groups weren’t comparable.', 'Satisfaction supports, not weakens.', 'Busy season would make the result more impressive.', 'Irrelevant.', 'Could explain how they kept up — doesn’t weaken.']),
      Q('Which of the following, if true, most strengthens the conclusion?',
        ['The trial teams were chosen at random and had workloads like the others’.', 'The firm plans to hire several more programmers over the coming year.', 'Most of the firm’s employees had asked to be included in the trial.', 'The firm’s main competitors all keep their teams on five-day weeks.', 'The trial ran for a full six months rather than for only a few weeks.'],
        0,
        'Random selection with comparable workloads makes the two groups fair comparisons, so equal output is meaningful.',
        ['Right.', 'Irrelevant.', 'Could introduce self-selection concerns.', 'Irrelevant.', 'Already stated.']),
    ],
  },
  {
    id: 'vaccine-flu',
    difficulty: 3,
    text: 'This winter, a higher percentage of hospital patients with influenza had been vaccinated than in any previous winter. Some commentators take this as evidence that this year’s vaccine is ineffective.',
    questions: [
      Q('Which of the following, if true, best undermines the commentators’ reasoning?',
        ['A far larger share of everyone was vaccinated this winter than in past winters.', 'This year’s vaccine was produced with a new and faster manufacturing method.', 'Most hospital patients with influenza, in any winter, are older adults.', 'This winter’s influenza season began several weeks earlier than it usually does.', 'Some vaccinated people experience mild side effects for a day or two.'],
        0,
        'If far more people were vaccinated overall, vaccinated people will make up a larger share of every group, including patients — even if the vaccine works. The base rate matters.',
        ['Right — base-rate explanation.', 'Irrelevant to effectiveness evidence.', 'Doesn’t address the reasoning.', 'Irrelevant.', 'Irrelevant.']),
      Q('To evaluate whether the vaccine was effective, it would be most useful to compare',
        ['the flu rate among vaccinated people with the rate among unvaccinated people', 'the number of doctors who recommended the vaccine this year with last year', 'the cost of this year’s vaccine with the cost of last year’s vaccine', 'hospital admissions for broken bones this winter with those last winter', 'the number of vaccine doses shipped to each state this year and last year'],
        0,
        'Effectiveness is about whether vaccinated people get sick at a lower RATE than unvaccinated people.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'solar-panels',
    difficulty: 2,
    text: 'Homeowners in Pinecrest who installed solar panels last year reduced their electricity bills by an average of 30 percent. A local installer argues that any Pinecrest homeowner who installs solar panels will save money.',
    questions: [
      Q('The installer’s argument is flawed because it',
        ['ignores the cost of buying and installing the panels', 'relies on data gathered from homes in a different town', 'assumes that electricity prices in Pinecrest will fall', 'confuses the average savings with the total savings', 'depends on the opinions of a few satisfied homeowners'],
        0,
        '“Save money” requires that bill reductions exceed the upfront cost. The argument considers only the reduction.',
        ['Right — costs are ignored.', 'The data are from Pinecrest.', 'No such assumption.', 'Not the main flaw.', 'The data are bill reductions, not opinions.']),
      Q('Which of the following, if true, would most weaken the installer’s claim that ANY homeowner will save?',
        ['The homes that installed panels last year mostly had large, south-facing roofs.', 'Electricity rates in Pinecrest are close to the average for the whole state.', 'Solar panels usually keep working for about twenty-five years after installation.', 'Some homeowners installed solar panels mainly for environmental reasons.', 'The installer offers homeowners financing to spread out the cost of the panels.'],
        0,
        'If early adopters had the best roofs, homes without them may save far less — “any homeowner” overgeneralizes.',
        ['Right — unrepresentative sample.', 'Irrelevant.', 'Supports long-term savings.', 'Irrelevant to savings.', 'Irrelevant.']),
    ],
  },
  {
    id: 'language-apps',
    difficulty: 1,
    text: 'People who use the language-learning app Lingo for at least a year are more likely to pass a proficiency exam than people who use it for less than a month. The company concludes that using Lingo for a year makes people proficient.',
    questions: [
      Q('Which of the following, if true, most weakens the company’s conclusion?',
        ['Year-long users tend to be motivated learners who also study in other ways.', 'Lingo offers lessons in twelve different languages, from Spanish to Japanese.', 'The proficiency exam is widely recognized by universities and employers alike.', 'Many people download Lingo but never open the app again after the first day.', 'Each of Lingo’s daily lessons takes only about ten minutes to complete.'],
        0,
        'Persistence and motivation could explain both long app use and exam success — the app may not be the cause.',
        ['Right — confounding factor.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant to the comparison.', 'Irrelevant.']),
      Q('The argument assumes that',
        ['the exam gap comes from using the app, not other differences between users', 'the proficiency exam is far too difficult for most learners to pass', 'people who stop using the app within a month learn nothing from it at all', 'all of the app’s users are studying the same language for the exam', 'the app is free for anyone who wants to keep using it for a whole year'],
        0,
        'The argument attributes the difference to the app itself.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not required.']),
    ],
  },
  {
    id: 'bakery-hours',
    difficulty: 1,
    text: 'Maple Street Bakery extended its closing time from 6 p.m. to 9 p.m., hoping to increase profits. But in the following month, profits fell, even though sales rose slightly.',
    questions: [
      Q('Which of the following, if true, most helps to explain how profits could fall even though sales rose?',
        ['The extra hours cost more in staff and lighting than the added sales brought in.', 'Most of the bakery’s customers still do their shopping in the morning hours.', 'A new café that sells pastries and coffee opened just down the street.', 'The bakery raised the prices of its bread at the same time it changed its hours.', 'Sales of the bakery’s cakes fell slightly during the month after the change.'],
        0,
        'Profit = revenue − cost. If the extra hours cost more than they brought in, profit falls even as sales rise.',
        ['Right.', 'Explains little about profit vs. sales.', 'Would reduce sales, but sales rose.', 'Would tend to raise revenue.', 'Overall sales still rose.']),
      Q('Which conclusion is most strongly supported by the information given?',
        ['The bakery’s costs rose more than its revenue did during that month.', 'The bakery will soon return to its old closing time of 6 p.m.', 'Most of the bakery’s customers prefer to shop before 6 p.m.', 'The profits of the bakery’s competitors rose during that month.', 'The bakery’s prices were set too low to cover its costs before.'],
        0,
        'If sales (revenue) rose but profit fell, costs must have risen by more than revenue did.',
        ['Right — must be true.', 'A prediction.', 'Not supported.', 'Not discussed.', 'Not supported.']),
    ],
  },
  {
    id: 'traffic-cameras',
    difficulty: 2,
    text: 'After Brookfield installed cameras at five intersections to catch drivers running red lights, collisions at those intersections fell by 25 percent. The mayor proposes installing cameras at all fifty of the city’s signalized intersections, predicting a similar drop in collisions citywide.',
    questions: [
      Q('Which of the following, if true, most weakens the mayor’s prediction?',
        ['Those five had been chosen for having the city’s worst collision rates the year before.', 'The cameras are expensive to maintain and need to be serviced several times a year.', 'Some drivers dislike the cameras and have complained about them to the city council.', 'The cameras also photograph vehicles that are speeding through the intersections.', 'Several neighboring cities are now considering installing cameras of their own.'],
        0,
        'Regression to the mean: intersections picked for unusually high collision rates would likely improve anyway, and other intersections may have less room to improve.',
        ['Right.', 'Cost doesn’t affect collisions.', 'Irrelevant.', 'Would tend to strengthen.', 'Irrelevant.']),
      Q('Which of the following would be most useful to know in evaluating the prediction?',
        ['How collisions changed over the same period at similar intersections without cameras', 'How many tickets the cameras have issued to drivers since they were first installed', 'Which company manufactured the cameras and how long they are expected to last', 'How many of the city’s residents own cars and drive them through the city', 'Whether the cameras are popular with voters in the upcoming city elections'],
        0,
        'A comparison group shows whether the drop was due to the cameras or to something that affected all intersections.',
        ['Right.', 'Tickets don’t measure collisions.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'organic-sales',
    difficulty: 2,
    text: 'Grocers in Eastfield report that sales of organic produce have tripled over the past decade. Since organic produce is generally more expensive than conventional produce, the increase shows that Eastfield residents have become wealthier over the decade.',
    questions: [
      Q('Which of the following, if true, most weakens the argument?',
        ['Over the decade, organic produce got much closer in price to conventional produce.', 'Eastfield grocers have also begun selling organic dairy products and eggs.', 'Some Eastfield residents grow their own vegetables in backyard gardens.', 'The population of Eastfield has remained about the same over the decade.', 'Organic produce is also sold at Eastfield’s weekly farmers’ market each summer.'],
        0,
        'If organic got relatively cheaper, residents could buy more without becoming wealthier.',
        ['Right — alternative explanation.', 'Irrelevant.', 'Irrelevant.', 'Would slightly strengthen by ruling out population growth.', 'Irrelevant.']),
      Q('Which of the following, if true, provides the best alternative explanation for the increase in sales?',
        ['Eastfield residents became more aware of organic farming’s environmental benefits.', 'Most of the grocers in Eastfield are independently owned, not part of chains.', 'Organic produce spoils faster than conventional produce once it is purchased.', 'Conventional produce is usually sold in larger packages than organic produce.', 'The decade included a recession in which many Eastfield residents lost jobs.'],
        0,
        'Changing preferences, not wealth, could explain higher organic sales.',
        ['Right.', 'Irrelevant.', 'Would, if anything, reduce sales.', 'Irrelevant.', 'A recession would work against the argument’s conclusion but doesn’t explain rising sales.']),
    ],
  },
  {
    id: 'standing-desks',
    difficulty: 2,
    text: 'A company gave standing desks to employees in its marketing department. Six months later, employees in that department reported fewer back problems than they had before. The company concludes that standing desks reduce back problems.',
    questions: [
      Q('Which of the following, if true, most weakens the conclusion?',
        ['Meanwhile, the company also began free weekly physical therapy for all staff.', 'Standing desks cost the company considerably more than ordinary desks do.', 'The marketing department is the largest department in the whole company.', 'Some employees in the marketing department rarely used their standing desks.', 'The company’s other departments did not receive standing desks at that time.'],
        0,
        'A simultaneous intervention (physical therapy) could explain the improvement.',
        ['Right — confounding change.', 'Irrelevant.', 'Irrelevant.', 'Weakens a little, but the therapy sessions are a more direct alternative cause.', 'This is the comparison that could help — not a weakener.']),
      Q('Which of the following would most help evaluate the conclusion?',
        ['Whether back problems also fell in departments that did not get standing desks', 'Which brand of standing desk the company bought for the marketing department', 'The average age of the employees who work in the marketing department', 'How many hours per day the company’s office building is open to employees', 'Whether the employees in the marketing department liked their new desks'],
        0,
        'A comparison group reveals whether the improvement was specific to the desks.',
        ['Right.', 'Irrelevant.', 'Only marginally relevant.', 'Irrelevant.', 'Irrelevant to back problems.']),
    ],
  },
  {
    id: 'library-closing',
    difficulty: 2,
    text: 'Council member: The Oakdale branch library should be closed. Its circulation — the number of books checked out — has fallen by half over five years, which proves that residents no longer need it.',
    questions: [
      Q('Which of the following, if true, most weakens the council member’s argument?',
        ['Meanwhile, use of the branch’s computers and study rooms has doubled.', 'The branch library building is more than fifty years old and needs repairs.', 'Circulation at the main library has also fallen over the same five years.', 'The branch is open fewer hours each week than the city’s main library is.', 'Oakdale’s population has grown slightly over the same five-year period.'],
        0,
        'The argument equates “need” with circulation. Rising use of other services shows residents still need the branch.',
        ['Right.', 'Irrelevant to need.', 'Doesn’t show residents need this branch.', 'Might explain lower circulation, but doesn’t show need as directly.', 'Slightly relevant, but weak.']),
      Q('The argument assumes that',
        ['book circulation is an adequate measure of residents’ need for the branch', 'the main library can absorb all of the branch’s patrons without crowding', 'the branch library is too expensive for the city to continue operating', 'books are the only resource that the branch library offers to residents', 'most residents now prefer to borrow e-books rather than printed books'],
        0,
        'It moves from falling circulation to “no longer need it.”',
        ['Right.', 'Not stated or required.', 'Not stated.', 'Similar, but stronger than required; the circulation assumption is the needed one.', 'Not required.']),
    ],
  },
  {
    id: 'honey-bees-pesticide',
    difficulty: 3,
    text: 'In regions where a certain pesticide is widely used, honeybee colonies have declined sharply. Yet in several regions where the pesticide has never been used, colonies have also declined.',
    questions: [
      Q('Which of the following, if true, most helps to reconcile the two observations with the hypothesis that the pesticide harms bees?',
        ['Bee declines have several causes, including a mite found in every region studied.', 'The pesticide is expensive, so farmers in poorer regions rarely use it at all.', 'Some of the regions studied use other pesticides instead of this particular one.', 'Beekeepers in all of the regions studied use similar kinds of hives and methods.', 'Honeybees often forage over several kilometers away from their own hives.'],
        0,
        'If another cause (mites) is present everywhere, colonies can decline without the pesticide — while the pesticide can still be an additional cause where it is used.',
        ['Right — multiple causes.', 'Irrelevant.', 'Possible but vaguer; doesn’t explain declines in untreated regions as clearly.', 'Irrelevant.', 'Could suggest drift, but the regions never used it.']),
      Q('Which of the following would provide the strongest evidence that the pesticide contributes to colony decline?',
        ['In each region, colonies near treated fields decline faster than distant ones.', 'The pesticide is applied to many different crops, including fruits and grains.', 'Honeybees visit many different kinds of flowers when they forage for nectar.', 'The pesticide’s manufacturer disputes the claim that its product harms bees.', 'Declines in honeybee colonies were first noticed by beekeepers in the 1990s.'],
        0,
        'Comparing nearby vs. distant colonies within a region controls for regional factors like mites and climate.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Not evidence either way.', 'Irrelevant.']),
    ],
  },
  {
    id: 'remote-work',
    difficulty: 2,
    text: 'Employees at Norsk Corp who work from home at least three days a week report higher job satisfaction than those who work in the office full-time. Norsk’s management plans to require all employees to work from home three days a week, expecting overall satisfaction to rise.',
    questions: [
      Q('Which of the following, if true, most weakens management’s expectation?',
        ['Remote workers chose to work from home, and many office workers prefer the office.', 'Norsk’s offices are located downtown, close to restaurants and public transit.', 'Remote employees at Norsk use video conferencing for most of their meetings.', 'Norsk has offices in three different countries, each with its own managers.', 'Some Norsk employees currently work from home only on Fridays, not three days.'],
        0,
        'Self-selection: current remote workers wanted to work from home. Forcing people who prefer the office may lower their satisfaction.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Management’s plan assumes that',
        ['the satisfaction gap comes from working at home, not from who chose to do it', 'employees will get more work done at home than they do in the office', 'office space downtown is expensive for the company to rent and maintain', 'every employee has a reliable internet connection at home to work with', 'job satisfaction can be measured precisely enough to detect a change'],
        0,
        'The plan assumes that working from home causes satisfaction for anyone who does it.',
        ['Right.', 'Productivity is not the goal stated.', 'Not stated.', 'Plausibly needed in practice, but not the core logical assumption about satisfaction.', 'Not required.']),
    ],
  },
  {
    id: 'ancient-grain',
    difficulty: 3,
    text: 'Archaeologists found large quantities of charred barley in a Bronze Age settlement but almost no wheat. They concluded that the settlement’s inhabitants ate far more barley than wheat.',
    questions: [
      Q('Which of the following, if true, most weakens the archaeologists’ conclusion?',
        ['Unlike wheat, barley was parched over fire before storage, so it charred more often.', 'Barley grows well even in the poor, rocky soil that surrounded the settlement.', 'Other Bronze Age settlements in the same region also grew large amounts of barley.', 'The settlement was built beside a river that flooded the nearby fields every spring.', 'Charred grain can be dated precisely using standard radiocarbon methods.'],
        0,
        'Preservation bias: if barley was much more likely to be charred (and thus preserved), the record overstates barley relative to wheat.',
        ['Right — preservation bias.', 'Irrelevant to consumption.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('The archaeologists’ reasoning assumes that',
        ['the amounts of charred grain that survived reflect the amounts that were eaten', 'wheat had not yet been domesticated anywhere during the Bronze Age', 'the settlement imported most of its barley from neighboring regions', 'the settlement was abandoned suddenly, leaving its grain stores behind', 'charred grains of barley and wheat are easy to tell apart from each other'],
        0,
        'They infer consumption from what survived.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not the key assumption.']),
    ],
  },
  {
    id: 'app-downloads',
    difficulty: 1,
    text: 'The fitness app StepUp was downloaded twice as many times this year as last year. Its developers conclude that twice as many people are exercising with StepUp this year.',
    questions: [
      Q('Which of the following, if true, most weakens the developers’ conclusion?',
        ['Most people who download StepUp stop using it within a week.', 'StepUp is available on both of the major kinds of smartphones.', 'Downloads of StepUp’s main competitors also grew this year.', 'StepUp added a popular nutrition-tracking feature this year.', 'StepUp’s price this year stayed the same as it was last year.'],
        0,
        'Downloads ≠ people exercising. If most downloaders quit quickly, doubling downloads doesn’t mean doubling active users.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Might explain downloads but doesn’t weaken.', 'Irrelevant.']),
      Q('The developers’ argument depends on the assumption that',
        ['the share of downloaders who actually exercise with the app did not fall', 'StepUp is the single most popular fitness app on the market this year', 'people who exercise regularly tend to download several fitness apps', 'everyone who used the app last year has since stopped using it', 'the app can be downloaded free of charge by anyone with a phone'],
        0,
        'To go from “twice the downloads” to “twice the exercisers,” the share of downloaders who exercise must not have dropped.',
        ['Right.', 'Not required.', 'Not required.', 'Not required, and would actually complicate the count.', 'Not required.']),
    ],
  },
  {
    id: 'cheaper-flights',
    difficulty: 3,
    text: 'Airline X cut its fares on the Denver–Boston route by 20 percent, and the number of passengers it carried on that route rose by 50 percent. Airline X’s executives conclude that cutting fares on all its routes would increase its total revenue.',
    questions: [
      Q('Which of the following, if true, most weakens the executives’ conclusion?',
        ['Rivals didn’t match this cut, so riders switched; on most routes, rivals match cuts.', 'The Denver–Boston route is one of the longest routes that Airline X flies.', 'Fuel prices rose sharply during the months when the lower fares were in effect.', 'Airline X flies to thirty cities and plans to add several more routes next year.', 'Some Denver–Boston passengers paid extra fees to check additional pieces of luggage.'],
        0,
        'The gain came from stealing competitors’ passengers who didn’t match. Where competitors match, a fare cut won’t attract many new passengers, and revenue may fall.',
        ['Right.', 'Irrelevant.', 'Affects costs, not revenue.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following can be properly concluded from the information about the Denver–Boston route?',
        ['Airline X’s revenue on that route increased after the fare cut.', 'Airline X’s profit on that route increased after the fare cut.', 'Competing airlines lost money on the Denver–Boston route that year.', 'Cutting fares on any route always increases an airline’s revenue.', 'Passengers on that route prefer Airline X to its competitors.'],
        0,
        '0.8 × price × 1.5 × passengers = 1.2 × the old revenue → revenue rose 20% on that route (assuming the 20% cut applied to all its fares there).',
        ['Right — 0.8 × 1.5 = 1.2.', 'Costs are unknown.', 'Not established.', 'Overgeneralization.', 'Not established.']),
    ],
  },
  {
    id: 'mayor-poll',
    difficulty: 1,
    text: 'An online poll on a political blog found that 80 percent of respondents disapprove of the mayor. The blog’s author concludes that the mayor is unpopular with most of the city’s residents.',
    questions: [
      Q('The author’s reasoning is most vulnerable to the objection that',
        ['the respondents may not be representative of the city’s residents', 'the poll asked respondents too many questions about city issues', 'the mayor was elected only recently and has had little time in office', 'online polls are illegal for political blogs in most jurisdictions', '80 percent of the respondents does not amount to a majority of them'],
        0,
        'Readers of a political blog who choose to respond are a self-selected, likely unrepresentative sample.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Absurd.', '80% is a majority.']),
      Q('Which of the following, if true, most weakens the conclusion?',
        ['The blog mainly criticizes the mayor and is read chiefly by the mayor’s opponents.', 'The poll stayed open on the blog for a full week before the results were posted.', 'The blog has many thousands of regular readers from all over the region.', 'The mayor is currently serving a second term after winning reelection.', 'Some of the poll’s respondents also left comments explaining their views.'],
        0,
        'A readership of opponents would produce high disapproval regardless of citywide opinion.',
        ['Right.', 'Irrelevant.', 'Size doesn’t fix bias.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'wolf-reintro',
    difficulty: 3,
    text: 'After wolves were reintroduced to a national park, the number of elk declined and willow trees along the park’s streams, which elk browse, began to recover. Some ecologists concluded that wolves caused the willow recovery by reducing elk numbers.',
    questions: [
      Q('Which of the following, if true, would most strengthen the ecologists’ conclusion?',
        ['Where wolves rarely hunt, willows haven’t recovered, though elk declined there too.', 'Willows grow best in wet soil near streams, where their roots can reach water.', 'Elk are the main prey of the reintroduced wolves, both in the park and beyond it.', 'The park attracts many thousands of tourists who come hoping to see the wolves.', 'Beavers living along the park’s streams also eat the bark of willow trees.'],
        0,
        'Where wolves are absent, willows didn’t recover — linking recovery to wolves specifically (perhaps by changing elk behavior as well as numbers).',
        ['Right — links recovery to wolf presence.', 'Background.', 'Background; doesn’t link to willows.', 'Irrelevant.', 'Introduces another factor, not a strengthener.']),
      Q('Which of the following, if true, would most weaken the ecologists’ conclusion?',
        ['A run of unusually wet years, which favor willow growth, coincided with the recovery.', 'The reintroduced wolves also prey on deer and other animals in the park.', 'Most of the park’s elk migrate out of the park during the winter months.', 'Willow trees are common throughout the region, both inside and outside the park.', 'The reintroduced wolves were brought to the park from forests in another country.'],
        0,
        'An alternative cause: wet years could explain willow recovery.',
        ['Right.', 'Irrelevant.', 'Irrelevant to the causal claim.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'textbook-price',
    difficulty: 2,
    text: 'A university began offering free online textbooks for its introductory courses. In the first year, the average grade in those courses rose. The provost concludes that cost had been preventing some students from obtaining textbooks, which lowered their grades.',
    questions: [
      Q('Which of the following, if true, most strengthens the provost’s conclusion?',
        ['Gains were largest among aided students, many of whom had gone without textbooks.', 'The online textbooks are much shorter than the printed ones they replaced.', 'The introductory courses are large lectures with hundreds of students each.', 'Most faculty members said they liked the online textbooks better than print.', 'The university raised its tuition by a small amount in that same year.'],
        0,
        'If gains were largest among students who had lacked textbooks for cost reasons, the explanation fits.',
        ['Right.', 'Might suggest another cause, if anything.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following, if true, most weakens the conclusion?',
        ['That same year, the university began letting students retake their exams.', 'Some students printed out the online textbooks so they could read them on paper.', 'The online textbooks were written by the instructors who teach the courses.', 'Students can read the online textbooks on their phones as well as computers.', 'Enrollment in the introductory courses rose during the same year.'],
        0,
        'A new retake policy is an alternative explanation for higher grades.',
        ['Right.', 'Irrelevant.', 'Could matter, but less directly than the new retake policy.', 'Irrelevant.', 'Irrelevant to average grades.']),
    ],
  },
  {
    id: 'noise-plants',
    difficulty: 2,
    text: 'An office manager placed large potted plants throughout an open-plan office. Afterward, employees’ complaints about noise dropped by half. The manager concluded that the plants absorbed enough sound to make the office quieter.',
    questions: [
      Q('Which of the following, if true, most weakens the manager’s conclusion?',
        ['Noise measurements taken before and after the plants arrived showed no change.', 'The plants needed frequent watering, which the office manager did each morning.', 'Employees said the plants made the office a more pleasant place to work.', 'Some of the larger plants were placed near the office’s windows for light.', 'The open-plan office is shared by about forty employees in four teams.'],
        0,
        'If measured noise didn’t change, the plants didn’t make the office quieter; complaints fell for another reason.',
        ['Right.', 'Irrelevant.', 'Suggests a different reason complaints dropped — actually weakens too, but less decisively than a direct measurement.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following offers the best alternative explanation for the drop in complaints?',
        ['The plants made employees more comfortable, so the same noise bothered them less.', 'The plants release oxygen, which can make people feel more alert at work.', 'The plants were expensive, and the manager had to justify buying them.', 'Noise complaints are very common in open-plan offices of every size and type.', 'Some of the employees wear headphones at their desks for much of the workday.'],
        0,
        'Complaints reflect how bothered people are, not only noise level; a more pleasant space could reduce annoyance.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Would have been true before too — doesn’t explain a change.']),
    ],
  },
  {
    id: 'bridge-traffic',
    difficulty: 3,
    text: 'To reduce congestion, the city built a second bridge across the river. A year later, traffic on the original bridge was just as heavy as before, and the total number of vehicles crossing the river had increased substantially.',
    questions: [
      Q('Which of the following, if true, best explains these results?',
        ['The new bridge made crossing easier, so people made trips they used to avoid.', 'The new bridge is narrower than the original bridge and carries fewer lanes.', 'Construction of the new bridge took three years and was delayed twice.', 'The tolls on the two bridges are the same for every type of vehicle.', 'The original bridge was recently repainted and had its lighting replaced.'],
        0,
        'Induced demand: added capacity makes driving across easier, generating new trips that fill the old bridge again.',
        ['Right.', 'Doesn’t explain the increase in total crossings.', 'Irrelevant.', 'Doesn’t explain.', 'Irrelevant.']),
      Q('The results most strongly support which conclusion?',
        ['Adding road capacity does not necessarily reduce congestion on existing roads.', 'The second bridge should be closed, since it failed to reduce congestion.', 'Tolls on bridges always reduce the amount of traffic that crosses them.', 'Most drivers prefer to use the original bridge rather than the new one.', 'Public transit ridership across the river fell after the new bridge opened.'],
        0,
        'Traffic on the original bridge didn’t fall even with a new bridge.',
        ['Right.', 'Not supported.', 'Tolls aren’t discussed.', 'Not supported.', 'Not discussed.']),
    ],
  },
  {
    id: 'chess-math',
    difficulty: 2,
    text: 'Children who belong to school chess clubs tend to score higher on math tests than children who do not. An education advocate argues that schools should add chess to the curriculum in order to improve math achievement.',
    questions: [
      Q('Which of the following, if true, most seriously undermines the advocate’s argument?',
        ['Children who are already strong in math are more likely to be drawn to chess clubs.', 'Chess sets are inexpensive, so nearly any school could afford to buy enough of them.', 'Most school chess clubs meet after school rather than during class time.', 'Some members of chess clubs also enjoy playing checkers and other games.', 'Chess has been played for centuries in many different parts of the world.'],
        0,
        'Reverse causation / self-selection: math ability may lead to chess, not the other way around.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following findings would most support the advocate’s proposal?',
        ['Students assigned at random to chess improved more in math than a comparison group.', 'Many parents say they enjoy playing chess with their children at home on weekends.', 'Professional chess players are well paid, especially those who win major events.', 'Chess clubs for children are popular in several countries around the world.', 'Most school chess tournaments are held on weekends rather than school days.'],
        0,
        'Random assignment removes self-selection and tests whether chess causes math gains.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'hospital-deaths',
    difficulty: 3,
    text: 'Mercy Hospital has a higher death rate among its patients than nearby Valley Hospital. A health reporter concludes that patients receive worse care at Mercy than at Valley.',
    questions: [
      Q('Which of the following, if true, most seriously weakens the reporter’s conclusion?',
        ['Mercy is the region’s trauma center and receives the most critically ill patients.', 'Mercy is a larger hospital than Valley and admits many more patients every year.', 'Valley Hospital opened more recently than Mercy and is in a newer building.', 'Both hospitals employ highly skilled surgeons who trained at top schools.', 'Mercy’s parking lot is much smaller and is often full during visiting hours.'],
        0,
        'Different patient mix: a hospital taking the sickest patients will have a higher death rate even with excellent care.',
        ['Right.', 'Size alone doesn’t explain a rate.', 'Irrelevant.', 'Doesn’t address the comparison.', 'Irrelevant.']),
      Q('Which comparison would provide the best evidence about quality of care?',
        ['Death rates for patients with similar conditions and severity at the two hospitals', 'The number of doctors and nurses working at each hospital on a typical weekday', 'Patient satisfaction surveys collected by each hospital after discharge', 'Each hospital’s annual budget and how much of it is spent on equipment', 'The age of each hospital’s main buildings and when they were last renovated'],
        0,
        'Comparing like with like controls for patient mix.',
        ['Right.', 'Irrelevant.', 'Measures satisfaction, not outcomes.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'sunscreen',
    difficulty: 2,
    text: 'A survey found that people who regularly use sunscreen are more likely to have been diagnosed with skin cancer than people who do not. The survey’s authors caution against concluding that sunscreen causes skin cancer.',
    questions: [
      Q('Which of the following, if true, best supports the authors’ caution?',
        ['Fair-skinned people, at higher risk of skin cancer, also use sunscreen more often.', 'Sunscreen is sold in many different strengths, from SPF 15 all the way to SPF 100.', 'Skin cancer is more common among people living in sunny climates than in cloudy ones.', 'Some sunscreens are waterproof and stay on through an hour of swimming.', 'Most people apply too little sunscreen to get the protection on the label.'],
        0,
        'A common cause (fair skin) explains both higher sunscreen use and higher cancer risk.',
        ['Right.', 'Irrelevant.', 'Relevant background, but doesn’t link sunscreen use and risk.', 'Irrelevant.', 'Might weaken sunscreen’s protection, but doesn’t explain the correlation.']),
      Q('The situation described is most similar to which of the following?',
        ['Towns with more firefighters have more fires, but firefighters do not cause fires.', 'Students who study more get better grades, because studying helps them learn more.', 'A new drug reduced symptoms more than a placebo did in a randomized trial.', 'Prices in a state rose shortly after the state raised its sales tax rate.', 'A car’s speed determines how long it takes to travel a given distance.'],
        0,
        'Both involve a correlation that doesn’t reflect a causal effect of the first factor on the second.',
        ['Right.', 'A plausible causal claim.', 'A controlled result.', 'A plausible causal claim.', 'A definitional relationship.']),
    ],
  },
  {
    id: 'price-match',
    difficulty: 2,
    text: 'Electronics retailer Voltra introduced a policy of matching any competitor’s lower price. Afterward, its sales rose, but so did the number of customers who returned items within a week.',
    questions: [
      Q('Which of the following, if true, best explains the increase in returns?',
        ['Some buyers found lower prices elsewhere and returned items instead of asking for a match.', 'Voltra sells mostly televisions and other large home-entertainment products.', 'Voltra extended its store hours on weekends at about the same time as the policy began.', 'Voltra’s competitors did not introduce any price-matching policies of their own.', 'Voltra’s return policy, which allows returns within thirty days, has not changed.'],
        0,
        'Price-matching encouraged comparison shopping; some who found a better deal returned items instead of claiming a match.',
        ['Right.', 'Irrelevant.', 'Irrelevant to returns.', 'Doesn’t explain returns.', 'Doesn’t explain the increase.']),
      Q('Which of the following would be most useful for Voltra to know in evaluating whether the policy has been profitable?',
        ['Whether the extra sales earned more than the matched prices and returns cost', 'Whether Voltra’s competitors advertise their prices on television and online', 'How many employees work at each of Voltra’s stores during busy periods', 'Whether customers liked the new layout that Voltra introduced in its stores', 'The number of different product brands that Voltra carries in its stores'],
        0,
        'Profitability depends on the extra profit versus the extra costs the policy created.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'volunteers-health',
    difficulty: 2,
    text: 'A long-term study found that older adults who volunteer regularly live longer, on average, than those who do not. A columnist concludes that volunteering improves health.',
    questions: [
      Q('Which of the following, if true, most weakens the columnist’s conclusion?',
        ['People in poor health are less able to volunteer.', 'Volunteering is common among older adults in many countries.', 'Some of the volunteers in the study work with young children.', 'The study followed its participants for twenty years.', 'Many of the volunteers in the study were retired.'],
        0,
        'Poor health prevents volunteering — so volunteers may live longer because they were healthier to begin with (reverse causation).',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following, if true, would most strengthen the conclusion?',
        ['The advantage held even against non-volunteers who began equally healthy.', 'Volunteers in the study often said that volunteering made them feel useful.', 'Many volunteer organizations say they need more help than they can find.', 'Retired adults generally have more free time to volunteer than workers do.', 'Some of the people in the study had been volunteering for several decades.'],
        0,
        'Controlling for baseline health rules out the reverse-causation explanation.',
        ['Right.', 'Plausible mechanism but weaker evidence.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
    ],
  },
  {
    id: 'recycling-bins',
    difficulty: 1,
    text: 'After the town of Kessler gave every household a free recycling bin, the amount of material recycled in the town doubled. A neighboring town, Linden, plans to do the same and expects its recycling to double as well.',
    questions: [
      Q('Which of the following, if true, most weakens Linden’s expectation?',
        ['Most Linden households already have recycling bins.', 'Kessler is larger than Linden and has more households.', 'The free recycling bins are made of durable plastic.', 'Linden’s town council strongly supports recycling.', 'Kessler’s recycling bins are collected once a week.'],
        0,
        'If Linden households already have bins, giving free bins won’t change behavior the way it did in Kessler.',
        ['Right.', 'Size is irrelevant to doubling.', 'Irrelevant.', 'Irrelevant.', 'Doesn’t address Linden.']),
      Q('Linden’s expectation depends on the assumption that',
        ['conditions in Linden are relevantly like those in Kessler before the bins', 'recycling is profitable for both towns once enough material is collected', 'Kessler’s residents are wealthier on average than Linden’s residents are', 'Linden’s bins will be the same size and color as the ones in Kessler', 'the recycled material collected in both towns can be sold to factories'],
        0,
        'Reasoning by analogy requires relevant similarity.',
        ['Right.', 'Not required.', 'Not required.', 'Irrelevant.', 'Not required.']),
    ],
  },
  {
    id: 'phone-ban',
    difficulty: 2,
    text: 'After Ridgeway High banned phones during class, the average test score rose by 6 points. The principal argues that phones had been distracting students and lowering their performance.',
    questions: [
      Q('Which of the following, if true, would most strengthen the principal’s argument?',
        ['At a similar school without a phone ban, scores were unchanged over that period.', 'Most students at Ridgeway High own phones and bring them to school daily.', 'Some teachers at Ridgeway used their own phones in class before the ban.', 'The ban on phones in class was popular with most of the students’ parents.', 'Students at Ridgeway are still allowed to use their phones at lunch.'],
        0,
        'A comparison school without the ban rules out a general trend as the cause.',
        ['Right.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.', 'Irrelevant.']),
      Q('Which of the following, if true, would most weaken it?',
        ['The state replaced its standardized test with an easier version that year.', 'The ban was enforced strictly by every teacher at the school from its first day.', 'Many students complained to the principal that the ban was unfair and too strict.', 'Phones can also be used by students for research and for studying at home.', 'The school opened a new library with longer hours at the start of that year.'],
        0,
        'An easier test is an alternative explanation for higher scores.',
        ['Right.', 'Supports.', 'Irrelevant.', 'Irrelevant.', 'A minor alternative.']),
    ],
  },
  {
    id: 'coffee-shop',
    difficulty: 2,
    text: 'Owner: Our café should stop offering free Wi-Fi. Customers who use it stay for hours while buying only a single coffee, occupying tables that other customers could use.',
    questions: [
      Q('Which of the following, if true, most weakens the owner’s argument?',
        ['The café’s tables are rarely all occupied, even at its busiest times.', 'Providing the Wi-Fi costs the café very little compared with its other costs.', 'Some customers bring their own mobile hotspots and don’t use the café’s Wi-Fi.', 'Several other cafés nearby also offer their customers free Wi-Fi.', 'The price of a cup of coffee at the café has risen twice over the past year.'],
        0,
        'The argument assumes Wi-Fi users crowd out other customers. If tables are rarely full, no one is being turned away.',
        ['Right.', 'Irrelevant to the crowding argument.', 'Irrelevant.', 'Suggests a competitive risk, but doesn’t attack the reasoning as directly.', 'Irrelevant.']),
      Q('The owner’s argument assumes that',
        ['the customers who would use the freed tables would spend more than Wi-Fi users', 'every one of the café’s customers uses the free Wi-Fi when they visit', 'coffee is the only product that the café sells to the people who visit', 'the Wi-Fi service is expensive for the café to keep providing every month', 'most customers prefer a quiet café to one full of people working on laptops'],
        0,
        'Removing Wi-Fi only helps if replacement customers would bring in more.',
        ['Right.', 'Not required.', 'Not required.', 'Not required.', 'Not required.']),
    ],
  },
];

const letters = 'ABCDE';

/**
 * Choices are authored with the right answer first. Deal them into a fixed
 * order per question, with the right answer moved to the slot this question
 * is assigned, so across the set every letter is right equally often and the
 * position gives nothing away.
 */
function deal(key: string, options: string[], notes: string[], answer: number, slot: number) {
  const order = shuffle(mulberry32(hashStr(`deal:${key}`)), options.map((_, j) => j));
  const t = slot % options.length;
  const at = order.indexOf(answer);
  [order[t], order[at]] = [order[at], order[t]];
  return { options: order.map((j) => options[j]), notes: order.map((j) => notes[j]), answer: t };
}

function build(a: Arg, n: number): Candidate[] {
  return a.questions.map((q, i) => {
    const d = deal(`${a.id}:${i}`, q.options, q.notes, q.answer, n * 2 + i);
    return {
      key: `${a.id}:${i}`,
      group: `arg:${a.id}`,
      q: {
        kind: 'mcq' as const,
        prompt: q.prompt,
        options: d.options,
        correctIndex: d.answer,
        explanation: `${q.why} (Answer: ${letters[d.answer]}.)`,
        distractorNotes: d.notes.map((note, j) => (j === d.answer ? `✓ ${note}` : note)),
        difficulty: a.difficulty,
        stimulus: { passage: a.text },
      },
    };
  });
}

const crArguments: Generator = {
  id: 'cr-arguments',
  track: 'verbal',
  topic: 'Argument questions (critical reasoning)',
  lessonId: 'gre-rc-arguments',
  count: ARGUMENTS.reduce((n, a) => n + a.questions.length, 0),
  all: () => [...ARGUMENTS].sort((x, y) => x.difficulty - y.difficulty).flatMap((a, n) => build(a, n)),
};

export const ARGUMENT_GENERATORS: Generator[] = [crArguments];
