// Authored two- and three-blank text completions. Each blank names the
// vocabulary cluster its answer comes from and the cluster its trap comes
// from (usually the opposite — the choice you'd pick if you misread the
// sentence's logic). The generator fills each blank's three choices: one
// word from the answer cluster, one from the trap cluster, one unrelated.
//
// Grammar rule: every word in a blank's answer AND trap clusters must fit
// the slot (verbs appear in base form after "to", "did not", "would", …;
// adjectives after "was"/before nouns; "a (i)___" is shown as "a(n)").
//
// `why` walks through the logic the way you should on test day: find the
// clue and the signal words, fill the easiest blank first.

export interface MultiTemplate {
  text: string;
  blanks: [answer: string, trap: string][];
  why: string;
}

const M = (text: string, blanks: [string, string][], why: string): MultiTemplate => ({ text, blanks, why });

export const MULTI_BLANK: MultiTemplate[] = [
  // ------------------------------------------------------------ two blanks
  M('Although the senator was usually (i)___, answering reporters in single syllables, at the rally she was positively (ii)___, speaking for nearly two hours.',
    [['taciturn', 'talkative'], ['talkative', 'taciturn']],
    '“Single syllables” defines (i): she normally says little. “Although … at the rally” flips it, and “speaking for nearly two hours” defines (ii): talkative.'),
  M('The critic’s review was far from (i)___; in fact, it was so (ii)___ that the director publicly demanded an apology.',
    [['beneficial', 'harmful'], ['malicious', 'kind']],
    '“Far from X; in fact, so Y that the director demanded an apology” — (ii) must be hurtful and ill-intended, and (i) its opposite: something that does good.'),
  M('Scientists had expected the new coating to be (i)___, but tests showed it was remarkably (ii)___, surviving decades of simulated wear.',
    [['fleeting', 'lasting'], ['lasting', 'fleeting']],
    '“Surviving decades” defines (ii) as long-lasting. “Expected … but” signals a reversal, so (i) is the opposite: short-lived.'),
  M('Far from being (i)___ with money, the philanthropist was so (ii)___ that she gave away nearly her entire fortune.',
    [['stingy', 'generous'], ['generous', 'stingy']],
    '“Gave away nearly her entire fortune” defines (ii): generous. “Far from” makes (i) the opposite: stingy.'),
  M('The professor’s lectures, once praised as (i)___, had become so (ii)___ that even devoted students struggled to follow them.',
    [['clear', 'obscure'], ['obscure', 'clear']],
    '“Struggled to follow” defines (ii): hard to understand. “Once praised … had become” marks a change, so (i) is the opposite: clear.'),
  M('The negotiator’s (i)___ opening remarks, which offered several concessions, did little to (ii)___ the union leaders, who walked out within the hour.',
    [['conciliatory', 'hostile'], ['placate', 'provoke']],
    '“Offered several concessions” defines (i): peace-making. “Did little to … who walked out” says the attempt failed to calm them, so (ii) means placate.'),
  M('Because the evidence was so (i)___, the jury reached a verdict in minutes; in the earlier trial, by contrast, the testimony had been (ii)___, and the deliberations dragged on for days.',
    [['explicit', 'ambiguous'], ['ambiguous', 'explicit']],
    'A quick verdict needs unmistakable evidence — (i). “By contrast … dragged on” needs the opposite for (ii): unclear, open to interpretation.'),
  M('Critics who had dismissed the painter as merely (i)___ were forced to reconsider when her later work proved strikingly (ii)___.',
    [['unoriginal', 'original'], ['original', 'unoriginal']],
    '“Forced to reconsider” means the critics’ label was wrong; the later work showed the opposite. (i) = unoriginal, (ii) = original.'),
  M('The mayor’s response to the flood was criticized as (i)___: a brief tour of the damage and a two-sentence statement, when residents had hoped for (ii)___ attention to their needs.',
    [['perfunctory', 'careful'], ['careful', 'perfunctory']],
    '“A brief tour and a two-sentence statement” is minimal effort — (i). What residents hoped for is the contrast: careful, thorough attention — (ii).'),
  M('Although the entrepreneur was (i)___ in private, spending almost nothing on herself, she was (ii)___ in her public gifts, funding hospitals and schools across the region.',
    [['thrifty', 'extravagant'], ['generous', 'stingy']],
    '“Spending almost nothing on herself” defines (i): thrifty. “Although” contrasts it with her giving: “funding hospitals and schools” = generous (ii).'),
  M('The biography is (i)___ in its praise, treating every one of its subject’s decisions as wise; readers hoping for a (ii)___ assessment will be disappointed.',
    [['flattering', 'arrogant'], ['impartial', 'biased']],
    'Praising “every one” of the decisions is fawning — (i). The disappointed readers wanted the opposite of fawning: a fair, balanced assessment — (ii).'),
  M('The river, normally (i)___ in late summer, became (ii)___ after the storm, sweeping away two bridges.',
    [['peaceful', 'turbulent'], ['turbulent', 'peaceful']],
    '“Sweeping away two bridges” defines (ii): violent and disorderly. “Normally … became” marks a change, so (i) is calm.'),
  M('Her reputation as a (i)___ manager, one who checked every figure twice, made the (ii)___ errors in the final report all the more surprising.',
    [['careful', 'sloppy'], ['sloppy', 'careful']],
    '“Checked every figure twice” defines (i): meticulous. “All the more surprising” means the errors clash with that reputation, so (ii) is careless.'),
  M('What began as a (i)___ disagreement over a parking space escalated into a (ii)___ feud that lasted for decades.',
    [['trivial', 'crucial'], ['vindictive', 'forgiving']],
    '“Began as … escalated” — the start was small and unimportant (i). A feud lasting decades is driven by revenge and resentment (ii).'),
  M('At first the scientific establishment was quick to (i)___ the theory, but a series of confirming experiments eventually led many former critics to (ii)___ it.',
    [['criticize', 'praise'], ['praise', 'criticize']],
    '“At first … but … former critics” signals a reversal: first attacked (i), later applauded (ii).'),
  M('Rather than (i)___ the crisis, the minister’s blunt remarks served only to (ii)___ it, prompting a second night of protests.',
    [['alleviate', 'worsen'], ['worsen', 'alleviate']],
    '“Prompting a second night of protests” shows things got worse — (ii). “Rather than” makes (i) what he failed to do: ease the crisis.'),
  M('The novelist is famously (i)___ about her private life, and her new memoir, which reveals remarkably little, will do nothing to (ii)___ her readers’ curiosity.',
    [['taciturn', 'talkative'], ['soothe', 'worsen']],
    '“Reveals remarkably little” confirms (i): reserved. A memoir that tells nothing will not satisfy — ease or quiet — readers’ curiosity (ii).'),
  M('Although the committee’s proposal seemed (i)___ at first, closer inspection revealed a (ii)___ web of exceptions and conditions.',
    [['simple', 'complicated'], ['complicated', 'simple']],
    '“Web of exceptions and conditions” defines (ii): convoluted. “Although … seemed … at first” makes (i) the opposite: simple.'),
  M('The young violinist’s (i)___ was evident in her flawless technique, but critics noted a (ii)___ of feeling in her playing, which struck them as cold.',
    [['skill-n', 'ineptitude-n'], ['dearth-n', 'excess-n']],
    '“Flawless technique” shows skill (i). “But … struck them as cold” means feeling was lacking — a shortage (ii).'),
  M('Investors were (i)___ about the start-up’s prospects, having seen dozens of similar companies fail; its founders, however, remained (ii)___.',
    [['skeptical', 'gullible'], ['optimistic', 'pessimistic']],
    'Having watched dozens fail, investors doubted — (i). “However” sets the founders against them: hopeful (ii).'),
  M('The general was (i)___ in battle, but in peacetime his (ii)___ decisions, made without consulting anyone, alienated his advisers.',
    [['bold', 'cowardly'], ['reckless', 'cautious']],
    'Praise-worthy in battle = courageous (i). “But … made without consulting anyone” turns that daring into rashness in peacetime (ii).'),
  M('To the tourists, the island’s customs seemed (i)___, but to the islanders themselves they were entirely (ii)___, the stuff of everyday life.',
    [['eccentric', 'conventional'], ['ordinary', 'anomalous']],
    '“The stuff of everyday life” defines (ii): ordinary. “But” contrasts the tourists’ view: odd, unconventional (i).'),
  M('The CEO’s (i)___ promises to employees stood in stark contrast to the (ii)___ layoffs announced a week later.',
    [['kind', 'malicious'], ['unfeeling', 'kind']],
    '“Stark contrast” sets warm, caring promises (i) against layoffs carried out callously (ii).'),
  M('Although the report was (i)___, running to nearly four hundred pages, its central finding could be stated in a single (ii)___ sentence.',
    [['wordy', 'brief'], ['brief', 'wordy']],
    '“Nearly four hundred pages” = long-winded (i). “Although … a single sentence” sets up the contrast: concise (ii).'),
  M('Unlike her (i)___ predecessor, who approved every request without question, the new director was notably (ii)___, rejecting nearly half the proposals she received.',
    [['lenient', 'harsh'], ['rigorous', 'lenient']],
    '“Approved every request” = lenient (i). “Unlike” sets up the opposite; “rejecting nearly half” = strict and demanding (ii).'),
  M('The detective found the suspect’s account (i)___: every detail matched the security footage, and several witnesses came forward to (ii)___ it.',
    [['explicit', 'ambiguous'], ['confirm', 'disprove']],
    'Every detail matching the footage makes the account clear and unmistakable (i). Witnesses who back it up confirm it (ii).'),
  M('The candidate’s speech was so (i)___ that listeners could not tell where he stood on any issue, a strategy his rivals derided as (ii)___.',
    [['ambiguous', 'explicit'], ['cowardly', 'bold']],
    '“Could not tell where he stood” = equivocal (i). Rivals would mock deliberate vagueness as a lack of nerve (ii).'),
  M('The species, once (i)___ across the continent, has become so (ii)___ that biologists fear it will vanish within a decade.',
    [['ubiquitous', 'scarce'], ['scarce', 'abundant']],
    '“Fear it will vanish” = now rare (ii). “Once … has become” signals change, so (i) = found everywhere.'),
  M('Though the author’s prose is (i)___, full of elaborate metaphors and digressions, the plot itself is refreshingly (ii)___.',
    [['ornate', 'austere'], ['simple', 'complicated']],
    '“Elaborate metaphors and digressions” = ornate (i). “Though … refreshingly” contrasts it: the plot is straightforward (ii).'),
  M('Colleagues found the scientist (i)___ and hard to approach, yet her students described her as unfailingly (ii)___.',
    [['aloof', 'friendly'], ['friendly', 'aloof']],
    '“Hard to approach” = distant (i). “Yet” reverses it for students: warm and friendly (ii).'),
  M('Civil-liberties groups rushed to (i)___ the ruling, calling it a victory for free speech, while prosecutors were quick to (ii)___ it, warning that it would make convictions harder to obtain.',
    [['praise', 'criticize'], ['criticize', 'praise']],
    'Calling it a “victory” = praising it (i); warning of harm = attacking it (ii). “While” sets the two reactions against each other.'),
  M('The new regulations did not (i)___ the company’s growth, as critics had predicted; instead they helped to (ii)___ it by simplifying the approval process.',
    [['hinder', 'facilitate'], ['facilitate', 'hinder']],
    '“Simplifying the approval process” = made growth easier (ii). “Did not … as critics had predicted; instead” makes (i) the feared opposite: hinder.'),
  M('The explorer’s journals, (i)___ in their detail, record the temperature, wind, and position every hour; yet they are strangely (ii)___ about her own feelings, which she almost never mentions.',
    [['careful', 'sloppy'], ['taciturn', 'talkative']],
    'Hourly records of temperature, wind, and position = meticulous (i). “Yet … almost never mentions” her feelings = reticent (ii).'),
  M('The prime minister’s support among voters proved (i)___: popular in the spring, he was reviled by the autumn, a reversal that surprised only those who had mistaken early enthusiasm for (ii)___ loyalty.',
    [['fickle', 'steadfast'], ['steadfast', 'fickle']],
    'Popular in spring, reviled by autumn = changeable (i). The mistake was thinking the enthusiasm was firm, lasting loyalty (ii).'),
  M('The museum’s new wing, with its bare concrete walls and (i)___ galleries, is a deliberate rejection of the (ii)___ style of the original building, with its gilded ceilings and marble statues.',
    [['austere', 'ornate'], ['ornate', 'austere']],
    '“Gilded ceilings and marble statues” = ornate (ii). “Bare concrete walls” and “deliberate rejection” = severely plain (i).'),
  M('Although the diplomat’s tone was (i)___, her message was unmistakably (ii)___: any further incursion would be met with force.',
    [['respectful', 'impudent'], ['hostile', 'conciliatory']],
    '“Although” contrasts tone with message. The message — “met with force” — is aggressive (ii); the tone is its polite opposite (i).'),
  M('Early reviewers were quick to (i)___ the novel as a trivial romance, but later critics recognized it as a (ii)___ work that anticipated many of the century’s great themes.',
    [['belittle', 'honor'], ['crucial', 'trivial']],
    '“As a trivial romance” = belittled (i). “But later critics recognized” reverses the judgment: a pivotal, important work (ii).'),
  M('The investigation revealed that the charity’s leaders, publicly so (i)___, had privately diverted millions for their own use, an act of (ii)___ that shocked even hardened auditors.',
    [['selfless', 'greedy'], ['deceit-n', 'integrity-n']],
    'Publicly presented as unselfish (i), privately stealing — the scheme is deception (ii).'),
  M('Because the evidence for the hypothesis remains (i)___, most researchers are (ii)___ about drawing firm conclusions.',
    [['meager', 'abundant'], ['cautious', 'reckless']],
    '“Because … most researchers are” hesitant — thin evidence (i) makes them wary (ii).'),
  M('The chef’s early dishes were (i)___, relying on the same few ingredients in predictable combinations; her later menus, by contrast, were (ii)___, drawing on cuisines from four continents.',
    [['unoriginal', 'original'], ['varied', 'uniform']],
    '“Same few ingredients in predictable combinations” = unoriginal (i). “By contrast … four continents” = diverse (ii).'),
  M('The new manager’s (i)___ temper, which led her to shout at staff over minor mistakes, soon began to (ii)___ the team’s morale.',
    [['irritable', 'friendly'], ['undermine', 'bolster']],
    'Shouting over minor mistakes = a bad temper (i). That would weaken morale (ii).'),
  M('What the author presents as a (i)___ account of the war is in fact deeply (ii)___, omitting every fact that contradicts her thesis.',
    [['impartial', 'biased'], ['biased', 'impartial']],
    '“Omitting every fact that contradicts her thesis” = one-sided (ii). “Presents as … is in fact” contrasts it with the claim: neutral (i).'),
  M('The (i)___ student rarely spoke in seminars, but her essays were so (ii)___ that the professor read them aloud as models.',
    [['shy', 'bold'], ['eloquent', 'inarticulate']],
    '“Rarely spoke” = shy (i). “But … read them aloud as models” = articulate, persuasive writing (ii).'),
  M('After the scandal, the senator’s once-(i)___ supporters rushed to (ii)___ the views they had shared with him, fearing that the association would damage their own careers.',
    [['steadfast', 'fickle'], ['renounce', 'confirm']],
    '“Once-” implies they used to be loyal (i). Fearing damage, they now disavowed those views (ii).'),
  M('The drug’s side effects, though (i)___ for most patients, can be (ii)___ for those with weakened immune systems.',
    [['harmless', 'harmful'], ['harmful', 'harmless']],
    '“Though … for most, … for those with weakened immune systems” contrasts two groups: harmless (i) vs. harmful (ii).'),
  M('Her (i)___ manner in meetings, which led her to agree with whoever had spoken last, made it impossible to know her (ii)___ opinion of the plan.',
    [['flexible', 'stubborn'], ['honest', 'deceitful']],
    'Agreeing with whoever spoke last = easily swayed (i). So her real, frank opinion was impossible to know (ii).'),
  M('The landscape, which had seemed (i)___ in the harsh light of noon, looked almost (ii)___ at dusk, softened by long shadows and golden light.',
    [['austere', 'ornate'], ['peaceful', 'turbulent']],
    '“Harsh light” = stark and severe (i). “Softened” at dusk = tranquil (ii).'),
  M('While the old treasurer’s reviews of the budget had been (i)___, the new treasurer’s were almost (ii)___, questioning every expense down to the last paper clip.',
    [['perfunctory', 'careful'], ['fussy', 'perfunctory']],
    '“While” sets up a contrast with “questioning every expense” — excessively particular (ii). The old reviews were the opposite: cursory (i).'),
  M('The company’s profits, (i)___ for years, began to (ii)___ when a rival released a cheaper product.',
    [['lasting', 'fleeting'], ['subside', 'proliferate']],
    '“For years” = stable and enduring (i). A cheaper rival product would make profits shrink (ii).'),
  M('The historian’s (i)___ research, which kept her in the archives for a decade, gives her conclusions an authority that the (ii)___ reviews of her critics, based only on secondary sources, cannot match.',
    [['hardworking', 'lazy'], ['perfunctory', 'careful']],
    'A decade in the archives = diligent (i). Reviews based only on secondary sources are superficial (ii).'),
  M('Although the witness appeared (i)___ on the stand, answering every question calmly, she later admitted that she had been (ii)___ throughout.',
    [['calm-person', 'agitated'], ['agitated', 'calm-person']],
    '“Answering every question calmly” = composed (i). “Although … later admitted” reveals the opposite inside: agitated (ii).'),
  M('The playwright’s early comedies are (i)___ and lighthearted; her later work, written after the war, is (ii)___ and often tragic.',
    [['humorous', 'serious'], ['serious', 'humorous']],
    '“Lighthearted” pairs with (i): humorous. The later work is contrasted — “often tragic” = solemn (ii).'),
  M('Critics accused the agency of trying to (i)___ the report’s alarming findings, releasing it late on a Friday with no press conference in the hope that public concern would quickly (ii)___.',
    [['understate', 'exaggerate'], ['subside', 'proliferate']],
    'Burying the release = downplaying the findings (i). The hope is that concern would die down (ii).'),
  M('Scholars once regarded the manuscript as a forgery, but new chemical tests appear to (i)___ its authenticity, and even (ii)___ critics now concede it is genuine.',
    [['confirm', 'disprove'], ['skeptical', 'gullible']],
    '“But new tests appear to …” reverses the forgery view: they support authenticity (i). “Even … critics now concede” = the formerly doubtful ones (ii).'),
  M('The mountain village, (i)___ for most of the year, is transformed each August into a (ii)___ scene of music, crowds, and fireworks.',
    [['peaceful', 'turbulent'], ['lively', 'lazy']],
    '“Transformed … into a scene of music, crowds, and fireworks” = energetic and lively (ii). The contrast makes the rest of the year tranquil (i).'),
  M('The auditor’s report was (i)___, listing each irregularity with page references, and its conclusions were anything but (ii)___: the firm, it said plainly, had broken the law.',
    [['careful', 'sloppy'], ['ambiguous', 'explicit']],
    'Listing each irregularity with page references = meticulous (i). “Anything but … : it said plainly” = not vague at all (ii).'),
  M('Though the professor’s manner in class was (i)___, even forbidding, her office hours revealed a (ii)___ side that students came to treasure.',
    [['aloof', 'friendly'], ['kind', 'unfeeling']],
    '“Even forbidding” amplifies (i): distant, cold. “Though … revealed a … side that students came to treasure” = warm, caring (ii).'),
  M('The council’s (i)___ decision, made in a single rushed meeting without any expert testimony, has had (ii)___ consequences for the town’s water supply.',
    [['reckless', 'cautious'], ['harmful', 'beneficial']],
    '“A single rushed meeting without any expert testimony” = rash (i). The context of blame implies damaging consequences (ii).'),
  M('In contrast to the (i)___ official histories, which glorify every decision of the regime, the recently opened archives present a far more (ii)___ picture.',
    [['flattering', 'arrogant'], ['impartial', 'biased']],
    '“Glorify every decision” = fawning (i). “In contrast … far more” = balanced, even-handed (ii).'),
  M('The famine was caused less by a (i)___ of grain than by corrupt officials who were allowed to (ii)___ the supplies that did exist.',
    [['dearth-n', 'excess-n'], ['squander', 'conserve']],
    '“Less by … than by corrupt officials” — the obvious cause (a shortage, i) is contrasted with officials wasting the supplies that existed (ii).'),
  M('Her (i)___ approach to the negotiation, conceding nothing and threatening to walk out at every turn, only served to (ii)___ the other side.',
    [['stubborn', 'flexible'], ['provoke', 'placate']],
    '“Conceding nothing” = unyielding (i). Threats at every turn would anger the other side (ii).'),
  M('The ancient treaty remained in force for centuries, and no ruler dared to (i)___ it, for the people held its terms to be almost (ii)___.',
    [['abolish', 'authorize'], ['crucial', 'trivial']],
    '“No ruler dared to …” a treaty in force = cancel it (i). Rulers wouldn’t dare because the people held its terms to be of supreme importance (ii).'),
  M('Unlike his (i)___ brother, who spent his inheritance within a year, Marcus was so (ii)___ that he still lived on the interest decades later.',
    [['extravagant', 'thrifty'], ['thrifty', 'extravagant']],
    '“Spent his inheritance within a year” = wasteful (i). “Unlike … still lived on the interest” = frugal (ii).'),
  M('The drug company was accused of trying to (i)___ the results of the trial, publishing only the favorable data while it chose to (ii)___ every study that showed harm.',
    [['exaggerate', 'understate'], ['suppress', 'spread']],
    'Publishing only favorable data overstates the benefits (i); hiding harmful studies = suppressing them (ii).'),
  M('Although the actor’s public persona was (i)___, full of jokes and bravado, his friends knew him as (ii)___ and deeply private.',
    [['cheerful', 'sad'], ['taciturn', 'talkative']],
    '“Full of jokes and bravado” = high-spirited (i). “Although … deeply private” = reserved, saying little (ii).'),
  M('The architect’s first buildings were so (i)___ that critics called them boxes; her later work, with its sweeping curves and bold colors, is anything but (ii)___.',
    [['dull', 'lively'], ['dull', 'lively']],
    '“Critics called them boxes” = lifeless (i). “Anything but” + “sweeping curves and bold colors” means the later work is NOT dull — the same idea again (ii).'),
  M('The reporter’s (i)___ questions, which went straight to the heart of the scandal, left the minister unable to (ii)___ the charges against him.',
    [['relevant', 'irrelevant'], ['disprove', 'confirm']],
    '“Straight to the heart of the scandal” = pertinent (i). Left unable to answer them = unable to refute the charges (ii).'),
  M('Some scholars (i)___ the poet’s later work, finding it thin and repetitive, but others (ii)___ it as the finest of her career.',
    [['belittle', 'honor'], ['praise', 'criticize']],
    '“Finding it thin and repetitive” = disparage it (i). “But others … as the finest” = praise it (ii).'),
  M('The explorer’s (i)___ was legendary: she once crossed a glacier alone at night, a feat most of her colleagues considered not brave but (ii)___.',
    [['boldness-n', 'timidity-n'], ['reckless', 'cautious']],
    'Crossing a glacier alone at night = daring (i). “Not brave but …” = foolhardy (ii).'),
  M('The old mill town, once (i)___, is now (ii)___: most of its factories stand empty, and a third of its residents live below the poverty line.',
    [['wealthy', 'poor'], ['poor', 'wealthy']],
    '“Factories stand empty … below the poverty line” = impoverished (ii). “Once … now” signals change, so (i) = prosperous.'),
  M('The teacher’s (i)___ comments, meant only as a joke, deeply hurt the student, who took them as (ii)___.',
    [['flippant', 'serious'], ['malicious', 'kind']],
    '“Meant only as a joke” but hurtful = inappropriately light (i). The student read them as intentionally hurtful (ii).'),
  M('Rather than (i)___ the young scientist’s unconventional idea, the committee chose to (ii)___ her research with a three-year grant.',
    [['belittle', 'honor'], ['bolster', 'undermine']],
    '“Rather than … chose to … with a three-year grant” — funding supports her research (ii); the rejected alternative is dismissing the idea (i).'),
  M('The union’s initial demands were (i)___, but its leaders grew steadily more (ii)___ as the strike dragged on, refusing every compromise the company offered.',
    [['meager', 'abundant'], ['stubborn', 'flexible']],
    '“Refusing every compromise” defines (ii): intransigent. “Initial … but … grew steadily more” contrasts that with how small the demands were at first (i).'),
  M('Popular accounts tend to (i)___ the role of the lone genius; historians of science, more (ii)___, emphasize the many collaborators behind every discovery.',
    [['exaggerate', 'understate'], ['impartial', 'biased']],
    'Historians “emphasize the many collaborators” — so popular accounts overstate the lone genius (i). The historians are presented as more balanced (ii).'),
  M('The speaker was (i)___, pausing often and losing her place in her notes, but her argument itself was (ii)___, and the audience was persuaded.',
    [['inarticulate', 'eloquent'], ['clear', 'obscure']],
    '“Pausing often and losing her place” = halting delivery (i). “But … the audience was persuaded” = the argument was lucid (ii).'),

  // ---------------------------------------------------------- three blanks
  M('The committee’s chair, usually (i)___ in debate, surprised everyone by losing her temper; her outburst, however, did not (ii)___ her colleagues, who agreed that her objections were entirely (iii)___.',
    [['calm-person', 'agitated'], ['provoke', 'placate'], ['relevant', 'irrelevant']],
    '“Surprised everyone by losing her temper” means she is normally composed (i). “However … did not … her colleagues, who agreed” — her outburst did not anger them (ii) because her objections were to the point (iii).'),
  M('The scientist’s early papers were (i)___ and largely ignored; only after a decade of (ii)___ work did her colleagues begin to (iii)___ her as the field’s leading figure.',
    [['obscure', 'clear'], ['hardworking', 'lazy'], ['honor', 'belittle']],
    '“Largely ignored” fits hard-to-follow early papers (i). “Only after a decade of … work” = persistent, diligent effort (ii), after which colleagues began to revere her (iii).'),
  M('Critics called the policy (i)___, arguing that its benefits would be (ii)___ while its costs, borne by the poorest households, would be anything but (iii)___.',
    [['harmful', 'beneficial'], ['meager', 'abundant'], ['trivial', 'crucial']],
    'Critics attacking a policy call it damaging (i). Its benefits would be small (ii), while its costs would be “anything but” trivial — that is, significant (iii).'),
  M('Far from being the (i)___ adventurer of legend, the explorer was by temperament (ii)___, planning every expedition for years so that no storm or rival could (iii)___ her plans.',
    [['reckless', 'cautious'], ['cautious', 'reckless'], ['thwart', 'facilitate']],
    '“Planning every expedition for years” = circumspect (ii), so the legend she is “far from” is the rash adventurer (i). Planning for years so nothing could foil her plans is the point of (iii): thwart.'),
  M('Although the new mayor promised to be (i)___ with public money, her administration proved (ii)___, and by the end of her term the city’s reserves had begun to (iii)___.',
    [['thrifty', 'extravagant'], ['extravagant', 'thrifty'], ['subside', 'proliferate']],
    '“Although … promised … proved” sets promise against reality: she promised frugality (i) but was wasteful (ii), so the reserves shrank (iii).'),
  M('The biographer set out to (i)___ the myth of the general as a simple soldier, showing him instead to be a (ii)___ politician whose apparent frankness concealed a talent for (iii)___.',
    [['disprove', 'confirm'], ['sly', 'naive'], ['deceit-n', 'candor-n']],
    '“Showing him instead to be” = debunking the myth (i). A politician whose frankness “concealed” something is crafty (ii), and what it concealed is deception (iii).'),
  M('The candidate’s speeches, once (i)___ and full of specific proposals, have become (ii)___ and evasive, suggesting that she has decided to (iii)___ on the issues that divide her party.',
    [['explicit', 'ambiguous'], ['ambiguous', 'explicit'], ['hesitate', 'decide']],
    '“Full of specific proposals” = explicit (i). “Have become … and evasive” = vague (ii). Evasiveness on divisive issues suggests she is wavering (iii).'),
  M('The new CEO inherited a (i)___ company, its cash nearly exhausted; she moved quickly to (ii)___ the wasteful contracts her predecessor had signed, and within two years she was earning (iii)___ from investors who had written the company off.',
    [['poor', 'wealthy'], ['abolish', 'authorize'], ['praise-n', 'criticism-n']],
    '“Its cash nearly exhausted” = impoverished (i). Getting out of wasteful contracts means canceling — rescinding — them (ii). The turnaround earned praise (iii).'),
  M('Reviewers found the novel’s prose (i)___, full of clichés, and its characters (ii)___; only its (iii)___ plot, twisting through five timelines, held their interest.',
    [['unoriginal', 'original'], ['dull', 'lively'], ['complicated', 'simple']],
    '“Full of clichés” = hackneyed prose (i). Only the plot held interest, so the characters were dull (ii). “Twisting through five timelines” = intricate (iii).'),
  M('The negotiations began in a spirit of (i)___, but as each side accused the other of bad faith, a deep (ii)___ set in, and the talks collapsed amid mutual (iii)___.',
    [['harmony-n', 'hostility-n'], ['hostility-n', 'harmony-n'], ['criticism-n', 'praise-n']],
    '“Began … but” signals a decline: from goodwill (i) to animosity (ii), ending in mutual condemnation (iii).'),
  M('At first the villagers were (i)___ of the engineers’ plan to divert the river, but when the first dry summer passed without shortages, even the most (ii)___ residents began to (iii)___ it.',
    [['skeptical', 'gullible'], ['stubborn', 'flexible'], ['praise', 'criticize']],
    '“At first … but when … passed without shortages” marks a change of heart: doubt (i) giving way to approval (iii) — even among the most obstinate (ii).'),
  M('The pianist’s technique was (i)___, but her interpretations were so (ii)___ — she played the same sonata three completely different ways in one week — that critics found her (iii)___.',
    [['careful', 'sloppy'], ['fickle', 'steadfast'], ['anomalous', 'ordinary']],
    'Technique praised as meticulous (i), “but” the interpretations were changeable — three ways in one week (ii) — so critics found her unusual, hard to classify (iii).'),
  M('The official’s (i)___ reply to the families’ questions, which dismissed their concerns in two sentences, only served to (ii)___ their anger and (iii)___ the protests.',
    [['perfunctory', 'careful'], ['worsen', 'alleviate'], ['bolster', 'undermine']],
    '“Dismissed their concerns in two sentences” = cursory (i). That would inflame their anger (ii) and strengthen the protests (iii).'),
  M('Although the theory was (i)___ enough to explain every observation, its (ii)___ equations, spanning dozens of pages, made it (iii)___ to all but a few specialists.',
    [['versatile', 'fickle'], ['complicated', 'simple'], ['obscure', 'clear']],
    'Able to explain every observation = adaptable (i). “Although … its … equations, spanning dozens of pages” = convoluted (ii), making it abstruse to non-specialists (iii).'),
  M('The small bakery’s success was no accident: its owners were (i)___ in their standards, (ii)___ with their ingredients, and (iii)___ toward every customer who walked through the door.',
    [['rigorous', 'lenient'], ['careful', 'sloppy'], ['friendly', 'aloof']],
    '“No accident” means each trait is a strength: demanding standards (i), meticulous with ingredients (ii), warm toward customers (iii).'),
  M('The regime tried to (i)___ news of the protests, but reports continued to (ii)___ online, and the government’s (iii)___ denials convinced no one.',
    [['suppress', 'spread'], ['proliferate', 'subside'], ['deceitful', 'honest']],
    '“Tried to … but reports continued” = tried to stifle them (i), yet reports multiplied (ii). Denials of known events are dishonest (iii).'),
  M('The young editor was (i)___ enough to challenge the publisher’s decision, but her memo was so (ii)___ and well reasoned that, instead of firing her, the publisher chose to (iii)___ the decision.',
    [['bold', 'shy'], ['clear', 'obscure'], ['renounce', 'confirm']],
    'Challenging the publisher takes nerve (i). A memo that persuaded must have been lucid (ii), and the publisher reversed — disavowed — the decision (iii).'),
  M('What looks like (i)___ in the cat — hours spent motionless in the sun — is in fact a (ii)___ way to (iii)___ energy between bursts of hunting.',
    [['lethargy-n', 'vigor-n'], ['wise', 'foolish'], ['conserve', 'squander']],
    'Hours motionless looks like sluggishness (i), but “in fact” it is a sensible (ii) way of saving (iii) energy.'),
  M('The museum’s director, (i)___ by temperament, refused to (ii)___ her decision to show the controversial exhibit despite furious protests, insisting that the gallery’s duty was to show art, not to (iii)___ its critics.',
    [['stubborn', 'flexible'], ['abolish', 'authorize'], ['placate', 'provoke']],
    'Refusing despite furious protests = unyielding (i). She would not revoke her decision (ii); the gallery’s duty is not to appease critics (iii).'),
  M('The first reports of the storm were (i)___, but as the damage became clear, officials abandoned their (ii)___ tone and began to (iii)___ emergency aid.',
    [['optimistic', 'pessimistic'], ['cheerful', 'sad'], ['expedite-go', 'postpone']],
    '“But as the damage became clear … abandoned their … tone” — the early tone was upbeat (i, ii), and officials then moved to speed up (iii) aid.'),
  M('The journal’s editors, (i)___ about fraud after an earlier scandal, now demand that authors (ii)___ every result with raw data, a requirement some researchers consider (iii)___.',
    [['cautious', 'reckless'], ['confirm', 'disprove'], ['harsh', 'lenient']],
    'After a scandal, editors are wary (i), so they demand authors substantiate results (ii); some researchers consider that excessively severe (iii).'),
  M('Though the senator’s voting record was (i)___, his rhetoric was so (ii)___ that many voters believed him a radical, an impression his opponents were happy to (iii)___.',
    [['conventional', 'eccentric'], ['heterodox', 'conventional'], ['exaggerate', 'understate']],
    '“Though … so … that voters believed him a radical” — his record was mainstream (i) but his rhetoric was unorthodox (ii), and opponents would happily inflate that impression (iii).'),
  M('The documentary treats its subject with (i)___: it does not (ii)___ the singer’s failings, nor does it (iii)___ her very real achievements.',
    [['candor-n', 'deceit-n'], ['understate', 'exaggerate'], ['belittle', 'honor']],
    'A balanced treatment is frank (i): it neither minimizes her failings (ii) nor disparages her achievements (iii).'),
  M('The union and the company, (i)___ for years, have lately shown signs of (ii)___, and a new contract may soon (iii)___ the bitterness of their long dispute.',
    [['hostile', 'conciliatory'], ['harmony-n', 'hostility-n'], ['alleviate', 'worsen']],
    '“Long dispute” = antagonistic for years (i). “Lately shown signs of” change = goodwill (ii), and a contract would ease the bitterness (iii).'),
  M('The detective was (i)___ by nature, taking nothing at face value; it was this (ii)___ that allowed her to see through the suspect’s (iii)___ alibi.',
    [['skeptical', 'gullible'], ['insight-n', 'ineptitude-n'], ['deceitful', 'honest']],
    '“Taking nothing at face value” = doubting (i). Seeing through a lie requires keen judgment (ii); an alibi she saw through was false (iii).'),
  M('Although the new medication is (i)___ for most patients, doctors remain (ii)___ in prescribing it, because its long-term effects are still (iii)___.',
    [['beneficial', 'harmful'], ['cautious', 'reckless'], ['obscure', 'clear']],
    '“Although … doctors remain … because” — the drug helps (i), but doctors are wary (ii) because long-term effects are still poorly understood (iii).'),
  M('The author’s (i)___ style, with its long sentences and rare words, tends to delight some readers and (ii)___ others, who find it (iii)___.',
    [['ornate', 'austere'], ['provoke', 'placate'], ['pompous', 'humble']],
    '“Long sentences and rare words” = elaborate (i). It delights some and irritates others (ii), who find it pretentious (iii).'),
  M('The village’s (i)___ traditions, unchanged for centuries, began to (ii)___ when the new highway arrived, bringing tourists, chain stores, and a (iii)___ of outside influences.',
    [['lasting', 'fleeting'], ['subside', 'proliferate'], ['excess-n', 'dearth-n']],
    '“Unchanged for centuries” = enduring (i). A highway bringing outsiders makes traditions fade (ii), overwhelmed by a flood of influences (iii).'),
  M('The CEO, usually (i)___ with praise, was uncharacteristically (ii)___ at the meeting, where she rose to (iii)___ the engineers whose design had saved the company.',
    [['stingy', 'generous'], ['generous', 'stingy'], ['praise', 'criticize']],
    '“Usually … uncharacteristically” sets habit against the moment: normally sparing with praise (i), this time lavish (ii), lauding the engineers (iii).'),
  M('Critics were once quick to (i)___ the photographer’s work as mere documentation, but a new exhibition reveals an artist of (ii)___ ambition whose images are anything but (iii)___.',
    [['belittle', 'honor'], ['bold', 'cowardly'], ['ordinary', 'anomalous']],
    '“Once … as mere documentation, but” — the old view dismissed her (i); the exhibition reveals daring ambition (ii) and images that are far from commonplace (iii).'),
];
