import type { CheatsheetData } from '@/lib/types';

// One cheatsheet per Cracking-LeetCode lesson — the "before the interview"
// quick reference. Columns are tuned for pattern recognition:
// Signal (what in the problem screams this pattern) / Move (the template) /
// Watch (the classic trap). Aggregated globally in content/cheatsheets.ts.

const H: [string, string, string] = ['Signal', 'The move', 'Watch out'];

export const LEETCODE_CHEATSHEETS: CheatsheetData[] = [
  {
    lessonId: 'lc-method',
    opsHeaders: H,
    opsTable: [
      { op: 'Blank mind on a new problem', complexity: 'Run UMPIRE (Understand→Evaluate)', note: 'You always have a next step' },
      { op: 'Can’t see the optimal', complexity: 'State a correct brute force first', note: 'It’s a real answer; optimize from it' },
      { op: '“Which pattern?”', complexity: 'Match against the signal→pattern table', note: 'Recognition, not memorization' },
      { op: 'Wrong answer', complexity: 'print() the intermediate values', note: 'Read what the code does, don’t stare' },
    ],
    useWhen: 'Every single problem — this is the loop you run before reaching for any specific pattern.',
    dontUseWhen: 'Never skip it; even a 30-second UMPIRE pass beats diving into code blind.',
    stdlib: 'the in-app editor · the /playground scratchpad · hints then solution',
    stdlibLabel: 'Your tools',
    bullets: [
      'UMPIRE: Understand, Match, Plan, Implement, Review, Evaluate — in order.',
      'A correct brute force pins the contract and is usually one deletion away from the optimal.',
      'You’re learning ~15 patterns, not 3,000 problems.',
      'Think out loud, even alone — it catches wrong assumptions early.',
    ],
    gotchas: [
      'Diving in after one read — restate the problem and name edge cases first.',
      'Debugging by staring — print the values instead.',
    ],
  },
  {
    lessonId: 'lc-constraints',
    opsHeaders: H,
    opsTable: [
      { op: 'n ≤ 10–12', complexity: 'O(n!) ok', note: 'permutations / brute over orderings' },
      { op: 'n ≤ 20–25', complexity: 'O(2ⁿ) ok', note: 'subsets, bitmask, backtracking' },
      { op: 'n ≤ 5,000', complexity: 'O(n²) ok', note: 'nested loops, most 2-D DP' },
      { op: 'n ≤ 10⁵–10⁶', complexity: 'O(n log n) / O(n)', note: 'sort, heap, two pointers, hashing' },
      { op: 'n ≥ 10⁸', complexity: 'O(log n) / O(1)', note: 'binary search or math' },
    ],
    useWhen: 'Before writing any code — convert the bound into an operations budget (~10⁸/second) to rule algorithms in or out.',
    dontUseWhen: 'You already know the intended complexity from the pattern; the constraint just confirms it.',
    stdlib: '~10⁸ simple operations per second is the mental budget',
    stdlibLabel: 'Rule of thumb',
    bullets: [
      'Plug the max n into candidate complexities; anything over ~10⁹ total ops is too slow.',
      'A tiny n (≤ ~20) is permission to go exponential — backtracking or bitmask.',
      'A huge n (10⁹+) means you can’t even read every element: O(log n) or a formula.',
      'If you think of an O(n²) idea but n is 10⁵, don’t write it — keep looking.',
    ],
    gotchas: [
      'Ignoring the constraints section — it’s a hint the setter left you.',
      'Python’s constant factor is large; be conservative near the budget.',
    ],
  },
  {
    lessonId: 'lc-two-pointers',
    opsHeaders: H,
    opsTable: [
      { op: 'Sorted array + pair/target', complexity: 'Opposite ends, move the “wrong” side', note: 'O(n), O(1) space' },
      { op: 'Palindrome / from both ends', complexity: 'left=0, right=n-1, step inward', note: 'compare, then converge' },
      { op: 'In-place filter / dedupe', complexity: 'Fast/slow, same direction', note: 'slow writes, fast scans' },
      { op: 'Container / max-area', complexity: 'Move the shorter wall inward', note: 'the greedy that’s provably safe' },
    ],
    useWhen: 'Input is sorted (or sortable), asks about pairs, or works from both ends. The cheapest pattern — try it first.',
    dontUseWhen: 'You need every unordered pair with no structure, or index output on unsorted data (use hashing).',
    stdlib: 'no library needed — just two indices',
    stdlibLabel: 'Tools',
    bullets: [
      'Opposite-ends template: left, right = 0, n-1; while left < right: move the pointer whose value is wrong.',
      'The decision inside the loop (which pointer moves) is the whole skill.',
      'Container-with-water: move the shorter wall — the taller one can never improve the area.',
      'O(n) time, O(1) space — no extra data structure.',
    ],
    gotchas: [
      'Using it on unsorted data expecting sorted behavior — name the structure you’re exploiting.',
      'Sorting first costs O(n log n) and loses original indices.',
    ],
  },
  {
    lessonId: 'lc-sliding-window',
    opsHeaders: H,
    opsTable: [
      { op: 'Contiguous subarray/substring', complexity: 'Slide a window, reuse overlap', note: 'the core signal' },
      { op: 'Fixed size k', complexity: 'window += enter − leave', note: 'O(1) per slide, O(n) total' },
      { op: '“longest/shortest/at most k”', complexity: 'Grow right, shrink left while invalid', note: 'both pointers forward-only' },
      { op: 'Track a condition', complexity: 'Running sum / count map / set', note: 'defines “invalid”' },
    ],
    useWhen: 'A contiguous chunk with “longest / shortest / max sum / at most k distinct.”',
    dontUseWhen: 'Values can be negative and you need a target sum — the window’s monotonicity breaks; use prefix sums + hashmap.',
    stdlib: 'collections.Counter / a set for the window contents',
    stdlibLabel: 'Tools',
    bullets: [
      'Fixed window: compute the first, then +enter −leave each step.',
      'Variable window: grow the right edge, shrink the left while the window violates its rule.',
      'Both edges only move forward → O(n) even with the inner while-loop.',
      'The art is defining “invalid” and what to track.',
    ],
    gotchas: [
      'Negatives break the “extending only grows the sum” assumption — switch to prefix sums.',
      'Forgetting to update the answer at the right moment (after re-validating).',
    ],
  },
  {
    lessonId: 'lc-hashing',
    opsHeaders: H,
    opsTable: [
      { op: '“Have I seen this?”', complexity: 'set membership', note: 'O(1) average lookup' },
      { op: '“What’s paired / which index?”', complexity: 'dict value→index', note: 'Two Sum: look for target−n' },
      { op: '“How many of each?”', complexity: 'collections.Counter', note: 'mode, grouping, anagrams' },
      { op: 'Subarray sum = k (with negatives)', complexity: 'prefix sum + count map', note: 'count earlier prefixes = prefix−k' },
    ],
    useWhen: 'An inner loop is searching for something — replace the search with an O(1) hash lookup.',
    dontUseWhen: 'You need ordering or position and only stored membership — use a dict (index) or sorting/heap.',
    stdlib: 'dict · set · collections.Counter · collections.defaultdict',
    stdlibLabel: 'Python',
    bullets: [
      'Memory buys lookup speed: O(n) space to make “is it here?” O(1).',
      'Two Sum on unsorted data → hash map (keeps indices), not sort + two pointers.',
      'Group anagrams: key each word by its sorted letters (or a letter-count tuple).',
      'Prefix-sum + hashmap counts subarrays summing to k, even with negatives.',
    ],
    gotchas: [
      'dict/set are O(1) average, not worst case, and cost real memory.',
      'A set discards position — store the index in a dict if you need “where.”',
    ],
  },
  {
    lessonId: 'lc-binary-search',
    opsHeaders: H,
    opsTable: [
      { op: 'Sorted array, find target', complexity: 'lo<=hi, mid±1', note: 'the bug-free exact-match template' },
      { op: '“min/max X such that …”', complexity: 'Binary-search the ANSWER', note: 'needs a monotonic works(x)' },
      { op: 'Find a boundary', complexity: 'lo<hi, hi=mid / lo=mid+1', note: 'return lo' },
      { op: 'Rotated sorted array', complexity: 'Decide which half is sorted', note: 'then discard the other' },
    ],
    useWhen: 'Sorted data, or “smallest/largest value that satisfies a monotonic condition.” Also any 10⁹ constraint.',
    dontUseWhen: 'The feasibility test isn’t monotonic — binary search on the answer is invalid.',
    stdlib: 'the bisect module (bisect_left / bisect_right)',
    stdlibLabel: 'Python',
    bullets: [
      'Exact match: lo, hi = 0, n-1; while lo <= hi; move mid ± 1.',
      'Boundary/on-the-answer: while lo < hi; if works(mid): hi = mid else lo = mid+1; return lo.',
      '“Binary search on the answer” searches the range of possible answers, not the array.',
      'Write the works(x) feasibility check first — it’s usually a simple loop.',
    ],
    gotchas: [
      'Mixing the two templates causes off-by-one or infinite loops — match template to question.',
      'hi = mid - 1 when mid could be the answer skips the real answer.',
    ],
  },
  {
    lessonId: 'lc-stacks',
    opsHeaders: H,
    opsTable: [
      { op: 'Matching / nesting / undo', complexity: 'Plain stack (LIFO)', note: 'top = most recent unresolved' },
      { op: 'Balanced brackets', complexity: 'Push openers, match on close', note: 'end: stack must be empty' },
      { op: '“Next greater/smaller element”', complexity: 'Monotonic stack of indices', note: 'pop when new value resolves top' },
      { op: 'Span / distance until bigger', complexity: 'record i − j on pop', note: 'store indices, not values' },
    ],
    useWhen: 'The problem is about the most recent unresolved item, or “for each element, the nearest bigger/smaller.”',
    dontUseWhen: 'You need random access or ordering of all elements — that’s an array/heap.',
    stdlib: 'a plain list (append / pop)',
    stdlibLabel: 'Python',
    bullets: [
      'Plain stack invariant: the top is always the most recent unresolved thing.',
      'Monotonic stack keeps candidates in increasing/decreasing order; each index is pushed and popped once.',
      'That once-each is why the nested loop is O(n) amortized, not O(n²).',
      'For “next greater,” keep the stack decreasing and pop when a bigger value arrives.',
    ],
    gotchas: [
      'Store indices (not values) when you need distances like i − j.',
      'Get the monotonic direction right or you compute “next smaller” by accident.',
    ],
  },
  {
    lessonId: 'lc-linked-list',
    opsHeaders: H,
    opsTable: [
      { op: 'Front might change', complexity: 'Dummy head sentinel', note: 'return dummy.next' },
      { op: 'Reverse in place', complexity: 'Three pointers', note: 'save nxt before flipping' },
      { op: 'Midpoint / cycle', complexity: 'Fast/slow pointers', note: 'O(1) space vs a visited set' },
      { op: 'Merge two lists', complexity: 'Dummy + splice smaller each step', note: 'O(1) space' },
    ],
    useWhen: 'Any singly/doubly linked list manipulation — reversal, merge, cycle, nth-from-end.',
    dontUseWhen: 'You need random access by index — that’s an array.',
    stdlib: 'just ListNode (.val, .next)',
    stdlibLabel: 'Structure',
    bullets: [
      'Dummy head erases the special case for changes at the front.',
      'Reversal: prev/curr/nxt — always save nxt = curr.next before overwriting.',
      'Fast/slow: slow +1, fast +2; they meet inside a cycle, and slow lands at the midpoint.',
      'Guard the loop: while fast and fast.next.',
    ],
    gotchas: [
      'None.next → AttributeError; check the pointer before following it.',
      'Test the empty list and single node first — that’s where list code dies.',
    ],
  },
  {
    lessonId: 'lc-trees',
    opsHeaders: H,
    opsTable: [
      { op: 'Subtree info / all paths', complexity: 'Recursive DFS', note: 'trust children, return info up' },
      { op: 'Shortest steps / by level', complexity: 'BFS with a queue', note: 'drain one level per iteration' },
      { op: 'Combine children', complexity: 'return combine(node, left, right)', note: 'define what each call returns' },
      { op: 'Very deep tree', complexity: 'Explicit stack, not recursion', note: 'avoid the ~1000 recursion limit' },
    ],
    useWhen: 'Any binary-tree traversal or aggregation; BFS when depth/shortest matters.',
    dontUseWhen: 'The structure has cycles — that’s a general graph (add a visited set).',
    stdlib: 'collections.deque for BFS',
    stdlibLabel: 'Python',
    bullets: [
      'DFS template: if not node: return base; recurse both sides; combine.',
      'Don’t trace the whole tree — trust the recursion on the children.',
      'BFS: snapshot len(queue) each iteration so children land in the next level.',
      'First BFS arrival = fewest edges → shortest path in unweighted trees/graphs.',
    ],
    gotchas: [
      'Handle the empty tree (root is None) as the first line.',
      'Recursive DFS depth = tree height; a degenerate tree can overflow the stack.',
    ],
  },
  {
    lessonId: 'lc-heaps',
    opsHeaders: H,
    opsTable: [
      { op: '“k largest” of many/stream', complexity: 'Size-k MIN-heap', note: 'root = weakest champion' },
      { op: '“k smallest”', complexity: 'Size-k max-heap (negate)', note: 'heapq is min-only' },
      { op: 'Top k frequent', complexity: 'Counter + heap', note: 'most_common(k)' },
      { op: 'Merge k sorted / median stream', complexity: 'Heap of heads / two heaps', note: 'O(log k) per step' },
    ],
    useWhen: '“k largest/smallest/most frequent,” median of a stream, or merge-k. The answer is the top few, not the full order.',
    dontUseWhen: 'You need everything sorted (use sort) or O(1) lookup by key (use a dict).',
    stdlib: 'heapq (heappush/heappop/heapify) · collections.Counter',
    stdlibLabel: 'Python',
    bullets: [
      'Top-K-largest → size-k min-heap: the root is the only champion a newcomer must beat.',
      'O(n log k) time, O(k) space — beats sorting when k ≪ n and works on streams.',
      'heapq is min-only: push negatives for a max-heap; push (priority, tiebreak, item) tuples for custom order.',
      'Below the root a heap is NOT sorted — only h[0] is meaningful.',
    ],
    gotchas: [
      'Forgetting heapq is min-only gives you the k smallest by accident.',
      'h[1] is not the second-smallest.',
    ],
  },
  {
    lessonId: 'lc-backtracking',
    opsHeaders: H,
    opsTable: [
      { op: 'Generate ALL subsets/perms/combos', complexity: 'choose → explore → un-choose', note: 'usually small n' },
      { op: 'Record a solution', complexity: 'res.append(path[:])', note: 'COPY, or it mutates later' },
      { op: 'Avoid permuted duplicates', complexity: 'Pass a start index', note: 'only consider choices ≥ start' },
      { op: 'Dead branch', complexity: 'Prune / return early', note: 'DFS over a decision tree' },
    ],
    useWhen: '“All arrangements/combinations,” or search over choices — with small n (the constraint says so).',
    dontUseWhen: 'You only need a count or an optimum with overlapping subproblems — that’s DP.',
    stdlib: 'recursion + one mutable path list',
    stdlibLabel: 'Tools',
    bullets: [
      'Template: choose (append), explore (recurse), un-choose (pop).',
      'It’s DFS over an implicit tree of decisions — prune branches that can’t succeed.',
      'Store path[:] copies at complete states.',
      'Reuse allowed → recurse with i; no reuse → recurse with i+1.',
    ],
    gotchas: [
      'res.append(path) (no copy) makes every answer the same list.',
      'Forgetting path.pop() leaks state between sibling branches.',
    ],
  },
  {
    lessonId: 'lc-graphs',
    opsHeaders: H,
    opsTable: [
      { op: 'Grid / “connected cells”', complexity: 'DFS/BFS, cell = node', note: '4 neighbors = edges' },
      { op: 'Count regions / islands', complexity: 'Flood fill each blob', note: 'connected components' },
      { op: 'Shortest unweighted path', complexity: 'BFS', note: 'first arrival = fewest steps' },
      { op: 'Ordering under dependencies', complexity: 'Topological sort (Kahn)', note: 'queue starves = cycle' },
    ],
    useWhen: 'Grids, connectivity, shortest unweighted path, or dependency ordering/cycle detection.',
    dontUseWhen: 'Edges have weights and you need shortest path — use Dijkstra (min-heap frontier).',
    stdlib: 'collections.deque · defaultdict(list)',
    stdlibLabel: 'Python',
    bullets: [
      'Grid neighbors: the 4 (dr,dc) offsets with a bounds check are your edges.',
      'Flood fill = count connected components (islands, regions).',
      'BFS gives shortest steps because it expands in distance layers.',
      'Kahn’s topo sort: queue in-degree-0 nodes; if you can’t take all n, there’s a cycle.',
    ],
    gotchas: [
      'Mark visited at ENQUEUE time, not dequeue, or nodes get processed multiple times.',
      'Never omit visited tracking on a graph with cycles — it loops forever.',
    ],
  },
  {
    lessonId: 'lc-dp-1d',
    opsHeaders: H,
    opsTable: [
      { op: '“count ways / min / max over choices”', complexity: 'Define dp[state] + transition', note: 'overlapping subproblems' },
      { op: 'First correct version', complexity: 'Top-down memoized recursion', note: 'mirrors the recurrence' },
      { op: 'No recursion / clear cost', complexity: 'Bottom-up tabulation', note: 'fill base cases up' },
      { op: 'State reads last few entries', complexity: 'Space-optimize to O(1)', note: 'rolling variables' },
    ],
    useWhen: 'Counting ways or optimizing over a sequence of decisions where subproblems repeat.',
    dontUseWhen: 'Choices don’t overlap (greedy or plain recursion) or you must list all solutions (backtracking).',
    stdlib: 'functools.lru_cache for painless memoization',
    stdlibLabel: 'Python',
    bullets: [
      'DP = state (the precise subproblem) + transition (build from smaller) + base cases.',
      'Write the state in ONE sentence before coding — a vague state is the #1 bug.',
      'Climbing stairs is Fibonacci → two rolling variables, O(1) space.',
      'Coin change: dp[a] = min(dp[a−c]+1); greedy fails on coins like [1,3,4].',
    ],
    gotchas: [
      'A vague state (“answer so far”) yields a subtly wrong transition.',
      'Off-by-one table sizes — a state 0..n needs length n+1.',
    ],
  },
  {
    lessonId: 'lc-dp-2d',
    opsHeaders: H,
    opsTable: [
      { op: 'Two things vary (row+col, A+B)', complexity: '2-D table dp[i][j]', note: 'the state has two indices' },
      { op: 'Grid paths', complexity: 'dp[i][j]=dp[i-1][j]+dp[i][j-1]', note: 'fill top→bottom, left→right' },
      { op: 'Two sequences (LCS/edit dist)', complexity: 'split on A[i-1]==B[j-1]', note: 'diagonal on match, else skip' },
      { op: 'Table too big', complexity: 'Roll to one row', note: 'O(m·n) → O(n) space' },
    ],
    useWhen: 'A position in a grid, or comparing two sequences/strings. This tier holds many Hards (edit distance).',
    dontUseWhen: 'Only one thing varies (1-D DP) or subproblems don’t overlap.',
    stdlib: 'a list-of-lists table; functools.lru_cache for the recursive form',
    stdlibLabel: 'Python',
    bullets: [
      'Fill order must respect dependencies: up-and-left deps → iterate rows then cols ascending.',
      'Two-sequence transition: match → dp[i-1][j-1] (+1); mismatch → best of dp[i-1][j], dp[i][j-1].',
      'The extra row/column (index 0) encode empty-prefix base cases.',
      'Roll the table to one row when each cell reads only the previous row.',
    ],
    gotchas: [
      'Table size (m+1)×(n+1); the extra row/col are base cases, not padding.',
      'Mixing 0- and 1-indexing between the table and the strings.',
    ],
  },
  {
    lessonId: 'lc-hard',
    opsHeaders: H,
    opsTable: [
      { op: 'A problem labeled “Hard”', complexity: 'Decompose into 2–3 known patterns', note: 'not a brand-new algorithm' },
      { op: 'Trapping rain water', complexity: 'Two pointers + running maxes', note: 'O(1) space' },
      { op: 'Minimum window substring', complexity: 'Sliding window + frequency map', note: 'a “missing” counter' },
      { op: 'Word ladder', complexity: 'BFS over one-letter neighbors', note: 'shortest = first arrival' },
    ],
    useWhen: 'Any Hard — run UMPIRE, brute-force, read the constraints, then name the sub-patterns and compose them.',
    dontUseWhen: 'Never skip the brute force because it “feels too big” — it clarifies the contract and reveals the optimization.',
    stdlib: 'everything from this course, stacked',
    stdlibLabel: 'Toolkit',
    bullets: [
      'A Hard is usually familiar patterns stacked, or one pattern with a twist — decompose.',
      'Trapping rain water = the container-with-water greedy applied to running maxes.',
      'Minimum window = grow/shrink window (sliding) + Counter (hashing) + a missing counter.',
      'Word ladder = words as nodes, one-letter edits as edges, BFS for shortest.',
    ],
    gotchas: [
      'Reaching for something exotic when two known patterns would do.',
      'Skipping the brute force — it’s often one deletion from the real solution.',
    ],
  },
];

export { H as LC_HEADERS };
