// Word-root breakdowns, part 2 (style, value, quantity, manner; first verbs).

export const ROOTS_2 = String.raw`
uncomplicated: un- (not) + com- (together) + plic (fold) + -ated → "not folded together"
simple: sim (one) + ple (fold) → "one-fold"
elementary: element (first principle — elementum, a letter of the alphabet) + -ary → "of the ABCs"
banal: ~ from French banal, "belonging to the lord's domain" — like the village oven every peasant had to use, so common to all
trite: trit (rubbed, worn — terere) + -e → "worn down"
hackneyed: hackney (a horse for hire that anyone could ride) + -ed → "worn out like a hired horse"
clichéd: cliché (a printing plate — French clicher, the click of the mold) + -d → "stamped out like a printing plate"
novel: nov (new) + -el → "new"
innovative: in- (into) + nov (new) + -ative → "making new"
groundbreaking: ground + breaking → "breaking new ground"
inventive: in- (upon) + vent (come) + -ive → "coming upon ideas"
insipid: in- (not) + sipid (tasty — sapidus, from sapere, to taste) → "tasteless"
vapid: vap (flat, flavorless — vapidus, gone to vapor) + -id → "gone flat"
prosaic: prosa (prose) + -ic → "like prose, not poetry"
pedestrian: pedestr (on foot — pes, foot) + -ian → "going on foot," never soaring
lackluster: lack + luster (shine) → "lacking shine"
mundane: mund (world — mundus) + -ane → "worldly, earthly"
quotidian: quoti (every) + di (day — dies) + -an → "every day"
workaday: work + a + day → "for a working day"
commonplace: common + place → "a common place"
anomalous: an- (not) + omal (even — Greek homalos) + -ous → "uneven, irregular"
aberrant: ab- (away) + err (wander) + -ant → "wandering away"
atypical: a- (not) + typ (type, model) + -ical → "not typical"
irregular: ir- (not — in-) + regul (rule) + -ar → "not by the rule"
eccentric: ec- (out — ex-) + centr (center) + -ic → "off center"
idiosyncratic: idio (one's own) + syn (together) + crat (mixture) + -ic → "one's own mixture"
quirky: quirk (a sudden twist or turn) + -y → "full of twists"
unconventional: un- (not) + con- (together) + vent (come) + -ional → "not going along with the crowd"
orthodox: ortho (straight, right) + dox (opinion) → "right opinion"
conventional: con- (together) + vent (come) + -ional → "agreed on by coming together"
conformist: con- (with) + form (shape) + -ist → "one who takes the same shape"
traditional: tradit (handed over — tradere) + -ional → "handed down"
heterodox: hetero (other) + dox (opinion) → "other opinion"
heretical: here (choice — Greek hairesis) + -tical → "choosing for oneself"
iconoclastic: icono (image — eikon) + clast (break) + -ic → "image-breaking"
unorthodox: un- (not) + ortho (right) + dox (opinion) → "not the accepted opinion"
dogmatic: dogma (decree, opinion — Greek dokein, to seem) + -tic → "laying down decrees"
doctrinaire: doctrin (teaching) + -aire → "sticking to the teaching"
opinionated: opinion + -ated → "full of one's opinions"
peremptory: per- (completely) + empt (take — emere) + -ory → "taking away entirely" — final, allowing no debate
impartial: im- (not) + part (side) + -ial → "not taking a side"
dispassionate: dis- (without) + passion (feeling) + -ate → "without passion"
disinterested: dis- (not) + interest (have a stake — inter esse, to be between) + -ed → "having no stake"
evenhanded: even + hand + -ed → "with even hands"
objective: ob- (before) + ject (thrown) + -ive → "thrown before the mind" — about the thing, not oneself
partisan: parti (part, side) + -san → "of a party"
prejudiced: pre- (before) + judic (judge) + -ed → "judged beforehand"
tendentious: tend (stretch toward, aim) + -entious → "aiming at a point"
one-sided: one + sid (side) + -ed → "with only one side"
pertinent: per- (thoroughly) + tin (hold, reach — tenere) + -ent → "reaching to the point"
germane: germ (of the same parents — germanus, sibling) + -ane → "closely akin"
apposite: ap- (to — ad-) + posit (put) + -e → "put next to," fitting
apropos: a (to) + propos (purpose — French) → "to the purpose"
relevant: re- (again) + lev (lift, raise) + -ant → "bearing on"
extraneous: extra (outside) + -neous → "from outside"
irrelevant: ir- (not) + re- (again) + lev (lift) + -ant → "not bearing on"
tangential: tang (touch) + -ential → "just touching," like a tangent line
immaterial: im- (not) + materi (matter) + -al → "not of the matter"
trivial: tri (three) + vi (way, road) + -al → "where three roads meet" — street-corner chatter
inconsequential: in- (not) + con- (with) + sequ (follow) + -ential → "having nothing follow from it"
insignificant: in- (not) + sign (mark) + -ificant (making) → "making no mark"
petty: petty (small — French petit) → "small"
crucial: cruci (cross — crux) + -al → "at the crossroads," where the decision falls
pivotal: pivot (the pin a thing turns on) + -al → "what everything turns on"
vital: vit (life) + -al → "of life"
paramount: para (by — Old French par) + mount (upward — amont) → "above all"
ephemeral: ep- (on — epi-) + hemer (day) + -al → "lasting a day"
evanescent: e- (out) + van (empty, vanish) + -escent (becoming) → "vanishing away"
transient: trans (across) + i (go — ire) + -ent → "passing across"
fleeting: fleet (glide, float — Old English fleotan) + -ing → "slipping away"
transitory: trans (across) + it (go) + -ory → "passing over"
enduring: en- (in) + dur (hard, lasting) + -ing → "lasting"
abiding: abid (remain — abide) + -ing → "remaining"
perennial: per- (through) + enni (year — annus) + -al → "through the years"
durable: dur (last) + -able → "able to last"
ubiquitous: ubiqu (everywhere — ubique) + -itous → "everywhere"
pervasive: per- (through) + vas (go — vadere) + -ive → "going through"
omnipresent: omni (all) + present (being there) → "present everywhere"
prevalent: pre- (before) + val (be strong) + -ent → "prevailing"
abundant: ab- (from) + und (wave) + -ant → "overflowing in waves"
copious: copi (plenty — copia) + -ous → "plentiful"
profuse: pro- (forth) + fus (poured) + -e → "poured forth"
plentiful: plenti (plenty — plenus, full) + -ful → "full of plenty"
ample: ample (large, spacious — amplus) → "roomy"
scarce: ~ from Old French escars, from Latin excerpere, "to pick out" — picked over, little left
rare: rare (thinly scattered — rarus) → "few and far between"
scant: ~ from Old Norse skamt, "short" — falling short
sparse: spars (scattered — spargere) + -e → "scattered"
meager: ~ from Old French maigre, Latin macer, "thin" (as in emaciated)
paltry: paltr (trash, rags — palt) + -y → "trashy"
measly: measl (measles — once "spotty, wretched") + -y → "spotty, wretched"
negligible: neg (not) + lig (pick up — legere) + -ible → "not worth picking up"
deleterious: delet (hurt, destroy — Greek deleisthai) + -erious → "destructive"
pernicious: per- (completely) + nic (kill — nex, death) + -ious → "deadly"
noxious: nox (harm — noxa) + -ious → "harmful"
detrimental: de- (away) + trim (rub, wear — terere) + -ental → "wearing away"
injurious: in- (not) + jur (right, law) + -ious → "against what is right"
salutary: salut (health — salus) + -ary → "healthful"
salubrious: salubri (health-giving — salus) + -ous → "healthful"
beneficial: bene (well) + fic (making) + -ial → "doing good"
wholesome: whole (healthy, sound) + -some → "making whole"
innocuous: in- (not) + nocu (harm — nocere) + -ous → "not harmful"
benign: ben (well) + ign (born) → "well-born, kindly"
harmless: harm + -less → "without harm"
inoffensive: in- (not) + of- (against — ob-) + fens (strike) + -ive → "not striking against"
clandestine: clandest (secret — clam, in secret) + -ine → "secret"
covert: cover (covered) + -t → "covered"
surreptitious: sur- (under — sub-) + rept (snatch — rapere) + -itious → "snatched secretly"
furtive: furt (theft — fur, thief) + -ive → "like a thief"
overt: overt (opened — Old French ouvrir) → "opened"
blatant: ~ coined by Edmund Spenser for the Blatant Beast, a noisy, many-tongued monster — perhaps from Latin blatire, "to babble"
flagrant: flagr (blaze — flagrare) + -ant → "blazing"
conspicuous: con- (thoroughly) + spic (look) + -uous → "easily seen"
opulent: opul (wealth — opes) + -ent → "wealthy"
sumptuous: sumptu (expense — sumere, to spend) + -ous → "costly"
luxurious: luxur (excess — luxus) + -ious → "excessive"
plush: ~ from French peluche, a soft fabric with a long pile
austere: ~ from Greek austeros, "harsh, dry" — the puckering taste of unripe fruit
spartan: spart (Sparta, whose citizens lived famously plain, hard lives) + -an → "like a Spartan"
unadorned: un- (not) + adorn (decorate) + -ed → "not decorated"
stark: ~ from Old English stearc, "stiff, severe"
ornate: orn (decorate — ornare) + -ate → "decorated"
elaborate: e- (out) + labor (work) + -ate → "worked out"
florid: flor (flower) + -id → "flowery"
baroque: ~ from Portuguese barroco, "a misshapen pearl" — first an insult for overwrought art
ostentatious: ostent (show — ostendere) + -atious → "showing off"
flamboyant: flamboy (blaze — French flamboyer, from flamme) + -ant → "blazing"
garish: ~ perhaps from obsolete gaure, "to stare" — something that makes you stare
showy: show + -y → "full of show"
ascetic: ascet (training, exercise — Greek askein) + -ic → "in strict training"
abstemious: abs- (away from) + tem (strong drink — temetum) + -ious → "avoiding strong drink"
temperate: temper (mix in proportion, moderate) + -ate → "moderate"
abstinent: abs- (away) + tin (hold — tenere) + -ent → "holding oneself back"
hedonistic: hedon (pleasure) + -istic → "pleasure-seeking"
sybaritic: sybarit (Sybaris, a Greek city famed for luxury) + -ic → "like a Sybarite"
self-indulgent: self + in- (toward) + dulg (be kind) + -ent → "being kind to oneself"
epicurean: epicur (Epicurus, the philosopher of pleasure) + -ean → "a follower of Epicurus"
affluent: af- (to — ad-) + flu (flow) + -ent → "with riches flowing in"
prosperous: prosper (as hoped — pro spere) + -ous → "going as hoped"
wealthy: wealth (well-being — weal) + -y → "full of well-being"
moneyed: money + -ed → "having money"
impoverished: im- (into) + pover (poor — pauper) + -ished → "made poor"
indigent: indig (be in need — indigere) + -ent → "needy"
destitute: de- (away) + stitut (set, placed — statuere) + -e → "set aside, abandoned"
impecunious: im- (without) + pecuni (money — pecus, cattle) + -ous → "without money"
eclectic: ec- (out) + lect (choose) + -ic → "picking out the best"
heterogeneous: hetero (different) + gene (kind) + -ous → "of different kinds"
diverse: di- (apart — dis-) + vers (turn) + -e → "turned different ways"
motley: ~ the multicolored cloth worn by court jesters (origin unclear)
homogeneous: homo (same) + gene (kind) + -ous → "of the same kind"
uniform: uni (one) + form (shape) → "one shape"
monolithic: mono (one) + lith (stone) + -ic → "a single stone"
undifferentiated: un- (not) + differ (carry apart) + -entiated → "not set apart"
chaotic: chao (chaos — the formless void) + -tic → "like chaos"
disorderly: dis- (not) + order + -ly → "out of order"
anarchic: an- (without) + arch (ruler) + -ic → "without a ruler"
haphazard: hap (chance, luck) + hazard (risk — a dice game) → "by chance"
orderly: order + -ly → "in order"
methodical: meth (after — meta) + od (way — hodos) + -ical → "following a way"
systematic: system (an organized whole — Greek sustema, "standing together") + -atic → "by system"
organized: organ (tool, instrument) + -ized → "made into a working instrument"
rigorous: rigor (stiffness) + -ous → "stiff, strict"
exacting: ex- (out) + act (drive — agere) + -ing → "driving out effort"
demanding: de- (completely) + mand (order) + -ing → "ordering"
stringent: string (draw tight — stringere) + -ent → "drawn tight"
draconian: dracon (Draco, an Athenian lawgiver who made almost every crime punishable by death) + -ian → "as harsh as Draco"
harsh: ~ from Middle English harsk, "rough to the touch"
severe: sever (strict, serious — severus) + -e → "strict"
punitive: punit (punish — punire) + -ive → "punishing"
lenient: leni (soft, mild — lenis) + -ent → "softening"
permissive: per- (through) + miss (let go) + -ive → "letting through"
lax: lax (loose — laxus) → "loose"
indulgent: in- (toward) + dulg (be kind — indulgere) + -ent → "giving way kindly"
deferential: de- (away) + fer (carry) + -ential → "yielding one's way to another"
respectful: re- (back) + spect (look) + -ful → "looking back at," regarding
reverent: re- (intensive) + ver (awe — vereri) + -ent → "in awe"
courteous: court (the royal court) + -eous → "with courtly manners"
impudent: im- (not) + pud (shame — pudere) + -ent → "shameless"
insolent: in- (not) + sol (be accustomed — solere) + -ent → "breaking custom"
impertinent: im- (not) + per- (thoroughly) + tin (hold, reach) + -ent → "not pertinent," then "out of line"
cheeky: cheek (insolent talk) + -y → "full of cheek"
jocular: joc (joke — jocus) + -ular → "joking"
waggish: wagg (wag, a joker) + -ish → "like a wag"
droll: ~ from French drôle, "a funny fellow" — perhaps from Dutch drol, "little man"
witty: witt (wit, mind) + -y → "full of wit"
flippant: flipp (flip, flick) + -ant → "flicking things off"
facetious: faceti (jest — facetia) + -ous → "joking"
cavalier: caval (horse — caballus) + -ier → "a horseman" — a swaggering knight
offhand: off + hand → "done off the cuff"
solemn: solemn (ceremonial — sollemnis) → "ceremonial"
grave: grav (heavy) + -e → "heavy, weighty"
earnest: ~ from Old English eornoste, "zeal, seriousness"
sober: sober (not drunk — sobrius) → "clear-headed"
laud: laud (praise — laus) → "praise"
extol: ex- (up) + tol (raise — tollere) → "lift up"
acclaim: ac- (to — ad-) + claim (shout — clamare) → "shout toward"
commend: com- (intensive) + mend (entrust — mandare) → "entrust," recommend
applaud: ap- (to — ad-) + plaud (clap) → "clap at"
castigate: castig (correct — castus, pure) + -ate → "make pure by punishing"
excoriate: ex- (off) + cori (skin — corium) + -ate → "strip the skin off"
berate: be- (thoroughly) + rate (scold) → "scold thoroughly"
lambaste: lam (beat) + baste (thrash) → "beat and thrash"
upbraid: up + braid (reproach — Old English bregdan) → "throw blame up at"
admonish: ad- (to) + mon (warn) + -ish → "warn"
reprove: re- (against) + prove (test — probare) → "disapprove"
chide: ~ from Old English cidan, "to quarrel"
reproach: re- (back) + proach (near — prope) → "bring back near," confront
disparage: dis- (down) + parage (rank, equality — par) → "lower in rank"
denigrate: de- (completely) + nigr (black) + -ate → "blacken"
belittle: be- (make) + little → "make little"
deprecate: de- (away) + prec (pray) + -ate → "pray away," wish against
venerate: vener (worship — venerari) + -ate → "worship"
revere: re- (intensive) + ver (awe) + -e → "stand in awe of"
idolize: idol (image — eidolon) + -ize → "make an idol of"
esteem: esteem (value — aestimare, as in estimate) → "value highly"
placate: plac (calm, please) + -ate → "make calm"
mollify: molli (soft — mollis) + fy (make) → "make soft"
pacify: paci (peace) + fy (make) → "make peaceful"
appease: ap- (to — ad-) + pease (peace — pax) → "bring to peace"
propitiate: propiti (favorable) + -ate → "make favorable"
antagonize: ant (against — anti) + agon (struggle, contest) + -ize → "struggle against"
incense: in- (in) + cens (burn — incendere) + -e → "set on fire"
rile: ~ a variant of roil, "to stir up mud in water"
inflame: in- (in) + flame → "set aflame"
assuage: as- (to — ad-) + suage (sweet — suavis) → "sweeten"
allay: al- (down) + lay → "lay down"
soothe: ~ from Old English sothian, "to show to be true" — later "to humor," then "to calm"
quiet: quiet (rest — quies) → "rest"
alleviate: al- (to — ad-) + levi (light — levis) + -ate → "make lighter"
mitigate: miti (mild — mitis) + gate (make — agere) → "make mild"
palliate: palli (cloak — pallium) + -ate → "cloak the symptoms"
lessen: less + -en → "make less"
exacerbate: ex- (thoroughly) + acerb (harsh, bitter) + -ate → "make more bitter"
`;
