// Word-root breakdowns, part 1 (character, temperament, speech).
// Format: word: part (meaning) + part (meaning) → "literal sense"
//         word: ~ origin story (for words with no useful roots)
// Each part is written as it appears in the word, so the pieces can be checked.

export const ROOTS_1 = String.raw`
obstinate: ob- (against) + stin (stand) + -ate → "standing firm against"
intransigent: in- (not) + trans (across) + ig (drive — agere) + -ent → "not willing to come to terms"
recalcitrant: re- (back) + calcitr (kick — calx, heel) + -ant → "kicking back"
obdurate: ob- (against) + dur (hard) + -ate → "hardened against"
intractable: in- (not) + tract (draw, handle) + -able → "not able to be handled"
pliant: pli (fold, bend) + -ant → "bending easily"
malleable: malle (hammer — malleus) + -able → "able to be hammered into shape"
amenable: a- (to) + men (lead — Old French mener) + -able → "able to be led"
tractable: tract (draw, handle) + -able → "easily handled"
docile: doc (teach) + -ile → "teachable"
compliant: com- (completely) + pli (fill — complere, to fulfill) + -ant → "fulfilling others' wishes"
submissive: sub- (under) + miss (send, put) + -ive → "putting oneself under"
dutiful: duti (duty — what is due) + -ful → "full of duty"
insubordinate: in- (not) + sub- (under) + ordin (order, rank) + -ate → "not keeping one's place in the order"
defiant: de- (away) + fi (trust, faith — fidus) + -ant → "renouncing loyalty"
mutinous: mutin (revolt — Old French mutin, from movere, to move) + -ous → "full of revolt"
refractory: re- (back) + fract (break) + -ory → "breaking back"
tenacious: ten (hold) + -acious (inclined to) → "inclined to hold on"
dogged: dogg (dog) + -ed → "like a dog that won't let go"
resolute: re- (back, again) + solut (loosened, settled — solvere) + -e → "with the matter settled"
indefatigable: in- (not) + de- (completely) + fatig (tire) + -able → "unable to be tired out"
persevering: per- (through) + sever (strict, serious) + -ing → "staying serious all the way through"
steadfast: stead (place) + fast (fixed) → "fixed in place"
staunch: ~ from Old French estanche, "watertight" — like a hull that never leaks, so firmly loyal
unwavering: un- (not) + waver (sway back and forth) + -ing → "not swaying"
constant: con- (firmly) + stant (standing) → "standing firm"
capricious: ~ from Italian capriccio, "a sudden start" (hair standing on end); popularly linked to capra, goat — picture a goat's sudden leaps
mercurial: mercuri (Mercury, the quick, shifty messenger god — also quicksilver) + -al → "like Mercury"
volatile: volat (fly) + -ile → "apt to fly off"
fickle: ~ from Old English ficol, "crafty, deceitful" — someone whose loyalty can't be trusted
erratic: err (wander) + -atic → "wandering"
versatile: vers (turn) + -atile → "turning easily"
protean: prote (Proteus, the sea god who could change his shape) + -an → "shape-shifting"
adaptable: ad- (to) + apt (fit) + -able → "able to be fitted to"
multifaceted: multi- (many) + facet (little face) + -ed → "many-faced"
loquacious: loqu (speak) + -acious (inclined to) → "inclined to talk"
garrulous: garr (chatter — garrire) + -ulous (tending to) → "chattering"
voluble: volu (roll — volvere) + -ble → "words rolling out"
chatty: chatt (chat) + -y → "inclined to chat"
taciturn: tacit (silent) + -urn → "habitually silent"
reticent: re- (intensive) + tic (be silent — tacere) + -ent → "keeping silent"
laconic: lacon (Laconia, home of the Spartans, famous for terse replies) + -ic → "speaking like a Spartan"
uncommunicative: un- (not) + communic (share, make common) + -ative → "not inclined to share"
aloof: a- (on) + loof (windward side of a ship) → "keeping to windward" — steering clear, at a distance
standoffish: stand + off + -ish → "inclined to stand off"
detached: de- (apart) + tach (fasten) + -ed → "unfastened"
remote: re- (back) + mot (moved) + -e → "moved far back"
affable: af- (to — ad-) + fa (speak) + -ble → "easy to speak to"
genial: geni (genius — a festive guardian spirit) + -al → "festive, cheerful"
amiable: ami (friend, love — amicus) + -able → "friendly"
cordial: cordi (heart) + -al → "from the heart"
irascible: irasc (grow angry — ira, anger) + -ible → "easily angered"
choleric: choler (yellow bile, the humor once blamed for anger) + -ic → "full of bile"
cantankerous: ~ origin uncertain — perhaps from Middle English contakour, "troublemaker"; hear "contentious" and "rancorous" in it
testy: test (head — Old French teste) + -y → "headstrong, touchy"
splenetic: splen (spleen, once thought the seat of bad temper) + -etic → "full of spleen"
belligerent: belli (war) + ger (wage) + -ent → "waging war"
bellicose: belli (war) + -cose (full of) → "warlike"
pugnacious: pugn (fight with fists) + -acious (inclined to) → "inclined to fight"
truculent: truc (fierce — trux) + -ulent (full of) → "full of fierceness"
combative: com- (against) + bat (beat) + -ive → "beating against"
conciliatory: concili (bring together — council) + -atory → "bringing together"
placatory: plac (calm, please) + -atory → "tending to calm"
propitiatory: propiti (favorable) + -atory → "making someone favorable again"
pacific: paci (peace) + fic (making) → "peacemaking"
obsequious: ob- (toward) + sequi (follow) + -ous → "following after"
sycophantic: syco (fig) + phant (show) + -ic → "fig-shower" — an Athenian informer, later a flatterer of the powerful
fawning: fawn (show delight, like a dog wagging its tail) + -ing → "acting like an eager dog"
servile: serv (slave — servus) + -ile → "slavish"
unctuous: unctu (oil, ointment — unguere, to anoint) + -ous → "oily"
haughty: haught (high — Old French haut) + -y → "high and mighty"
supercilious: super (above) + cili (eyelid — supercilium, eyebrow) + -ous → "with raised eyebrows"
imperious: imperi (command — imperium) + -ous → "commanding"
condescending: con- (with) + de- (down) + scend (climb) + -ing → "climbing down to someone"
disdainful: dis- (not) + dain (deem worthy — dignari) + -ful → "deeming unworthy"
modest: mod (measure) + -est → "keeping within measure"
unassuming: un- (not) + as- (to — ad-) + sum (take) + -ing → "not taking on airs"
self-effacing: self + ef- (out — ex-) + fac (face) + -ing → "rubbing out one's own face"
humble: hum (ground — humus) + -ble → "close to the ground"
vain: vain (empty — vanus) → "empty" — proud of empty things
conceited: conceit (idea, opinion — conceive) + -ed → "having a high idea of oneself"
narcissistic: narciss (Narcissus, who fell in love with his own reflection) + -istic → "like Narcissus"
egotistical: ego (I — Latin) + -tistical → "all about 'I'"
diffident: dif- (not — dis-) + fid (trust) + -ent → "not trusting oneself"
timid: tim (fear — timere) + -id → "fearful"
timorous: timor (fear) + -ous → "full of fear"
bashful: bash (abash, astonish — Old French esbair) + -ful → "easily abashed"
audacious: aud (dare — audere) + -acious → "inclined to dare"
intrepid: in- (not) + trepid (trembling, alarmed) → "not trembling"
dauntless: daunt (tame, frighten — domitare) + -less → "unable to be frightened"
fearless: fear + -less → "without fear"
pusillanimous: pusill (very small) + anim (spirit, mind) + -ous → "small-spirited"
craven: ~ probably from Old French cravanter, "to crush, overthrow" — like a beaten foe who begs for mercy
spineless: spine + -less → "without a backbone"
cowardly: coward (one who turns tail — Old French coue, tail) + -ly → "tail-between-the-legs"
rash: ~ from Middle Dutch rasch, "quick, hasty" — acting too fast
impetuous: im- (upon) + pet (rush at, seek) + -uous → "rushing upon"
heedless: heed (attention) + -less → "without attention"
foolhardy: fool + hardy (bold — Old French hardi) → "foolishly bold"
circumspect: circum (around) + spect (look) → "looking around"
wary: war (watchful — Old English wær, as in beware) + -y → "on watch"
chary: char (care, sorrow — Old English cearig) + -y → "full of care"
guarded: guard + -ed → "kept under guard"
judicious: judic (judge) + -ious → "having judgment"
sagacious: sag (keen-scented, perceptive — sagax) + -acious → "keen-witted"
prudent: prud (foreseeing — providens) + -ent → "seeing ahead"
sage: sage (wise — sapere, to be wise, to taste) → "wise" — the root of Homo sapiens
astute: astut (crafty — astus, cunning) + -e → "crafty"
shrewd: shrew (once "wicked" — also a scold) + -d → "wicked" became "cunning," then "sharp"
perspicacious: per- (through) + spic (look) + -acious → "seeing through things"
discerning: dis- (apart) + cern (sift, separate) + -ing → "sifting apart"
obtuse: ob- (against) + tus (beaten, blunted — tundere) + -e → "blunted"
dense: dens (thick) + -e → "thick"
slow-witted: slow + witt (wit, mind) + -ed → "slow of mind"
imperceptive: im- (not) + per- (thoroughly) + cept (take, seize) + -ive → "not taking things in"
fatuous: fatu (foolish — fatuus) + -ous → "foolish"
inane: inane (empty — inanis) → "empty-headed"
asinine: asin (ass, donkey — asinus) + -ine → "like a donkey"
puerile: puer (boy, child) + -ile → "childish"
candid: cand (shine white — candere) + -id → "pure, shining white"
forthright: forth (forward) + right (straight) → "straight ahead"
frank: ~ from the Franks — in Frankish Gaul only Franks were fully free, so "frank" meant free, then free in speech
outspoken: out + spoken → "speaking out"
duplicitous: duplic (double — duplex) + -itous → "double-dealing"
mendacious: mend (fault, lie — mendax) + -acious → "inclined to lie"
disingenuous: dis- (not) + ingenu (frank, freeborn — ingenuus) + -ous → "not frank"
deceitful: de- (away) + ceit (take — capere, via deceive) + -ful → "full of taking people in"
wily: wil (wile, trick) + -y → "full of tricks"
crafty: craft (skill, cunning) + -y → "skillful at tricks"
cunning: cunn (know — Old English cunnan, as in can) + -ing → "knowing"
artful: art (skill) + -ful → "full of skill" — clever in a crafty way
ingenuous: ingenu (frank, freeborn — ingenuus) + -ous → "frank, innocent"
artless: art (craft, guile) + -less → "without craft"
guileless: guile (trickery) + -less → "without trickery"
naive: naive (natural — nativus, native) → "in one's natural state" — unworldly
credulous: cred (believe) + -ulous (tending to) → "tending to believe"
gullible: gull (to dupe) + -ible → "easily duped"
trusting: trust + -ing → "giving trust"
skeptical: skept (look, examine — Greek skeptesthai) + -ical → "examining, questioning"
incredulous: in- (not) + cred (believe) + -ulous → "not believing"
dubious: dubi (wavering between two — duo) + -ous → "of two minds"
doubtful: doubt (dubitare — from duo, two) + -ful → "of two minds"
industrious: industri (diligence — industria) + -ous → "full of diligence"
diligent: dilig (value, care for — diligere) + -ent → "caring"
assiduous: as- (at — ad-) + sidu (sit — sedere) + -ous → "sitting at a task"
sedulous: sedul (from se dolo, "without trickery") + -ous → "honestly diligent"
indolent: in- (not) + dol (pain) + -ent → "not taking pains"
slothful: sloth (slowness — slow + -th) + -ful → "full of slowness"
lethargic: leth (forgetting — Lethe, the river of forgetfulness) + arg (idle) + -ic → "forgetful and idle"
torpid: torp (be numb — torpere) + -id → "numb"
sluggish: slugg (slug, sluggard) + -ish → "like a slug"
vivacious: viv (live) + -acious → "full of life"
spirited: spirit (breath, life) + -ed → "full of spirit"
sprightly: spright (sprite, spirit) + -ly → "like a sprite"
animated: anim (breath, soul) + -ated → "given life"
meticulous: metic (fear — metus) + -ulous → "fearful of mistakes"
scrupulous: scrupul (small sharp stone — a worry that pricks the conscience) + -ous → "pricked by every small worry"
punctilious: punctili (fine point — punctum) + -ous → "attentive to fine points"
painstaking: pains + taking → "taking pains"
slapdash: slap + dash → "slapped and dashed on"
slipshod: slip + shod (wearing shoes) → "shuffling in loose slippers"
sloppy: slopp (slop, mud) + -y → "splashy, messy"
careless: care + -less → "without care"
perfunctory: per- (through) + funct (perform) + -ory → "just getting through it"
cursory: curs (run) + -ory → "running over"
superficial: super (above) + fic (face, surface — facies) + -ial → "on the surface"
desultory: de- (from) + sult (leap — salire) + -ory → "leaping from one thing to another," like a circus rider jumping between horses
fastidious: fastidi (disgust — fastidium) + -ous → "easily disgusted"
finicky: finick (fine — overly refined) + -y → "overly fine"
persnickety: ~ from Scots pernickety (origin unknown) — it sounds as fussy as it means
fussy: fuss + -y → "full of fuss"
ebullient: e- (out) + bull (boil, bubble) + -ient → "bubbling over"
exuberant: ex- (thoroughly) + uber (fertile, abundant) + -ant → "overflowing"
buoyant: buoy (float) + -ant → "floating"
jovial: jovi (Jove, or Jupiter — people born under his planet were thought cheerful) + -al → "jolly as Jupiter"
effervescent: ef- (out) + ferv (boil) + -escent (beginning to) → "beginning to bubble over"
melancholy: melan (black) + choly (bile — chole) → "black bile," the humor once blamed for sadness
lugubrious: lugubri (mourning — lugere) + -ous → "mournful"
doleful: dole (grief — dolor) + -ful → "full of grief"
mournful: mourn + -ful → "full of mourning"
somber: ~ from French sombre, probably from Latin sub umbra, "under a shadow"
despondent: de- (away) + spond (pledge, promise) + -ent → "giving up," losing heart
dejected: de- (down) + ject (thrown) + -ed → "thrown down"
disconsolate: dis- (not) + consol (comfort) + -ate → "not to be comforted"
crestfallen: crest + fallen → "with the crest drooping," like a beaten rooster
sanguine: sangu (blood — the cheerful humor) + -ine → "ruddy and hopeful"
optimistic: optim (best) + -istic → "expecting the best"
hopeful: hope + -ful → "full of hope"
upbeat: up + beat → "an upward beat" in music
pessimistic: pessim (worst) + -istic → "expecting the worst"
defeatist: defeat + -ist → "one who accepts defeat"
gloomy: gloom + -y → "full of gloom"
fatalistic: fatal (fate — fatum, "what has been spoken") + -istic → "believing in fate"
imperturbable: im- (not) + per- (thoroughly) + turb (disturb) + -able → "unable to be thrown into disorder"
unflappable: un- (not) + flapp (flap, panic) + -able → "unable to be flustered"
composed: com- (together) + pos (put) + -ed → "put together"
equable: equ (even, equal) + -able → "even, steady"
agitated: agit (drive about, shake — agere) + -ated → "shaken up"
distraught: dis- (apart) + traught (pulled — as in distract) → "pulled apart"
overwrought: over + wrought (worked) → "overworked"
frantic: frant (frenzied — Greek phren, mind) + -ic → "out of one's mind"
placid: plac (calm, please) + -id → "calm"
serene: seren (cloudless — serenus) + -e → "clear and cloudless"
tranquil: tranquil (quiet — tranquillus) → "quiet, still"
halcyon: ~ the halcyon (kingfisher) was said to nest on the sea in winter, when the gods kept the waves calm for fourteen days
tumultuous: tumult (uproar — tumere, to swell) + -uous → "uproarious"
turbulent: turb (disturb, crowd) + -ulent (full of) → "full of disturbance"
tempestuous: tempest (storm) + -uous → "stormy"
stormy: storm + -y → "full of storms"
avid: av (crave — avere) + -id → "craving"
zealous: zeal (fervor — Greek zelos) + -ous → "full of zeal"
ardent: ard (burn — ardere) + -ent → "burning"
fervent: ferv (boil, glow) + -ent → "boiling"
keen: ~ from Old English cene, "bold, brave" — later "sharp," then "eager"
apathetic: a- (without) + path (feeling) + -etic → "without feeling"
indifferent: in- (not) + differ (carry apart, make a difference) + -ent → "seeing no difference"
unconcerned: un- (not) + concern (sift together, relate to) + -ed → "not involved"
blasé: ~ French, "dulled," from blaser, "to sate" — jaded by having had too much
benevolent: bene (well) + vol (wish) + -ent → "wishing well"
compassionate: com- (with) + passion (suffering) + -ate → "suffering with"
humane: human + -e → "showing the best human qualities"
kindly: kind + -ly → "kind"
malevolent: male (bad) + vol (wish) + -ent → "wishing ill"
malicious: mal (bad) + -icious → "full of ill will"
malign: mal (bad) + ign (born — gignere) → "bad by nature"
baleful: bale (evil, misery — Old English bealu) + -ful → "full of evil"
callous: call (hard skin — callus) + -ous → "hardened, thick-skinned"
insensitive: in- (not) + sens (feel) + -itive → "not feeling"
heartless: heart + -less → "without a heart"
hard-hearted: hard + heart + -ed → "with a hard heart"
vindictive: vindict (revenge — vindicta) + -ive → "vengeful"
vengeful: venge (avenge — vindicare) + -ful → "full of revenge"
spiteful: spite (despite, contempt) + -ful → "full of spite"
rancorous: rancor (bitter grudge — rancere, to go rank) + -ous → "rank with resentment"
magnanimous: magn (great) + anim (spirit) + -ous → "great-spirited"
forgiving: for- (completely) + giv (give) + -ing → "giving up resentment"
clement: clement (mild — clemens) → "mild"
merciful: merci (mercy — merces, reward) + -ful → "full of mercy"
munificent: muni (gift — munus) + fic (making) + -ent → "gift-making"
bountiful: bounti (goodness — bonitas) + -ful → "full of goodness"
openhanded: open + hand + -ed → "with an open hand"
lavish: ~ from Old French lavasse, "a downpour" (laver, to wash) — pouring out freely
parsimonious: parsimon (sparing — parcere, to spare) + -ious → "sparing"
miserly: miser (wretched) + -ly → "wretched with money"
tightfisted: tight + fist + -ed → "with a tight fist"
stingy: ~ probably from sting — "nipping, sharp"
frugal: frug (fruit, profit — frux) + -al → "making good use of the harvest"
thrifty: thrift (thriving — thrive) + -y → "good at thriving"
economical: eco (house — oikos) + nom (manage) + -ical → "managing a household"
provident: pro- (ahead) + vid (see) + -ent → "seeing ahead"
profligate: pro- (forward, down) + flig (strike, dash) + -ate → "dashed to ruin"
prodigal: prodig (drive away, squander — prodigere) + -al → "squandering"
spendthrift: spend + thrift (savings) → "spending the savings"
wasteful: waste + -ful → "full of waste"
avaricious: avar (greedy — avarus, from avere, to crave) + -icious → "craving wealth"
rapacious: rap (seize — rapere) + -acious → "inclined to seize"
covetous: covet (desire — cupiditas) + -ous → "desiring what's not yours"
acquisitive: ac- (to — ad-) + quisit (seek, gain — quaerere) + -ive → "seeking to gain"
altruistic: altru (others — altrui, from alter) + -istic → "for others"
selfless: self + -less → "without self"
philanthropic: phil (love) + anthrop (humankind) + -ic → "loving humankind"
charitable: charit (love — caritas) + -able → "loving, giving"
succinct: suc- (under — sub-) + cinct (girded) → "girded up," tucked in tight
pithy: pith (core, essence) + -y → "full of essence"
terse: ters (wiped clean, polished — tergere) + -e → "polished clean"
concise: con- (thoroughly) + cis (cut) + -e → "cut down"
verbose: verb (word) + -ose (full of) → "full of words"
prolix: pro- (forth) + lix (flowing) → "flowing on and on"
long-winded: long + wind (breath) + -ed → "long of breath"
discursive: dis- (apart) + curs (run) + -ive → "running about"
pompous: pomp (procession, display) + -ous → "full of display"
grandiloquent: grandi (grand) + loqu (speak) + -ent → "speaking grandly"
bombastic: bombast (cotton padding) + -ic → "padded out"
turgid: turg (swell — turgere) + -id → "swollen"
eloquent: e- (out) + loqu (speak) + -ent → "speaking out"
articulate: articul (joint, small part — artus) + -ate → "clearly jointed"
fluent: flu (flow) + -ent → "flowing"
silver-tongued: silver + tongue + -d → "with a silver tongue"
inarticulate: in- (not) + articul (jointed) + -ate → "not clearly jointed"
tongue-tied: tongue + tied → "with a tied tongue"
incoherent: in- (not) + co- (together) + her (stick — haerere) + -ent → "not sticking together"
halting: halt (lame — Old English healt) + -ing → "limping"
lucid: luc (light) + -id → "full of light"
pellucid: pel- (through — per-) + luc (light) + -id → "letting light through"
perspicuous: per- (through) + spic (look) + -uous → "able to be seen through"
intelligible: intel- (between — inter-) + lig (choose, read) + -ible → "able to be understood"
abstruse: abs- (away) + trus (thrust — trudere) + -e → "thrust away, hidden"
arcane: arcan (secret — arca, a chest) + -e → "locked in a chest"
recondite: re- (back) + cond (put away, hide) + -ite → "hidden away"
esoteric: eso (within — Greek) + -teric → "for the inner circle"
opaque: opaque (shaded, dark — opacus) → "letting no light through"
ambiguous: ambi (both) + gu (drive — agere) + -ous → "driving both ways"
equivocal: equi (equal) + voc (voice, call) + -al → "speaking equally for both sides"
nebulous: nebul (cloud, mist) + -ous → "cloudy"
vague: vague (wandering — vagus) → "wandering, unfixed"
explicit: ex- (out) + plicit (folded) → "unfolded"
unequivocal: un- (not) + equi (equal) + voc (voice) + -al → "not speaking both ways"
unambiguous: un- (not) + ambi (both) + gu (drive) + -ous → "not going two ways"
categorical: categor (assert — Greek kategorein) + -ical → "asserting outright"
convoluted: con- (together) + volut (rolled) + -ed → "rolled together"
labyrinthine: labyrinth (the maze built for the Minotaur) + -ine → "like a maze"
byzantine: byzant (Byzantium, whose imperial court was famously complex) + -ine → "like Byzantium's bureaucracy"
intricate: in- (in) + tric (perplexities — tricae) + -ate → "entangled"
tortuous: tortu (twisted — torquere) + -ous → "twisting"
straightforward: straight + forward → "going straight ahead"
`;
