// Word-root breakdowns, part 3 (verbs and nouns).

export const ROOTS_3 = String.raw`
aggravate: ag- (to — ad-) + grav (heavy) + -ate → "make heavier"
intensify: intens (stretched — intendere) + ify (make) → "stretch tighter"
compound: com- (together) + pound (put — ponere) → "put together," pile on
impede: im- (in) + ped (foot) + -e → "shackle the feet"
hinder: hind (behind) + -er → "hold behind"
hamper: ~ from Middle English hamperen, "to fetter, restrain"
obstruct: ob- (against) + struct (build) → "build up against"
encumber: en- (in) + cumber (a barrier of felled trees — Old French combre) → "block with a barrier"
thwart: ~ from Old Norse thvert, "across" — to lie across someone's path
foil: ~ from Old French fouler, "to trample" — trampling a trail so the hounds lose the scent
stymie: ~ a golf term: a ball lying between an opponent's ball and the hole, blocking the putt
frustrate: frustr (in vain — frustra) + -ate → "make in vain"
facilitate: facil (easy — facilis) + -itate → "make easy"
expedite: ex- (out) + ped (foot) + -ite → "free the feet"
ease: ease (comfort — Old French aise) → "comfort"
streamline: stream + line → "shaped to flow with the stream"
bolster: bolster (a long pillow) → "prop up with a cushion"
buttress: ~ a support built against an outside wall — from Old French bouter, "to push against"
reinforce: re- (again) + in- (in) + force (strength) → "strengthen again"
fortify: forti (strong) + fy (make) → "make strong"
undermine: under + mine (dig) → "dig under," as attackers tunneled beneath castle walls
erode: e- (away) + rod (gnaw) + -e → "gnaw away"
sap: ~ from sappe, a trench dug beneath a wall — to weaken from underneath (later linked to draining a plant's sap)
weaken: weak + -en → "make weak"
corroborate: cor- (together — com-) + robor (strength — robur, oak) + -ate → "strengthen together"
substantiate: sub- (under) + stant (stand) + -iate → "give a footing underneath"
validate: valid (strong — valere) + -ate → "make sound"
verify: veri (true) + fy (make) → "show to be true"
refute: re- (back) + fut (beat) + -e → "beat back"
rebut: re- (back) + but (push — Old French boter) → "push back"
disprove: dis- (not) + prove → "prove not so"
debunk: de- (remove) + bunk (nonsense — from Buncombe County, whose congressman gave a long, empty speech "for Buncombe") → "remove the nonsense"
renounce: re- (back) + nounc (announce — nuntiare) + -e → "announce one is giving up"
repudiate: re- (away) + pudi (perhaps shame — pudere) + -ate → "put away" — a Roman word for divorcing a spouse
disavow: dis- (not) + avow (declare) → "declare not"
recant: re- (back) + cant (sing — canere) → "sing back," unsay
abjure: ab- (away) + jur (swear) + -e → "swear away"
abrogate: ab- (away) + rog (ask, propose a law — rogare) + -ate → "repeal a law"
rescind: re- (back) + scind (cut) → "cut back"
revoke: re- (back) + vok (call — vocare) + -e → "call back"
annul: an- (to — ad-) + nul (nothing) → "bring to nothing"
authorize: author (originator — auctor) + -ize → "give an author's authority"
permit: per- (through) + mit (send, let go) → "let through"
sanction: sanct (holy, decreed — sancire) + -ion → "a solemn decree"
approve: ap- (to — ad-) + prove (test) → "test and find good"
proscribe: pro- (before, publicly) + scrib (write) + -e → "post in writing," as Rome posted lists of outlaws
prohibit: pro- (in front) + hibit (hold — habere) → "hold back"
forbid: for- (against) + bid (command) → "command against"
outlaw: out + law → "put outside the law"
squander: ~ origin unknown — perhaps from a dialect word meaning "to scatter"
dissipate: dis- (apart) + sip (throw) + -ate → "throw apart, scatter"
waste: waste (empty, desolate — vastus, as in devastate) → "make empty"
conserve: con- (thoroughly) + serv (keep) + -e → "keep safe"
husband: hus (house) + band (dweller — Old Norse bondi) → "householder," who manages its resources carefully
preserve: pre- (before) + serv (keep) + -e → "keep ahead of time"
save: save (make safe — salvare) → "make safe"
defer: de- (apart — Latin dis-, via French) + fer (carry) → "carry apart," set aside for later
postpone: post (after) + pone (put) → "put after"
put off: put + off → "put off till later"
delay: de- (away) + lay (leave — Old French laier) → "leave for later"
accelerate: ac- (to — ad-) + celer (swift) + -ate → "make swift"
hasten: hast (haste) + -en → "make haste"
precipitate: pre- (before) + cipit (head — caput) + -ate → "throw headfirst"
quicken: quick (alive, lively) + -en → "make lively"
procrastinate: pro- (forward) + crastin (tomorrow — cras) + -ate → "put forward to tomorrow"
dawdle: ~ origin unknown — perhaps from daddle, "to toddle"
dally: ~ from Old French dalier, "to chat, amuse oneself"
stall: stall (a stopping place, a stand) → "come to a stop"
vacillate: vacill (sway, totter — vacillare) + -ate → "sway back and forth"
waver: wave (move to and fro) + -r → "keep moving to and fro"
dither: ~ from Middle English didderen, "to tremble"
oscillate: oscill (swing — oscillum, a little mask hung to sway in the wind) + -ate → "swing"
resolve: re- (again) + solv (loosen, settle) + -e → "settle"
determine: de- (off) + termin (boundary) + -e → "set the boundaries"
settle: settle (seat, place — Old English setl) → "set in place"
decide: de- (off) + cid (cut — caedere) + -e → "cut off the other options"
mimic: mim (actor — Greek mimos) + -ic → "acting like"
ape: ape (the animal) → "copy like an ape"
parrot: parrot (the bird) → "repeat like a parrot"
imitate: imit (copy — imitari) + -ate → "copy"
emulate: emul (rival — aemulus) + -ate → "try to rival"
rival: riv (stream — rivus) + -al → "one using the same stream" — neighbors competing for water
equal: equ (even) + -al → "even"
match: ~ from Old English gemæcca, "mate, companion" — an equal partner
disseminate: dis- (apart) + semin (seed) + -ate → "scatter seed"
propagate: pro- (forth) + pag (fasten — pangere, to set slips in the ground) + -ate → "plant shoots forward"
circulate: circul (circle) + -ate → "go around in a circle"
broadcast: broad + cast (throw) → "throw widely," like scattering seed
quash: ~ from Latin quassare, "to shatter," and cassare, "to annul"
quell: ~ from Old English cwellan, "to kill"
stifle: ~ perhaps from Old French estouffer, "to smother"
squelch: ~ imitative — the sound of crushing something soft underfoot
suppress: sup- (under — sub-) + press → "press under"
foment: foment (a warm compress — fovere, to warm) → "keep warm," keep feeding
incite: in- (on) + cit (rouse — citare) + -e → "rouse on"
instigate: in- (on) + stig (prick, goad) + -ate → "goad on"
stir up: stir + up → "stir up"
deceive: de- (away) + ceive (take — capere) → "take in"
dupe: ~ from French dupe, "hoopoe" — a bird thought to be stupid and easy to catch
hoodwink: hood + wink (close the eyes) → "blindfold with a hood"
beguile: be- (thoroughly) + guile (trickery) → "trick thoroughly"
augment: aug (increase — augere) + -ment → "increase"
supplement: sup- (under — sub-) + ple (fill) + -ment → "fill up"
expand: ex- (out) + pand (spread) → "spread out"
boost: ~ American, origin unknown — first meant a shove from below
exaggerate: ex- (thoroughly) + agger (heap) + -ate → "heap up"
overstate: over + state → "state too much"
inflate: in- (into) + flat (blow) + -e → "blow up"
magnify: magni (great) + fy (make) → "make great"
understate: under + state → "state too little"
downplay: down + play → "play down"
minimize: minim (least) + -ize → "make least"
trivialize: trivial (commonplace) + -ize → "make trivial"
curtail: ~ from curtal, a horse with a docked tail (Latin curtus, short) — to cut short
reduce: re- (back) + duc (lead) + -e → "lead back"
scale back: scale + back → "scale back"
trim: ~ from Old English trymman, "to make firm, arrange"
abate: a- (to — ad-) + bat (beat) + -e → "beat down"
wane: ~ from Old English wanian, "to lessen" — as the moon wanes
ebb: ~ from Old English ebba, "the tide flowing back out"
subside: sub- (down) + sid (sit, settle) + -e → "settle down"
dwindle: ~ from Old English dwinan, "to waste away"
diminish: di- (apart — dis-) + min (small) + -ish → "make smaller"
proliferate: proli (offspring — proles) + fer (bear) + -ate → "bear offspring"
burgeon: ~ from Old French burjon, "a bud" — to bud and sprout
mushroom: mushroom (the fungus) → "spring up overnight like mushrooms"
flourish: flour (flower — flos) + -ish → "bloom"
accolades: ac- (to — ad-) + col (neck — collum) + -ades → "an embrace around the neck," part of being knighted
plaudits: plaud (clap) + -its → "applause"
encomiums: en- (in) + com (revel — Greek komos) + -iums → "songs at a celebration"
tributes: tribut (paid, granted — tribuere) + -es → "what is paid"
censure: cens (assess, judge — censere) + -ure → "a judgment against"
opprobrium: op- (against — ob-) + probr (reproach) + -ium → "disgrace"
obloquy: ob- (against) + loqu (speak) + -y → "speaking against"
condemnation: con- (completely) + demn (harm, loss — damnum) + -ation → "declaring guilty"
animosity: anim (spirit) + -osity → "spiritedness" turned hostile
enmity: en (not — in-) + mity (friendship — amicus) → "unfriendship"
antipathy: anti (against) + path (feeling) + -y → "feeling against"
rancor: rancor (rankness — rancere, to stink) → "a grudge gone rank"
animus: animus (mind, spirit — Latin) → "spirit," here a hostile one
amity: ami (friend) + -ty → "friendship"
concord: con- (together) + cord (heart) → "hearts together"
harmony: harmon (fitting together — Greek harmos, joint) + -y → "fitting together"
goodwill: good + will → "good will"
candor: cand (shine white) + -or → "whiteness, purity"
frankness: frank (free) + -ness → "freeness of speech"
forthrightness: forth + right + -ness → "going straight ahead"
openness: open + -ness → "being open"
probity: prob (good, honest — probus) + -ity → "goodness"
integrity: integr (whole, untouched — integer) + -ity → "wholeness"
rectitude: recti (straight, right) + -tude → "straightness"
uprightness: up + right + -ness → "standing straight"
duplicity: duplic (double) + -ity → "doubleness"
deceit: de- (away) + ceit (take — capere) → "taking people in"
mendacity: mend (lie, fault) + -acity → "lying"
chicanery: ~ from French chicaner, "to quibble" — legal trickery
guile: ~ from Old French guile, "deceit" (a cousin of wile)
prowess: prow (brave — Old French prou) + -ess → "bravery"
dexterity: dexter (right hand) + -ity → "right-handedness"
adroitness: a- (to) + droit (right — French) + -ness → "rightness, skill"
finesse: fin (fine) + -esse → "fineness"
acumen: acu (sharpen — acuere) + -men → "sharpness"
discernment: dis- (apart) + cern (sift) + -ment → "sifting apart"
perspicacity: per- (through) + spic (look) + -acity → "seeing through"
sagacity: sag (keen-scented — sagax) + -acity → "keenness"
ineptitude: in- (not) + ept (fit — aptus) + -itude → "unfitness"
incompetence: in- (not) + com- (together) + pet (seek, be fit — petere) + -ence → "not fit for the task"
clumsiness: clums (numb with cold — Middle English clumsen) + -iness → "stiff and numb"
ineptness: in- (not) + ept (fit) + -ness → "unfitness"
surfeit: sur- (over) + feit (done — facere) → "overdone"
glut: ~ from Old French gloutir, "to swallow" (as in gluttony)
plethora: pleth (fullness — Greek plethos) + -ora → "overfullness"
superfluity: super (over) + flu (flow) + -ity → "overflowing"
dearth: dear (costly) + -th → "dearness" — when food was scarce it was dear
paucity: pauc (few — paucus) + -ity → "fewness"
scarcity: scarc (scarce) + -ity → "scarceness"
shortage: short + -age → "falling short"
zenith: ~ from Arabic samt ar-ra's, "the path over the head" — the point straight overhead
apex: apex (tip, summit — Latin) → "tip"
pinnacle: pinna (feather, point) + -cle (little) → "a little point" — a slender peak
acme: acme (point, peak — Greek akme) → "the peak"
nadir: ~ from Arabic nazir as-samt, "opposite the zenith" — the point straight below
low point: low + point → "the low point"
bottom: bottom (the lowest part — Old English botm) → "the lowest part"
lowest ebb: lowest + ebb (the tide at its lowest) → "the tide at its lowest"
inception: in- (in) + cept (take) + -ion → "taking in hand"
outset: out + set → "setting out"
start: ~ from Old English styrtan, "to leap up"
beginning: begin + -ning → "beginning"
equanimity: equ (even) + anim (mind) + -ity → "an even mind"
composure: com- (together) + pos (put) + -ure → "being put together"
poise: ~ from Old French pois, "weight" — weight in balance, steadiness
aplomb: a (to — French à) + plomb (lead weight, plumb line) → "upright as a plumb line"
sangfroid: sang (blood) + froid (cold) → "cold blood"
agitation: agit (shake, drive) + -ation → "being shaken up"
turmoil: ~ origin unknown — perhaps turn + moil, "to churn"
perturbation: per- (thoroughly) + turb (disturb) + -ation → "thorough disturbance"
disquiet: dis- (not) + quiet → "lack of quiet"
temerity: temer (rashly, blindly — temere) + -ity → "rashness"
effrontery: ef- (out — ex-) + front (forehead, face) + -ery → "barefaced cheek"
audacity: aud (dare) + -acity → "daring"
gall: gall (bile) → "bitterness" — and the brazen nerve to go with it
diffidence: dif- (not) + fid (trust) + -ence → "not trusting oneself"
timidity: tim (fear) + -idity → "fearfulness"
bashfulness: bash (abash) + -fulness → "being abashed"
shyness: shy + -ness → "being shy"
trepidation: trepid (trembling) + -ation → "trembling"
apprehension: ap- (to — ad-) + prehens (seize, grasp) + -ion → "the mind seizing on danger ahead"
dread: ~ from Old English ondrædan, "to fear"
foreboding: fore (before) + bod (announce — bode) + -ing → "announcing beforehand"
zeal: zeal (fervor — Greek zelos) → "fervor"
fervor: ferv (boil) + -or → "boiling"
ardor: ard (burn) + -or → "burning"
enthusiasm: en- (in) + thusi (god — theos) + -asm → "having a god within"
apathy: a- (without) + path (feeling) + -y → "without feeling"
indifference: in- (not) + differ (make a difference) + -ence → "seeing no difference"
unconcern: un- (not) + concern → "not concerned"
nonchalance: non- (not) + chal (be hot — calere) + -ance → "not heated up"
lethargy: leth (forgetting) + arg (idle) + -y → "forgetful idleness"
torpor: torp (numb) + -or → "numbness"
lassitude: lass (weary — lassus) + -itude → "weariness"
languor: langu (be faint — languere) + -or → "faintness"
vigor: vig (be lively — vigere) + -or → "liveliness"
vitality: vit (life) + -ality → "liveliness"
verve: ~ from French verve, "vivacity" — from Latin verba, words: a lively way with words
zest: ~ from French zeste, the outer peel of a lemon or orange — a burst of flavor
`;
