import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'numeric',
    id: 'gre-pct-of',
    lessonId: 'gre-percents',
    difficulty: 1,
    prompt: '18 is what percent of 24?',
    answer: 75,
    answerDisplay: '75',
    suffix: '%',
    explanation: 'Part ÷ whole × 100: 18 ÷ 24 × 100 = **75%**. The whole is the number after “of.”',
  },
  {
    kind: 'mcq',
    id: 'gre-pct-successive',
    lessonId: 'gre-percents',
    difficulty: 2,
    prompt: 'A stock’s price increased by 50% in one year and decreased by 40% the next. The final price is what percent of the original price?',
    options: ['80%', '90%', '100%', '110%', '120%'],
    correctIndex: 1,
    explanation: 'Multiply the factors: 1.5 × 0.6 = 0.9 → **90%** of the original, a 10% loss overall.',
    distractorNotes: [
      'Arithmetic slip.',
      'Correct.',
      'Assumes the changes cancel.',
      'Adds +50 and −40 — percents taken of different bases don’t add.',
      'Not a valid combination.',
    ],
  },
  {
    kind: 'numeric',
    id: 'gre-pct-reverse',
    lessonId: 'gre-percents',
    difficulty: 2,
    prompt: 'Including an 8% sales tax, a purchase cost $64.80. What was the price before tax, in dollars?',
    answer: 60,
    answerDisplay: '60',
    prefix: '$',
    explanation: 'Total = 1.08 × price → price = 64.80 ÷ 1.08 = **$60**. Subtracting 8% of $64.80 would give $59.62 — wrong, because the tax was 8% of the smaller, pre-tax price.',
  },
  {
    kind: 'mcq',
    id: 'gre-pct-interest',
    lessonId: 'gre-percents',
    difficulty: 2,
    prompt: '$2,000 is invested at 10% annual interest, compounded annually. How much more interest does it earn in 3 years than it would at 10% simple interest?',
    options: ['$0', '$20', '$62', '$600', '$662'],
    correctIndex: 2,
    explanation: 'Compound: 2,000 × 1.1³ = $2,662, so $662 interest. Simple: 2,000 × 0.10 × 3 = $600. Difference: **$62**.',
    distractorNotes: [
      'Compounding always adds something after the first year.',
      'That is the extra after 2 years ($2,420 vs. $2,400).',
      'Correct.',
      'That is the simple interest.',
      'That is the compound interest itself, not the difference.',
    ],
  },
];
