import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'mcq',
    id: 'gre-tac-plug',
    lessonId: 'gre-quant-tactics',
    difficulty: 2,
    prompt: 'If a car travels m miles in h hours, how many minutes does it take to travel 1 mile at the same rate?',
    options: ['m/h', 'h/m', '60h/m', '60m/h', 'hm/60'],
    correctIndex: 2,
    explanation: 'Plug in: m = 30 miles in h = 1 hour → 30 mph → 1 mile takes 2 minutes. Test: m/h = 30 ✗, h/m = 1/30 ✗, 60h/m = 60/30 = 2 ✓, 60m/h = 1,800 ✗, hm/60 = 0.5 ✗. Answer **60h/m**.',
    distractorNotes: [
      'That is the speed in miles per hour.',
      'That is hours per mile — not minutes.',
      'Correct.',
      'Upside down — gives miles per minute × 3,600.',
      'Not a meaningful rate.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-tac-estimate',
    lessonId: 'gre-quant-tactics',
    difficulty: 1,
    prompt: 'Which of the following is closest to (39.8 × 5.02) / 0.198?',
    options: ['10', '100', '1,000', '10,000', '100,000'],
    correctIndex: 2,
    explanation: 'Round: (40 × 5) / 0.2 = 200 / 0.2 = 1,000. The choices are powers of ten apart, so estimation is all you need.',
    distractorNotes: ['Off by a factor of 100.', 'Forgot that dividing by 0.2 multiplies by 5.', 'Correct.', 'Off by a factor of 10.', 'Off by a factor of 100.'],
  },
  {
    kind: 'multi',
    id: 'gre-tac-multi',
    lessonId: 'gre-quant-tactics',
    difficulty: 2,
    prompt: 'If 3 < 2x − 1 < 11, which of the following could be the value of x?\n\nIndicate all such values.',
    options: ['1', '2', '3.5', '5', '6'],
    correctIndices: [2, 3],
    explanation: 'Solve once instead of testing each choice: add 1 → 4 < 2x < 12 → 2 < x < 6. Only 3.5 and 5 are strictly between 2 and 6.',
    distractorNotes: ['✗ below 2.', '✗ x = 2 gives 2x − 1 = 3, which is not greater than 3.', '✓ inside (2, 6).', '✓ inside (2, 6).', '✗ x = 6 gives 11, which is not less than 11.'],
  },
  {
    kind: 'mcq',
    id: 'gre-tac-question',
    lessonId: 'gre-quant-tactics',
    difficulty: 2,
    prompt: 'The length of a rectangle is 3 more than its width, and its area is 40. What is its perimeter?',
    options: ['5', '8', '13', '26', '40'],
    correctIndex: 3,
    explanation: 'Width w: w(w + 3) = 40 → w = 5, length 8. Perimeter = 2(5 + 8) = **26**. The traps are the width (5), the length (8), and their sum (13) — each the answer to a different question.',
    distractorNotes: ['The width.', 'The length.', 'Length + width — half the perimeter.', 'Correct.', 'The area.'],
  },
];
