import type { ModuleMeta } from './types';

// The 12-module curriculum (spec §6). Pure data — safe on client and server.
export const MODULES: ModuleMeta[] = [
  {
    slug: 'complexity',
    courseId: 'dsa',
    number: 1,
    title: 'Complexity',
    blurb: 'Big-O, Θ, Ω · amortized analysis · space complexity · recursion trees + Master theorem',
    anchors: ['Why an O(n²) autocomplete dies at 10k contacts'],
  },
  {
    slug: 'arrays',
    courseId: 'dsa',
    number: 2,
    title: 'Arrays and dynamic arrays',
    blurb: 'Static vs dynamic · amortized doubling · two pointers · sliding window · prefix sums',
    anchors: ['Python list internals', 'Image convolution as a sliding window'],
  },
  {
    slug: 'hashing',
    courseId: 'dsa',
    number: 3,
    title: 'Hashing',
    blurb: 'Hash functions · collisions (chaining vs open addressing) · load factor · when dict is not O(1)',
    anchors: ['Database indexes', 'Deduping event streams', 'DNS caching'],
  },
  {
    slug: 'linked-structures',
    courseId: 'dsa',
    number: 4,
    title: 'Linked structures',
    blurb: 'Singly/doubly linked · fast–slow pointers · LRU cache',
    anchors: ['Browser history (doubly linked)', 'LRU in a CDN edge cache'],
  },
  {
    slug: 'stacks',
    courseId: 'dsa',
    number: 5,
    title: 'Stacks',
    blurb: 'Array vs linked backing · monotonic stack · the call stack',
    anchors: ['The call stack itself', 'Undo/redo', 'Expression parsing in a compiler'],
  },
  {
    slug: 'queues',
    courseId: 'dsa',
    number: 6,
    title: 'Queues and deques',
    blurb: 'FIFO · ring buffer · deque · priority queue preview',
    anchors: ['Gmail send → SMTP worker queue', 'Kafka', 'Print spoolers', 'BFS frontier'],
  },
  {
    slug: 'heaps',
    courseId: 'dsa',
    number: 7,
    title: 'Heaps and priority queues',
    blurb: 'Binary heap · sift up/down · heapify · two-heap median · top-K',
    anchors: ['OS process scheduler', 'Uber dispatch', 'k-nearest results in a search ranker'],
  },
  {
    slug: 'trees',
    courseId: 'dsa',
    number: 8,
    title: 'Trees',
    blurb: 'Binary trees · traversals · BST · balancing (conceptual) · tries',
    anchors: ['Filesystem', 'DOM', 'Autocomplete tries', 'B-trees under every SQL index'],
  },
  {
    slug: 'graphs',
    courseId: 'dsa',
    number: 9,
    title: 'Graphs',
    blurb: 'Representations · BFS/DFS · topological sort · union-find · Dijkstra',
    anchors: ['Social graphs', 'Build dependency ordering (npm, Make)', 'Maps routing'],
  },
  {
    slug: 'sorting',
    courseId: 'dsa',
    number: 10,
    title: 'Sorting',
    blurb: 'Merge · quick (Lomuto + Hoare) · heap · counting/radix · Timsort · stability',
    anchors: ['Stable ORDER BY', 'Leaderboard sorting', 'External sort on files too big for RAM'],
  },
  {
    slug: 'searching',
    courseId: 'dsa',
    number: 11,
    title: 'Searching',
    blurb: 'Binary search · bisect from scratch · binary search on the answer · quickselect',
    anchors: ['Git bisect', 'Rate-limit threshold tuning', 'Percentile queries'],
  },
  {
    slug: 'dp',
    courseId: 'dsa',
    number: 12,
    title: 'Recursion, backtracking, DP, greedy',
    blurb: 'Memo → tabulate → space-optimize · knapsack/LIS/edit distance · when greedy is provably safe',
    anchors: ['Diff algorithms (edit distance)', 'Autocomplete ranking', 'Cache eviction heuristics'],
  },

  // ----- Large language models -------------------------------------------
  {
    slug: 'tokenization',
    courseId: 'llm',
    number: 1,
    title: 'Foundations & tokenization',
    blurb: 'What an LLM actually is (next-token prediction) · training vs inference · bytes → tokens · BPE merges · vocab & context windows',
    anchors: ['“It’s just autocomplete” — and why that’s the whole story', 'Why an LLM miscounts the r’s in “strawberry”', 'The token bill'],
  },
  {
    slug: 'embeddings',
    courseId: 'llm',
    number: 2,
    title: 'Embeddings & vector search',
    blurb: 'Vectors as meaning · cosine similarity · chunking · vector DBs · approximate nearest neighbors (HNSW)',
    anchors: ['Semantic search', 'Dedup & clustering', 'The retrieval half of RAG'],
  },
  {
    slug: 'attention',
    courseId: 'llm',
    number: 3,
    title: 'Attention & transformers',
    blurb: 'Self-attention · Q/K/V · multi-head · positional encoding · the block · the KV cache',
    anchors: ['Why context length is quadratic', 'What the KV cache actually caches'],
  },
  {
    slug: 'decoding',
    courseId: 'llm',
    number: 4,
    title: 'Sampling & decoding',
    blurb: 'Logits → probabilities · temperature · top-k / top-p · greedy vs sampling · why it’s confidently wrong',
    anchors: ['The temperature knob', 'Structured/JSON decoding', 'Reproducibility vs creativity'],
  },
  {
    slug: 'prompting',
    courseId: 'llm',
    number: 5,
    title: 'Prompting',
    blurb: 'Zero/few-shot · system vs user · chain-of-thought · structured output · prompt injection',
    anchors: ['The system prompt', 'Few-shot as runtime programming', 'This app’s own tutor prompt'],
  },
  {
    slug: 'rag',
    courseId: 'llm',
    number: 6,
    title: 'Retrieval-augmented generation',
    blurb: 'Chunk → embed → retrieve → rerank → stuff → generate · failure modes · hybrid search · grounding',
    anchors: ['Docs Q&A', 'Lost-in-the-middle', 'Grounding to cut hallucination'],
  },
  {
    slug: 'tools',
    courseId: 'llm',
    number: 7,
    title: 'Tool use & function calling',
    blurb: 'Tool schemas · the call loop · JSON mode · parallel tools · grounding actions in the world',
    anchors: ['The weather/DB tool', 'Structured outputs as an API', 'Letting the model take actions'],
  },
  {
    slug: 'agents',
    courseId: 'llm',
    number: 8,
    title: 'Agents',
    blurb: 'The perceive→decide→act loop · ReAct · memory · planning · when an agent beats a fixed chain',
    anchors: ['A coding agent', 'The task loop', 'Autonomy vs control'],
  },
  {
    slug: 'agentic-workflows',
    courseId: 'llm',
    number: 9,
    title: 'Agentic workflows',
    blurb: 'Chaining · routing · parallelization · orchestrator-worker · evaluator-optimizer · reflection · multi-agent',
    anchors: ['Workflows vs agents (Anthropic’s split)', 'Orchestrator-worker', 'When determinism wins'],
  },
  {
    slug: 'evaluation',
    courseId: 'llm',
    number: 10,
    title: 'Evaluation',
    blurb: 'Offline vs online · LLM-as-judge · golden sets · RAG metrics · regression · cost & latency',
    anchors: ['“How do you know it got better?”', 'LLM-as-judge pitfalls', 'Faithfulness & context recall'],
  },
  {
    slug: 'fine-tuning',
    courseId: 'llm',
    number: 11,
    title: 'Fine-tuning & adaptation',
    blurb: 'When NOT to · SFT · LoRA/PEFT · RLHF/DPO (conceptual) · distillation · data curation',
    anchors: ['Style/format adaptation', 'LoRA’s low-rank trick', 'Prompt vs fine-tune vs RAG'],
  },
  {
    slug: 'inference',
    courseId: 'llm',
    number: 12,
    title: 'Inference & serving',
    blurb: 'Latency vs throughput · KV cache · continuous batching · quantization · context cost · streaming',
    anchors: ['The token bill, again', 'Time-to-first-token', 'Quantization tradeoffs'],
  },

  // ----- Cracking LeetCode ------------------------------------------------
  {
    slug: 'lc-method',
    courseId: 'leetcode',
    number: 1,
    title: 'The problem-solving method',
    blurb: 'UMPIRE · brute-force first · think out loud · test your own code · the anti-panic loop · meet the built-in editor',
    anchors: ['Why you freeze — and the checklist that stops it', 'Brute force is a valid first answer'],
  },
  {
    slug: 'lc-constraints',
    courseId: 'leetcode',
    number: 2,
    title: 'Reading the constraints',
    blurb: 'Input size → target complexity · the number that tells you the algorithm · when O(n²) is fine and when it dies',
    anchors: ['n ≤ 20 means exponential is allowed', 'n ≤ 10⁵ means O(n log n)'],
  },
  {
    slug: 'lc-two-pointers',
    courseId: 'leetcode',
    number: 3,
    title: 'Two pointers',
    blurb: 'Opposite ends · same direction · partitioning · the sorted-input tell',
    anchors: ['Two-sum on a sorted array', 'Container with most water', 'Valid palindrome'],
  },
  {
    slug: 'lc-sliding-window',
    courseId: 'leetcode',
    number: 4,
    title: 'Sliding window',
    blurb: 'Fixed vs variable window · grow-then-shrink · the “longest/shortest substring” family',
    anchors: ['Longest substring without repeats', 'Minimum window substring (Hard)'],
  },
  {
    slug: 'lc-hashing',
    courseId: 'leetcode',
    number: 5,
    title: 'Hashing & the “seen” trick',
    blurb: 'Set/dict for O(1) lookup · complement search · frequency maps · prefix-sum + hashmap',
    anchors: ['Two Sum', 'Group anagrams', 'Subarray sum equals k'],
  },
  {
    slug: 'lc-binary-search',
    courseId: 'leetcode',
    number: 6,
    title: 'Binary search',
    blurb: 'The bug-free template · rotated arrays · binary search on the answer',
    anchors: ['Search in rotated sorted array', 'Koko eating bananas', 'Find min in rotated'],
  },
  {
    slug: 'lc-stacks',
    courseId: 'leetcode',
    number: 7,
    title: 'Stacks & monotonic stacks',
    blurb: 'Matching/parsing · the monotonic-stack pattern for “next greater” problems',
    anchors: ['Valid parentheses', 'Daily temperatures', 'Largest rectangle in histogram (Hard)'],
  },
  {
    slug: 'lc-linked-list',
    courseId: 'leetcode',
    number: 8,
    title: 'Linked-list techniques',
    blurb: 'Dummy head · in-place reversal · fast/slow pointers · merge',
    anchors: ['Reverse a linked list', 'Detect a cycle', 'Merge two sorted lists'],
  },
  {
    slug: 'lc-trees',
    courseId: 'leetcode',
    number: 9,
    title: 'Trees: DFS & BFS templates',
    blurb: 'Recursive DFS · the “return info up” pattern · level-order BFS',
    anchors: ['Max depth', 'Level-order traversal', 'Lowest common ancestor'],
  },
  {
    slug: 'lc-heaps',
    courseId: 'leetcode',
    number: 10,
    title: 'Heaps & top-K',
    blurb: 'When “the k best” means a heap · merge-k pattern · the min-heap-for-top-K trick',
    anchors: ['Kth largest element', 'Merge k sorted lists (Hard)', 'Top k frequent'],
  },
  {
    slug: 'lc-backtracking',
    courseId: 'leetcode',
    number: 11,
    title: 'Backtracking',
    blurb: 'The choose → explore → un-choose template · subsets/permutations/combinations · pruning',
    anchors: ['Subsets & permutations', 'Combination sum', 'Word search', 'N-Queens (Hard)'],
  },
  {
    slug: 'lc-graphs',
    courseId: 'leetcode',
    number: 12,
    title: 'Graphs for interviews',
    blurb: 'Grid-as-graph · BFS shortest path · topological sort · union-find',
    anchors: ['Number of islands', 'Course schedule (topo sort)', 'Rotting oranges'],
  },
  {
    slug: 'lc-dp-1d',
    courseId: 'leetcode',
    number: 13,
    title: 'Dynamic programming I — 1D',
    blurb: 'State + transition · memoize → tabulate → space-optimize · the “decision at each step” shape',
    anchors: ['Climbing stairs', 'House robber', 'Coin change', 'Longest increasing subsequence'],
  },
  {
    slug: 'lc-dp-2d',
    courseId: 'leetcode',
    number: 14,
    title: 'Dynamic programming II — 2D & sequences',
    blurb: 'Grid DP · two-sequence DP · the Hard tier: edit distance, LCS, knapsack',
    anchors: ['Unique paths', 'Longest common subsequence', 'Edit distance (Hard)'],
  },
  {
    slug: 'lc-hard',
    courseId: 'leetcode',
    number: 15,
    title: 'Composing patterns: cracking Hard',
    blurb: 'A Hard problem is 2–3 known patterns stacked · three full walkthroughs · the confidence capstone',
    anchors: ['Trapping rain water (three ways)', 'Median of two sorted arrays', 'Word ladder'],
  },
];

export const getModule = (slug: string): ModuleMeta | undefined =>
  MODULES.find((m) => m.slug === slug);

export const getModulesForCourse = (courseId: string): ModuleMeta[] =>
  MODULES.filter((m) => m.courseId === courseId);

/** Client-safe module slug → courseId lookup (used to scope nav/practice). */
export const MODULE_COURSE: Record<string, string> = Object.fromEntries(
  MODULES.map((m) => [m.slug, m.courseId]),
);
