import type { CheatsheetData } from '@/lib/types';

// One cheatsheet per GRE lesson: the night-before quick reference. Each uses
// GRE-appropriate headers and labels. Aggregated in content/cheatsheets.ts.

const H: [string, string, string] = ['Idea', 'Rule / fact', 'Example'];
const L = { useWhenLabel: 'Spot it when', dontUseWhenLabel: 'Watch out for', stdlibLabel: 'Drill it' } as const;

export const GRE_CHEATSHEETS: CheatsheetData[] = [
  {
    lessonId: 'gre-overview',
    opsHeaders: ['Part', 'Format', 'Note'],
    opsTable: [
      { op: 'Analytical Writing', complexity: '1 Issue essay, 30 min', note: 'first; scored 0–6' },
      { op: 'Verbal', complexity: '12 Q / 18 min + 15 Q / 23 min', note: 'scored 130–170' },
      { op: 'Quant', complexity: '12 Q / 21 min + 15 Q / 26 min', note: 'scored 130–170; calculator' },
      { op: 'Adaptivity', complexity: 'section-level', note: 'section 1 sets section 2’s difficulty' },
      { op: 'Wrong answers', complexity: 'no penalty', note: 'never leave a blank' },
    ],
    ...L,
    useWhen: 'Planning your approach to any section: bank time on easy questions, mark hard ones, answer everything.',
    dontUseWhen: 'Spending more than ~2½ minutes on one question with no plan — mark it, guess, move on.',
    stdlib: 'Timed sections in the practice bank run at real GRE pace',
    bullets: [
      'Total time is about 1 hour 58 minutes.',
      'You can skip, mark, return, and change answers within a section.',
      'A harder second section usually means the first went well.',
    ],
    gotchas: ['The on-screen calculator is slow — use it only for arithmetic you have already set up.'],
  },
  {
    lessonId: 'gre-study-plan',
    opsHeaders: ['Tool', 'What it is for', 'When'],
    opsTable: [
      { op: 'Lessons', complexity: 'learn one method each', note: 'weeks 1–7, in course order' },
      { op: 'Checks', complexity: 'confirm you have it', note: 'inside every lesson' },
      { op: 'Numbered sets', complexity: 'mixed practice, Foundation → Advanced', note: '1 quant + 1 verbal daily' },
      { op: 'Timed sets', complexity: 'pacing', note: 'from week 4' },
      { op: 'Review queue', complexity: 'every miss comes back', note: 'daily, first thing' },
    ],
    ...L,
    useWhen: 'Deciding what to do today: review queue → next lesson in order → the day’s sets.',
    dontUseWhen: 'Skipping review or timed practice to “save time” — those two convert understanding into points.',
    stdlib: 'Practice bank → Numbered sets (next set highlighted)',
    bullets: ['About 1½–2 hours a day, six days a week, for 8 weeks.', 'Official ETS POWERPREP practice tests in weeks 7–8.', 'Move up a tier when sets feel easy (85%+).'],
    gotchas: ['Read the note under every choice, even on questions you got right.'],
  },
  {
    lessonId: 'gre-vocab-method',
    opsHeaders: H,
    opsTable: [
      { op: 'Word families', complexity: 'learn synonyms together', note: 'obstinate · intransigent · obdurate' },
      { op: 'Opposite family', complexity: 'learn it alongside', note: 'stubborn ↔ pliant, amenable' },
      { op: 'Roots', complexity: 'decode unknown words', note: 'mal- bad, bene- good, loqu- speak' },
      { op: 'Charge', complexity: 'positive or negative?', note: 'pernicious “sounds” bad — and is' },
      { op: 'Second meanings', complexity: 'easy word, rare sense', note: 'qualify = limit; temper = moderate' },
    ],
    ...L,
    useWhen: 'You half-know a word: its family and charge are often enough to answer.',
    dontUseWhen: 'A simple word in a hard sentence — check whether a second meaning fits.',
    stdlib: 'Vocab drills: meaning · definition · synonyms · antonyms',
    bullets: ['20 new words a day, one or two families at a time.', 'Say each word in a sentence of your own.', 'Let the review queue handle repetition.'],
    gotchas: ['Alphabetical lists are the least effective way to learn words.'],
  },
  {
    lessonId: 'gre-vocab-core',
    opsHeaders: ['Family', 'Members', 'Opposite family'],
    opsTable: [
      { op: 'stubborn', complexity: 'obstinate, intransigent, recalcitrant, obdurate', note: 'pliant, malleable, amenable' },
      { op: 'praise', complexity: 'laud, extol, acclaim, commend', note: 'castigate, excoriate, berate' },
      { op: 'short-lived', complexity: 'ephemeral, evanescent, transient', note: 'enduring, abiding, perennial' },
      { op: 'harmful', complexity: 'deleterious, pernicious, noxious', note: 'salutary, salubrious, beneficial' },
      { op: 'saying little', complexity: 'taciturn, reticent, laconic', note: 'loquacious, garrulous, voluble' },
      { op: 'hard to understand', complexity: 'abstruse, arcane, recondite', note: 'lucid, pellucid, perspicuous' },
    ],
    ...L,
    useWhen: 'Sentence equivalence: the answer is two members of one family that fit the clue.',
    dontUseWhen: 'A second matching pair from the opposite family — it matches, but doesn’t fit.',
    stdlib: 'Topic drills → Vocab (four kinds)',
    bullets: ['About 760 words in 184 families.', 'Adjectives first — they dominate completions.'],
    gotchas: ['Knowing one word in a family is not knowing the family — learn every member.'],
  },
  {
    lessonId: 'gre-integers',
    opsHeaders: H,
    opsTable: [
      { op: 'Number of divisors', complexity: '(a+1)(b+1)(c+1)', note: '360 = 2³·3²·5 → 24' },
      { op: 'GCD', complexity: 'shared primes, lowest powers', note: 'gcd(24, 36) = 12' },
      { op: 'LCM', complexity: 'all primes, highest powers', note: 'lcm(12, 18) = 36' },
      { op: 'GCD × LCM', complexity: '= product of the two numbers', note: '12 × 72 = 24 × 36' },
      { op: 'Remainders', complexity: 'pick n = the remainder', note: 'n ÷ 7 rem 3 → try n = 3' },
      { op: 'Consecutive integers', complexity: 'average = middle = sum ÷ count', note: '7 terms sum 98 → middle 14' },
    ],
    ...L,
    useWhen: 'Any factor, multiple, divisor, or remainder question — prime-factorize first.',
    dontUseWhen: 'Testing only positive integers on “must be” questions — try negatives and fractions.',
    stdlib: 'Counting factors · GCD & LCM · Remainders · Odd/even & sign rules · Primes',
    bullets: ['1 is not prime; 2 is the only even prime.', 'Product negative ⇔ odd number of negative factors.'],
    gotchas: ['Forgetting the +1 in the divisor formula (exponent 0 is a choice).'],
  },
  {
    lessonId: 'gre-exponents-roots',
    opsHeaders: H,
    opsTable: [
      { op: 'Multiply', complexity: 'add exponents', note: 'x³·x⁴ = x⁷' },
      { op: 'Power of a power', complexity: 'multiply exponents', note: '(x³)⁴ = x¹²' },
      { op: 'Negative exponent', complexity: 'reciprocal', note: '2⁻³ = 1/8' },
      { op: 'Common base', complexity: 'rewrite, then equate exponents', note: '4ˣ = 8 → 2²ˣ = 2³' },
      { op: 'Simplify √', complexity: 'pull out perfect squares', note: '√72 = 6√2' },
      { op: 'Units digit', complexity: 'cycles of length 1, 2, or 4', note: '7: 7, 9, 3, 1' },
    ],
    ...L,
    useWhen: 'Different bases that are powers of the same prime (4, 8, 16, 32 → 2).',
    dontUseWhen: 'Sums: (a + b)² ≠ a² + b² and √(a + b) ≠ √a + √b.',
    stdlib: 'Exponent rules · Solving exponential equations · Roots & radicals · Units digits',
    bullets: ['Between 0 and 1: powers shrink, roots grow.', 'k copies of kⁿ = kⁿ⁺¹.'],
    gotchas: ['3¹² + 3¹² + 3¹² = 3¹³, not 3³⁶.'],
  },
  {
    lessonId: 'gre-fractions-decimals',
    opsHeaders: H,
    opsTable: [
      { op: 'Add / subtract', complexity: 'common denominator', note: '⅔ + ¾ = 17/12' },
      { op: 'Divide', complexity: 'multiply by reciprocal', note: '⅔ ÷ ¾ = 8/9' },
      { op: 'Compare', complexity: 'cross-multiply', note: '5/8 vs 7/11: 55 < 56' },
      { op: 'Fraction of remainder', complexity: 'multiply what’s left', note: '⅔ × ¾ = ½ remains' },
      { op: 'Scientific notation', complexity: 'coefficient in [1, 10)', note: '24 × 10⁸ = 2.4 × 10⁹' },
    ],
    ...L,
    useWhen: '“Of the remainder” — track what remains at each step, then work backward.',
    dontUseWhen: 'Close values in a “which is least” question — convert to 3 decimal places.',
    stdlib: 'Fraction arithmetic · Comparing fractions & decimals · Fractions of a remainder · Scientific notation',
    bullets: ['Numeric entry accepts unreduced equivalent fractions.', 'Know ⅛ … ⅞ as decimals.'],
    gotchas: ['0.3 × 0.3 = 0.09 — count decimal places.'],
  },
  {
    lessonId: 'gre-tc-method',
    opsHeaders: ['Step', 'Do', 'Why'],
    opsTable: [
      { op: '1. Cover', complexity: 'hide the choices', note: 'avoids being led by pretty words' },
      { op: '2. Clue', complexity: 'find the phrase describing the blank', note: 'it is always there' },
      { op: '3. Signal', complexity: 'same direction or reversal?', note: 'although, but, because, colon' },
      { op: '4. Predict', complexity: 'your own simple word', note: '“stubborn,” “made it worse”' },
      { op: '5. Match', complexity: 'closest choice; check vs clue', note: 'eliminate by charge first' },
    ],
    ...L,
    useWhen: 'Every one-blank completion: the sentence contains the evidence for exactly one answer.',
    dontUseWhen: 'Picking a word because it fits the topic (e.g. “empirical” in a science sentence) rather than the clue.',
    stdlib: 'Text completion (one blank)',
    bullets: ['Contrast signals flip the blank against the clue.', 'Colons and semicolons restate.'],
    gotchas: ['The opposite of the right answer is usually among the choices.'],
  },
  {
    lessonId: 'gre-tc-multi',
    opsHeaders: ['Step', 'Do', 'Why'],
    opsTable: [
      { op: 'Read all', complexity: 'whole sentence first', note: 'blanks depend on each other' },
      { op: 'Easiest blank', complexity: 'strongest clue first', note: 'often not blank (i)' },
      { op: 'Lock it in', complexity: 'use it as a new clue', note: 'narrows the other blanks' },
      { op: 'Reread', complexity: 'whole completed sentence', note: 'no partial credit' },
    ],
    ...L,
    useWhen: 'Parallel structures (“once X, now Y”) and cause chains link the blanks.',
    dontUseWhen: 'Treating blank (i) as a coin flip — skip it and come back.',
    stdlib: 'Text completion (two & three blanks)',
    bullets: ['Three choices per blank; all blanks must be right.'],
    gotchas: ['The trap choice for a blank often describes a different part of the sentence.'],
  },
  {
    lessonId: 'gre-quant-comparison',
    opsHeaders: ['Answer', 'Means', 'Note'],
    opsTable: [
      { op: 'A', complexity: 'A > B always', note: 'one counterexample kills it' },
      { op: 'B', complexity: 'B > A always', note: 'one counterexample kills it' },
      { op: 'C', complexity: 'A = B always', note: 'x% of y = y% of x' },
      { op: 'D', complexity: 'depends on the values', note: 'impossible with no variables' },
      { op: 'Zones to test', complexity: '0, 1, ½, −1, −½, 10', note: 'only values the constraint allows' },
    ],
    ...L,
    useWhen: 'Variables in the quantities: test numbers from every zone; stop at the first disagreement.',
    dontUseWhen: 'Multiplying or dividing both sides by something that could be negative.',
    stdlib: 'QC — variables & constraints · QC — numbers only · QC — classic traps',
    bullets: ['Simplify both quantities the same way (add/subtract; multiply by positives).', 'Percent vs percentage points.'],
    gotchas: ['x² = 16 → x = 4 OR −4.'],
  },
  {
    lessonId: 'gre-quant-tactics',
    opsHeaders: ['Tactic', 'Use when', 'Tip'],
    opsTable: [
      { op: 'Plug in', complexity: 'variables in the choices', note: 'avoid 0 and 1' },
      { op: 'Backsolve', complexity: 'numeric choices, one unknown', note: 'start with the middle choice' },
      { op: 'Estimate', complexity: 'choices far apart', note: 'round, then compare' },
      { op: 'Calculator', complexity: 'ugly arithmetic, already set up', note: 'Transfer Display for numeric entry' },
      { op: 'Select-all', complexity: 'judge each choice separately', note: 'no partial credit' },
    ],
    ...L,
    useWhen: 'The algebra is slow but checking an answer is fast.',
    dontUseWhen: 'The answer to a different question — reread the last line before clicking.',
    stdlib: 'Apply in every numbered set; timed sets show where time goes',
    bullets: ['Numeric entry: exact unless told to round; check units.'],
    gotchas: ['Choices include the width when the question asks for the perimeter.'],
  },
  {
    lessonId: 'gre-se-method',
    opsHeaders: ['Step', 'Do', 'Why'],
    opsTable: [
      { op: 'Predict', complexity: 'from the clue, choices covered', note: 'same as text completion' },
      { op: 'Find two', complexity: 'both match the prediction', note: 'exactly two answers' },
      { op: 'Confirm the pair', complexity: 'same meaning when inserted', note: 'a family match' },
      { op: 'Check other pairs', complexity: 'do they fit the clue?', note: 'the trap pair doesn’t' },
    ],
    ...L,
    useWhen: 'Six choices, one blank, “select two”: the answers are usually one word family.',
    dontUseWhen: 'A synonym pair that doesn’t fit, or one perfect word with no partner.',
    stdlib: 'Sentence equivalence',
    bullets: ['Both picks must be right — no partial credit.'],
    gotchas: ['“Far from” and “although” flip the clue; the trap pair often describes the flipped side.'],
  },
  {
    lessonId: 'gre-percents',
    opsHeaders: H,
    opsTable: [
      { op: 'Percent change', complexity: '(new − old) ÷ old', note: '80 → 92: +15%' },
      { op: 'Increase p%', complexity: '× (1 + p/100)', note: '+20% → × 1.2' },
      { op: 'Successive', complexity: 'multiply factors', note: '+25% then −20% → × 1.0' },
      { op: 'Undo a change', complexity: '÷ factor', note: '$54 after 25% off → $72' },
      { op: 'Compound interest', complexity: 'P(1 + r)ᵗ', note: '$1,000 at 10%, 2 yrs → $1,210' },
    ],
    ...L,
    useWhen: 'Any percent problem — convert changes to multipliers.',
    dontUseWhen: 'Adding successive percents, or dividing percent change by the NEW value.',
    stdlib: 'Percent of / what percent · Percent change · Successive changes · Finding the original · Interest',
    bullets: ['x% of y = y% of x.', 'Percentage points ≠ percent.'],
    gotchas: ['+p% then −p% is always a net loss.'],
  },
  {
    lessonId: 'gre-ratios',
    opsHeaders: H,
    opsTable: [
      { op: 'Parts', complexity: 'total ÷ (a + b) = one part', note: '4 : 7 of 66 → part 6' },
      { op: 'From a difference', complexity: 'difference ÷ (a − b)', note: '5 : 3, 14 more → part 7' },
      { op: 'Combine ratios', complexity: 'match the shared term', note: '2 : 3 & 4 : 5 → 8 : 12 : 15' },
      { op: 'Changing ratio', complexity: 'hold the unchanged part fixed', note: '3k + 6 : 4k = 1 : 1' },
      { op: 'Machines', complexity: 'rate per machine per hour', note: 'output ∝ machines × time' },
    ],
    ...L,
    useWhen: 'A ratio plus one real number (a total, a difference, a part) — find one part.',
    dontUseWhen: 'Treating a : b as a/b of the total — the total has a + b parts.',
    stdlib: 'Ratios — parts & totals · Combining ratios · Ratios that change · Proportional reasoning',
    bullets: ['A ratio gives shape, not size.'],
    gotchas: ['More workers → less time (inverse); more time → more output (direct).'],
  },
  {
    lessonId: 'gre-rates-work',
    opsHeaders: H,
    opsTable: [
      { op: 'Rate', complexity: 'amount = rate × time', note: 'distance, pages, jobs' },
      { op: 'Average speed', complexity: 'total distance ÷ total time', note: '30 & 60 mph each way → 40' },
      { op: 'Toward each other', complexity: 'add speeds', note: '300 mi at 40 + 60 → 3 h' },
      { op: 'Catching up', complexity: 'subtract speeds', note: 'gap ÷ (fast − slow)' },
      { op: 'Work together', complexity: 'add rates: ab/(a + b)', note: '3 h & 6 h → 2 h' },
      { op: 'Mixtures', complexity: 'track the pure amount', note: '3 L 20% + 1 L 60% → 30%' },
    ],
    ...L,
    useWhen: 'Anything happening “at a rate” — write amount = rate × time.',
    dontUseWhen: 'Averaging speeds or times, or averaging concentrations of unequal volumes.',
    stdlib: 'Average speed · Meeting & catching up · Work rates · Mixtures',
    bullets: ['Together must be faster than the fastest worker alone.', 'Drains subtract rates.'],
    gotchas: ['Adding water changes volume, not the amount of substance.'],
  },
  {
    lessonId: 'gre-rc-method',
    opsHeaders: ['Question type', 'Look', 'Classic wrong answer'],
    opsTable: [
      { op: 'Main idea', complexity: 'first/last sentences, pivots', note: 'true but too narrow' },
      { op: 'Detail', complexity: 'find the sentence', note: 'right words, wrong claim' },
      { op: 'Inference', complexity: 'one small step past the text', note: 'goes too far' },
      { op: 'Function', complexity: 'the sentence before', note: 'restates instead of explaining why' },
      { op: 'Vocab in context', complexity: 'surrounding words', note: 'the common meaning' },
    ],
    ...L,
    useWhen: 'Every RC question: point to the sentence that proves your answer.',
    dontUseWhen: 'Outside knowledge, extreme words (“always,” “all”), or answers that distort the text.',
    stdlib: 'Reading comprehension',
    bullets: ['First read: main point, each paragraph’s job, author’s attitude.', 'Pivot words (however, yet) mark the author’s view.'],
    gotchas: ['Select-all: judge each choice alone; one, two, or three can be right.'],
  },
  {
    lessonId: 'gre-rc-arguments',
    opsHeaders: ['Flaw', 'Looks like', 'Weaken with'],
    opsTable: [
      { op: 'Correlation → cause', complexity: 'A goes with B, so A causes B', note: 'third factor; reverse cause' },
      { op: 'Bad sample', complexity: 'blog poll → whole city', note: 'sample differs from population' },
      { op: 'Bad analogy', complexity: 'worked in X, so works in Y', note: 'X and Y differ' },
      { op: 'Base rate', complexity: 'more vaccinated patients', note: 'more people vaccinated overall' },
      { op: 'Revenue vs profit', complexity: 'sales up → profit up', note: 'costs rose' },
    ],
    ...L,
    useWhen: 'Find the gap between evidence and conclusion; the answer fills, widens, or names it.',
    dontUseWhen: 'Choices that discuss the topic without touching the gap.',
    stdlib: 'Argument questions (critical reasoning)',
    bullets: ['Assumption: negate it — if the argument collapses, it was required.'],
    gotchas: ['“Must be true” answers can’t add new information.'],
  },
  {
    lessonId: 'gre-linear',
    opsHeaders: H,
    opsTable: [
      { op: 'Fractions', complexity: 'multiply every term by the LCD', note: 'x/3 + 2 = x/2 − 1 → x = 18' },
      { op: 'Systems', complexity: 'add/subtract to get x ± y', note: '4x+3y=19, 3x+4y=16 → x+y=5' },
      { op: 'Inequality × negative', complexity: 'flip the sign', note: '−3x > 12 → x < −4' },
      { op: '|x − a| = b', complexity: 'x = a ± b', note: 'sum of solutions = 2a' },
      { op: '|x − a| ≤ b', complexity: 'a − b ≤ x ≤ a + b', note: 'distance from a' },
    ],
    ...L,
    useWhen: 'The question asks for an expression (x + y, 2x − 3) — look for a way to get it directly.',
    dontUseWhen: 'Multiplying an inequality by a variable of unknown sign.',
    stdlib: 'Linear equations · Systems · Inequalities · Absolute value · Word translation · Ages',
    bullets: ['“5 less than x” is x − 5.', 'Define variables in words.'],
    gotchas: ['Solving for x when the question wants x + y.'],
  },
  {
    lessonId: 'gre-quadratics',
    opsHeaders: H,
    opsTable: [
      { op: 'Factor x² + bx + c', complexity: 'multiply to c, add to b', note: 'x² − 5x + 6 = (x − 2)(x − 3)' },
      { op: 'Sum / product of roots', complexity: '−b and c (when a = 1)', note: 'roots of x² − 5x + 6: sum 5, product 6' },
      { op: '(x + y)²', complexity: 'x² + 2xy + y²', note: 'x² + y² = (x+y)² − 2xy' },
      { op: '(x − y)²', complexity: 'x² − 2xy + y²', note: '' },
      { op: 'Difference of squares', complexity: '(x + y)(x − y) = x² − y²', note: '51 × 49 = 2,499' },
    ],
    ...L,
    useWhen: 'Given x + y and xy (or x − y), asked for x² + y² — use an identity.',
    dontUseWhen: 'Dividing both sides by x — you lose x = 0.',
    stdlib: 'Solving quadratics · Special products',
    bullets: ['Set the equation equal to 0 before factoring.'],
    gotchas: ['Sign errors: (x + 5) = 0 gives x = −5.'],
  },
  {
    lessonId: 'gre-functions-sequences',
    opsHeaders: H,
    opsTable: [
      { op: 'Substitute', complexity: 'parentheses around every value', note: 'f(−2) = (−2)² − 3(−2)' },
      { op: 'Composition', complexity: 'inside first', note: 'f(g(2)) ≠ g(f(2))' },
      { op: 'Arithmetic seq.', complexity: 'aₙ = a₁ + (n − 1)d', note: 'sum = n × (first + last)/2' },
      { op: 'Geometric seq.', complexity: 'aₙ = a₁ × rⁿ⁻¹', note: '3, 6, 12 … a₇ = 192' },
      { op: 'Inverse variation', complexity: 'xy constant', note: 'y = 8 at x = 6 → y = 3 at x = 16' },
    ],
    ...L,
    useWhen: 'Made-up symbols: treat them as a two-input function, keeping a and b in order.',
    dontUseWhen: 'Off-by-one in sequences: term 1 to term 10 is 9 steps.',
    stdlib: 'Functions · Defined operations · Sequences · Direct & inverse variation',
    bullets: ['Recursive sequences: just write the terms out.'],
    gotchas: ['“Varies as the square” — doubling x multiplies y by 4.'],
  },
  {
    lessonId: 'gre-issue-essay',
    opsHeaders: ['Part', 'Contains', 'Length'],
    opsTable: [
      { op: 'Introduction', complexity: 'issue + qualified position + preview', note: '3–4 sentences' },
      { op: 'Body 1', complexity: 'strongest reason + specific example + explanation', note: 'a full paragraph' },
      { op: 'Body 2', complexity: 'second reason + different kind of example', note: 'a full paragraph' },
      { op: 'Counterargument', complexity: 'strongest opposing view + response', note: 'a full paragraph' },
      { op: 'Conclusion', complexity: 'restate position; no new ideas', note: '2–3 sentences' },
    ],
    ...L,
    useWhen: 'Every Issue prompt: plan 5 minutes, write 22, proofread 3.',
    dontUseWhen: 'Ignoring the task-specific instructions, or piling up rare words instead of reasons.',
    stdlib: 'Write one timed essay a week from week 5; ask the tutor for rubric feedback',
    bullets: ['Qualified positions read as nuanced.', 'Examples don’t argue for themselves — explain them.'],
    gotchas: ['No spellcheck in the test editor — leave time to proofread.'],
  },
  {
    lessonId: 'gre-lines-triangles',
    opsHeaders: H,
    opsTable: [
      { op: 'Triangle angles', complexity: 'sum to 180°', note: 'ratio 2:3:7 → 105° largest' },
      { op: 'Exterior angle', complexity: '= sum of remote interiors', note: '130° = 55° + 75°' },
      { op: 'Pythagorean triples', complexity: '3-4-5, 5-12-13, 8-15-17', note: 'and multiples' },
      { op: '45-45-90', complexity: 'x : x : x√2', note: 'square area = diagonal² ÷ 2' },
      { op: '30-60-90', complexity: 'x : x√3 : 2x', note: 'equilateral area = s²√3/4' },
      { op: 'Triangle inequality', complexity: 'difference < side < sum', note: '4 & 9 → 5 < x < 13' },
    ],
    ...L,
    useWhen: 'Right angles or a diagonal: reach for Pythagoras and the special triangles.',
    dontUseWhen: 'Assuming anything from the figure that isn’t stated.',
    stdlib: 'Angles & triangles · Pythagorean theorem · Special right triangles · Triangle inequality · Similar figures',
    bullets: ['Parallel lines + transversal: only x and 180° − x.', 'Similar figures: areas scale by k².'],
    gotchas: ['Figures are not necessarily drawn to scale.'],
  },
  {
    lessonId: 'gre-circles-polygons-solids',
    opsHeaders: H,
    opsTable: [
      { op: 'Circle', complexity: 'C = 2πr, A = πr²', note: 'r first, always' },
      { op: 'Arc / sector', complexity: '(θ/360) × whole', note: '45° of area 64π → 8π' },
      { op: 'Polygon angles', complexity: '(n − 2) × 180°', note: 'exterior angle = 360°/n' },
      { op: 'Box', complexity: 'V = lwh; diagonal √(l²+w²+h²)', note: '3×4×12 → 13' },
      { op: 'Cylinder', complexity: 'V = πr²h', note: '2× radius → 4× volume' },
    ],
    ...L,
    useWhen: 'Everything circular reduces to r; everything solid to base area × height.',
    dontUseWhen: 'Plugging a diameter into a radius formula.',
    stdlib: 'Circles · Arcs & sectors · Polygons · Rectangles & squares · Boxes, cubes & cylinders',
    bullets: ['Inscribed angle in a semicircle = 90°.', 'Lengths ×k → volumes ×k³.'],
    gotchas: ['Parallelogram height is perpendicular, not the slanted side.'],
  },
  {
    lessonId: 'gre-coordinate',
    opsHeaders: H,
    opsTable: [
      { op: 'Slope', complexity: '(y₂ − y₁)/(x₂ − x₁)', note: 'same order top and bottom' },
      { op: 'Distance', complexity: '√(Δx² + Δy²)', note: '(−2, 1) to (4, 9) → 10' },
      { op: 'Midpoint', complexity: 'average the coordinates', note: '' },
      { op: 'Line', complexity: 'y = mx + b', note: 'x-intercept: set y = 0' },
      { op: 'Perpendicular', complexity: 'negative reciprocal', note: '2/3 ⊥ −3/2' },
    ],
    ...L,
    useWhen: 'Two points given — sketch them first.',
    dontUseWhen: 'Confusing the x- and y-intercepts.',
    stdlib: 'Slope, distance & midpoint · Lines, intercepts & perpendiculars',
    bullets: ['Parallel lines have equal slopes.'],
    gotchas: ['Rewrite ax + by = c as y = … before reading the slope.'],
  },
  {
    lessonId: 'gre-statistics',
    opsHeaders: H,
    opsTable: [
      { op: 'Average', complexity: 'sum = average × count', note: 'add a number → use sums' },
      { op: 'Weighted average', complexity: 'total ÷ total count', note: 'closer to the bigger group' },
      { op: 'Median', complexity: 'middle of the SORTED list', note: 'even count → average two' },
      { op: 'SD', complexity: 'spread; +k: same, ×k: ×k', note: 'all equal → 0' },
      { op: 'Normal', complexity: '68 / 95 / 99.7', note: 'above +1 SD ≈ 16%' },
    ],
    ...L,
    useWhen: 'Averages change when numbers are added or removed — switch to sums.',
    dontUseWhen: 'Averaging averages of groups with different sizes.',
    stdlib: 'Averages · Weighted averages · Median, mode & range · Standard deviation · Normal distribution · Quartiles',
    bullets: ['IQR = Q3 − Q1.', 'Outliers move the mean, not the median.'],
    gotchas: ['Comparing SDs by the size of the numbers instead of their spread.'],
  },
  {
    lessonId: 'gre-counting-probability',
    opsHeaders: H,
    opsTable: [
      { op: 'Stages', complexity: 'multiply the options', note: '3 shirts × 4 pants = 12' },
      { op: 'Order matters', complexity: 'n!/(n − k)!', note: 'pres + VP from 10 → 90' },
      { op: 'Order doesn’t', complexity: 'C(n, k)', note: 'committee of 3 from 8 → 56' },
      { op: 'Together / apart', complexity: 'block; total − together', note: '5 in a row, A&B together → 48' },
      { op: 'At least one', complexity: '1 − P(none)', note: '4 flips → 15/16' },
      { op: 'Sets', complexity: 'A + B − both + neither', note: '' },
    ],
    ...L,
    useWhen: '“At least one” — use the complement.',
    dontUseWhen: 'Adding probabilities for AND events, or forgetting that draws without replacement change the odds.',
    stdlib: 'Permutations · Combinations · Probability · Combining probabilities · Overlapping sets',
    bullets: ['Independent AND → multiply.', 'OR → add, then subtract the overlap.'],
    gotchas: ['A probability above 1 means something went wrong.'],
  },
  {
    lessonId: 'gre-data-interpretation',
    opsHeaders: H,
    opsTable: [
      { op: 'Read first', complexity: 'title, units, scale, footnotes', note: 'thousands vs millions' },
      { op: 'Percent change', complexity: '(later − earlier) ÷ earlier', note: 'percent ≠ absolute' },
      { op: 'Share of total', complexity: 'part ÷ total', note: '300 of 780 → 38%' },
      { op: 'Percent of percent', complexity: 'multiply', note: '30% × 40% = 12%' },
    ],
    ...L,
    useWhen: 'A set of questions shares one table or graph — spend 15 seconds on the display first.',
    dontUseWhen: 'Choosing the biggest absolute change when the question asks for percent change.',
    stdlib: 'Data interpretation (tables)',
    bullets: ['Estimate when choices are far apart.'],
    gotchas: ['Axes that don’t start at zero exaggerate differences.'],
  },
  {
    lessonId: 'gre-test-day',
    opsHeaders: ['Section', 'Time', 'Halfway checkpoint'],
    opsTable: [
      { op: 'Verbal 1 (12 Q)', complexity: '18 min', note: 'Q6 at ~9 min' },
      { op: 'Verbal 2 (15 Q)', complexity: '23 min', note: 'Q8 at ~12 min' },
      { op: 'Quant 1 (12 Q)', complexity: '21 min', note: 'Q6 at ~10–11 min' },
      { op: 'Quant 2 (15 Q)', complexity: '26 min', note: 'Q8 at ~13 min' },
    ],
    ...L,
    useWhen: 'Two passes: answer the quick ones, guess-and-mark the rest, return with leftover time.',
    dontUseWhen: 'Changing answers on a hunch, or leaving any question blank.',
    stdlib: 'Timed sections in the practice bank',
    bullets: ['Last full practice test 3–4 days before.', 'Check ETS’s current ID and at-home rules a week ahead.'],
    gotchas: ['A hard second section usually means the first went well.'],
  },
  {
    lessonId: 'gre-practice-bank',
    opsHeaders: ['Mode', 'Best for', 'Note'],
    opsTable: [
      { op: 'Numbered sets', complexity: 'daily mixed practice', note: 'Foundation → Core → Advanced' },
      { op: 'Timed mode', complexity: 'pacing', note: 'feedback at the end' },
      { op: 'Topic drills', complexity: 'fixing one weak skill', note: 'unseen questions first' },
      { op: 'Mistakes', complexity: 'closing gaps', note: 'leaves the list when you get it right' },
      { op: 'Review queue', complexity: 'retention', note: 'fresh variants for most quant topics' },
    ],
    ...L,
    useWhen: 'After each set, drill any topic under ~70%.',
    dontUseWhen: 'Racing through questions without reading the explanations.',
    stdlib: 'Course dashboard → Practice bank',
    bullets: ['11,000+ questions: you will not run out.', 'Move up a tier at a consistent 85%+.'],
    gotchas: ['Timed practice from week 4 — untimed practice alone doesn’t teach pacing.'],
  },
];
