import type { TradeoffTableData } from '@/lib/types';

// GRE reference tables, aggregated globally in content/tradeoffs.ts and shown
// on /reference. Lessons embed them with <TradeoffTable id="..." />.

export const TRADEOFFS: TradeoffTableData[] = [
  {
    id: 'gre-sections',
    lessonId: 'gre-overview',
    title: 'The GRE General Test at a glance (about 1 hour 58 minutes)',
    columns: ['questions', 'time', 'pace', 'notes'],
    rows: [
      { label: 'Analytical Writing', cells: ['1 “Analyze an Issue” essay', '30 min', '—', 'always first; scored 0–6 in half points'] },
      { label: 'Verbal, section 1', cells: ['12', '18 min', '1.5 min/Q', 'your score here sets section 2’s difficulty'] },
      { label: 'Verbal, section 2', cells: ['15', '23 min', '~1.5 min/Q', 'easier or harder based on section 1'] },
      { label: 'Quant, section 1', cells: ['12', '21 min', '1.75 min/Q', 'on-screen calculator available'] },
      { label: 'Quant, section 2', cells: ['15', '26 min', '~1.75 min/Q', 'easier or harder based on section 1'] },
    ],
    note: 'Verbal and Quant are each scored 130–170 in 1-point steps. After the essay, the Verbal and Quant sections can come in either order. No penalty for wrong answers — never leave a question blank.',
  },
  {
    id: 'gre-question-types',
    lessonId: 'gre-overview',
    title: 'Every question type you will see',
    columns: ['section', 'format', 'the move'],
    rows: [
      { label: 'Text completion', cells: ['Verbal', '1–3 blanks; 5 choices (1 blank) or 3 per blank', 'find the clue, predict, then match; all blanks right or no credit'] },
      { label: 'Sentence equivalence', cells: ['Verbal', '1 blank, 6 choices, pick exactly 2', 'the two picks must fit AND mean the same thing'] },
      { label: 'Reading comprehension', cells: ['Verbal', 'passage + 1–4 questions; some “select all”', 'answer from the text, not from outside knowledge'] },
      { label: 'Quantitative comparison', cells: ['Quant', 'Quantity A vs B; 4 fixed choices', 'test numbers from every allowed zone; disagreement → D'] },
      { label: 'Multiple choice, one answer', cells: ['Quant', '5 choices', 'solve, or backsolve from the choices'] },
      { label: 'Multiple choice, one or more', cells: ['Quant', 'select all that apply', 'check every choice; no partial credit'] },
      { label: 'Numeric entry', cells: ['Quant', 'type the number (or a fraction)', 'no choices to lean on — check units and rounding'] },
      { label: 'Data interpretation', cells: ['Quant', 'questions on a shared table or graph', 'read the labels and units before the numbers'] },
    ],
  },
  {
    id: 'gre-plan-phases',
    lessonId: 'gre-study-plan',
    title: 'The 8-week plan in three phases',
    columns: ['weeks', 'focus', 'daily practice'],
    rows: [
      { label: 'Build', cells: ['1–4', 'one module per few days; learn every method', '1 quant set + 1 verbal set (≈ 40 questions, ~1 hour)'] },
      { label: 'Strengthen', cells: ['5–6', 'finish lessons; drill weakest topics', '2 sets per track, one of them timed; redo mistakes'] },
      { label: 'Simulate', cells: ['7–8', 'full-length practice tests; essays under time', 'timed sets daily; review queue; light last 2 days'] },
    ],
    note: 'The bank holds far more than 8 weeks need — keep working through the numbered sets after the plan, or stretch the plan if your test date is further out.',
  },
  {
    id: 'gre-number-zones',
    lessonId: 'gre-quant-comparison',
    title: 'Numbers to test in quantitative comparison (and why)',
    labelColumn: 'zone',
    columns: ['try', 'what it catches'],
    rows: [
      { label: 'Zero', cells: ['0', 'products vanish; x² = x³ = 0'] },
      { label: 'One', cells: ['1', 'powers stop changing; x = x² = √x'] },
      { label: 'Proper fraction', cells: ['½', 'squaring shrinks; roots grow; 1/x > x'] },
      { label: 'Negative', cells: ['−1, −2', 'odd powers stay negative; order flips when you multiply by a negative'] },
      { label: 'Negative fraction', cells: ['−½', 'the zone test-writers love: x³ > x here'] },
      { label: 'Big number', cells: ['10, 100', 'exponentials overtake polynomials'] },
    ],
    note: 'Only test values the constraint allows. As soon as two allowed values give different relationships, the answer is D — stop testing.',
  },
  {
    id: 'gre-signal-words',
    lessonId: 'gre-tc-method',
    title: 'Signal words: which way does the sentence turn?',
    labelColumn: 'signal',
    columns: ['examples', 'effect on the blank'],
    rows: [
      { label: 'Contrast', cells: ['but, yet, although, though, despite, however, while, far from, rather than, instead', 'the blank goes AGAINST the clue'] },
      { label: 'Continuation', cells: ['and, moreover, indeed, in fact, also, likewise, not only … but also', 'the blank goes WITH the clue'] },
      { label: 'Definition / restatement', cells: ['colon (:), semicolon (;), that is, in other words, namely', 'the blank restates the clue'] },
      { label: 'Cause / effect', cells: ['because, since, so, therefore, thus, consequently', 'the blank follows logically from the clue'] },
      { label: 'Surprise', cells: ['surprisingly, unexpectedly, ironically, paradoxically', 'the blank is the opposite of what you would expect'] },
    ],
  },
  {
    id: 'gre-rc-question-types',
    lessonId: 'gre-rc-method',
    title: 'Reading comprehension question types',
    columns: ['asks', 'where the answer lives', 'classic wrong answer'],
    rows: [
      { label: 'Main idea / primary purpose', cells: ['what the whole passage does', 'first and last sentences of each paragraph', 'true detail, too narrow'] },
      { label: 'Detail', cells: ['“according to the passage”', 'one specific sentence — go find it', 'right words, wrong claim'] },
      { label: 'Inference', cells: ['what must be true', 'one or two sentences, one small step further', 'plausible but goes beyond the text'] },
      { label: 'Function', cells: ['why the author mentions X', 'the sentence BEFORE X', 'restates X instead of its purpose'] },
      { label: 'Vocabulary in context', cells: ['what a word means here', 'the words around it', 'the word’s most common meaning'] },
      { label: 'Select all (3 choices)', cells: ['every true choice', 'check each independently', 'picking only one when two are true'] },
    ],
  },
  {
    id: 'gre-cr-types',
    lessonId: 'gre-rc-arguments',
    title: 'Argument questions: what each type wants',
    columns: ['the task', 'what the right answer does'],
    rows: [
      { label: 'Assumption', cells: ['find the unstated premise', 'if you negate it, the argument collapses'] },
      { label: 'Weaken', cells: ['make the conclusion less likely', 'offers an alternative cause, a bad sample, or a broken analogy'] },
      { label: 'Strengthen', cells: ['make the conclusion more likely', 'rules out an alternative or confirms the assumption'] },
      { label: 'Paradox / explain', cells: ['reconcile two facts that seem to clash', 'shows how both can be true at once'] },
      { label: 'Flaw', cells: ['name the reasoning error', 'describes it abstractly: correlation ≠ causation, unrepresentative sample …'] },
      { label: 'Evaluate', cells: ['what would help to know', 'information whose answer would swing the conclusion either way'] },
      { label: 'Inference', cells: ['what must be true', 'follows from the facts with no new assumptions'] },
    ],
  },
  {
    id: 'gre-percent-tools',
    lessonId: 'gre-percents',
    title: 'Percent tools',
    labelColumn: 'situation',
    columns: ['multiply by', 'example'],
    rows: [
      { label: 'Increase by p%', cells: ['(1 + p/100)', 'up 20% → × 1.2'] },
      { label: 'Decrease by p%', cells: ['(1 − p/100)', 'down 15% → × 0.85'] },
      { label: 'Successive changes', cells: ['multiply the factors', '+20% then −20% → × 0.96 (a 4% loss)'] },
      { label: 'Undo a change', cells: ['divide by the factor', 'after 25% off it costs $60 → $60 ÷ 0.75 = $80'] },
      { label: 'Percent change', cells: ['(new − old) ÷ old', '40 → 50 is +25%; 50 → 40 is −20%'] },
    ],
  },
  {
    id: 'gre-special-triangles',
    lessonId: 'gre-lines-triangles',
    title: 'Right triangles worth memorizing',
    columns: ['sides', 'how to spot it'],
    rows: [
      { label: '3-4-5', cells: ['and 6-8-10, 9-12-15 …', 'legs in ratio 3:4'] },
      { label: '5-12-13', cells: ['and 10-24-26 …', 'legs in ratio 5:12'] },
      { label: '8-15-17', cells: ['and 16-30-34', 'less common, but it appears'] },
      { label: '45-45-90', cells: ['x : x : x√2', 'isosceles right triangle; half of a square'] },
      { label: '30-60-90', cells: ['x : x√3 : 2x', 'half of an equilateral triangle'] },
    ],
  },
  {
    id: 'gre-counting',
    lessonId: 'gre-counting-probability',
    title: 'Does order matter? Permutation or combination',
    columns: ['order matters?', 'formula', 'example'],
    rows: [
      { label: 'Arrange all n', cells: ['yes', 'n!', '5 books on a shelf: 120'] },
      { label: 'Arrange k of n', cells: ['yes', 'n!/(n − k)!', 'president + VP from 10: 90'] },
      { label: 'Choose k of n', cells: ['no', 'n!/(k!(n − k)!)', 'committee of 2 from 10: 45'] },
      { label: 'Letters with repeats', cells: ['yes', 'n!/(a!·b!·…)', 'LEVEL: 5!/(2!·2!) = 30'] },
      { label: 'Independent stages', cells: ['—', 'multiply the counts', '3 shirts × 4 pants = 12 outfits'] },
    ],
  },
  {
    id: 'gre-issue-rubric',
    lessonId: 'gre-issue-essay',
    title: 'What separates Issue scores',
    columns: ['a 6 essay', 'a 4 essay', 'a 2 essay'],
    rows: [
      { label: 'Position', cells: ['clear, insightful, nuanced', 'clear', 'unclear or missing'] },
      { label: 'Support', cells: ['compelling, specific examples', 'relevant but general', 'little or irrelevant'] },
      { label: 'Organization', cells: ['logical, with smooth transitions', 'adequate', 'poorly organized'] },
      { label: 'Language', cells: ['precise, varied', 'generally clear, some errors', 'frequent errors that obscure meaning'] },
    ],
    note: 'A paraphrase of the published scoring guide’s spirit, not its wording. Length helps only because development takes space — a long, repetitive essay does not score well.',
  },
  {
    id: 'gre-quant-tactics',
    lessonId: 'gre-quant-tactics',
    title: 'Which quant tactic when',
    columns: ['use it when', 'watch out for'],
    rows: [
      { label: 'Plug in numbers', cells: ['variables in the question AND the choices', 'pick values that keep the arithmetic easy and distinct'] },
      { label: 'Backsolve', cells: ['numeric choices and a “what is x?” question', 'start with the middle choice to cut the work in half'] },
      { label: 'Estimate', cells: ['choices are far apart', 'close choices demand exact work'] },
      { label: 'Calculator', cells: ['ugly arithmetic you have already set up', 'using it for things faster by hand'] },
      { label: 'Skip and return', cells: ['more than ~2.5 min with no plan', 'forgetting to guess before time runs out'] },
    ],
  },
];
