import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'mcq',
    id: 'gre-tc1-predict',
    lessonId: 'gre-tc-method',
    difficulty: 1,
    prompt: 'The manager’s ___ approach to the budget — she questioned every expense, however small — frustrated some employees but saved the company millions.',
    options: ['cavalier', 'scrupulous', 'lavish', 'haphazard', 'indifferent'],
    correctIndex: 1,
    explanation: 'Clue: “she questioned every expense, however small.” Prediction: extremely careful. **Scrupulous** matches. The dashes restate the blank — a definition signal.',
    distractorNotes: [
      'Careless and offhand — the opposite of questioning every expense.',
      'Correct.',
      'Generous with spending — contradicts the clue.',
      'Lacking a plan — the opposite of her methodical approach.',
      'Uninterested — she cared intensely.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-tc1-signal',
    lessonId: 'gre-tc-method',
    difficulty: 2,
    prompt: 'Although the candidate’s supporters described her platform as visionary, her critics dismissed it as ___, a collection of slogans with no workable proposals.',
    options: ['pragmatic', 'innovative', 'vacuous', 'meticulous', 'radical'],
    correctIndex: 2,
    explanation: 'Clue: “a collection of slogans with no workable proposals.” Signal: “although … supporters … critics” — a contrast with “visionary.” Prediction: empty, lacking substance. **Vacuous** matches.',
    distractorNotes: [
      'Practical and workable — contradicts “no workable proposals.”',
      'A synonym for “visionary” — the supporters’ side of the contrast.',
      'Correct.',
      'Carefully detailed — the opposite of slogans.',
      'Tempting because critics might say it, but the clue is about emptiness, not extremism.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-tc1-unknown',
    lessonId: 'gre-tc-method',
    difficulty: 3,
    prompt: 'Rather than address the committee’s specific objections, the director responded with ___ generalities that committed him to nothing.',
    options: ['anodyne', 'incisive', 'pointed', 'explicit', 'trenchant'],
    correctIndex: 0,
    explanation: 'Clue: “generalities that committed him to nothing.” Prediction: bland, noncommittal. **Anodyne** means inoffensive and bland. Even if you didn’t know it, the other four all mean sharp or clear — the opposite of the clue — so elimination leaves only anodyne.',
    distractorNotes: [
      'Correct — bland, unlikely to offend.',
      'Sharp and penetrating — the opposite.',
      'Direct and sharp — the opposite.',
      'Clearly stated — the opposite of noncommittal.',
      'Forceful and cutting — the opposite.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-tc1-colon',
    lessonId: 'gre-tc-method',
    difficulty: 2,
    prompt: 'The novel’s ending is deliberately ___: readers still argue about whether the narrator survives.',
    options: ['conclusive', 'ambiguous', 'derivative', 'tragic', 'redundant'],
    correctIndex: 1,
    explanation: 'The colon signals that what follows explains the blank. Readers arguing about what happened means the ending is open to interpretation: **ambiguous**.',
    distractorNotes: [
      'The opposite — a conclusive ending would settle the argument.',
      'Correct.',
      'Unoriginal — nothing in the clue is about originality.',
      'Possible in a story, but the clue is about uncertainty, not sadness.',
      'Unnecessary repetition — not supported.',
    ],
  },
];
