import type { Question } from '@/lib/types';

const QC = [
  'Quantity A is greater.',
  'Quantity B is greater.',
  'The two quantities are equal.',
  'The relationship cannot be determined from the information given.',
];

export const QUESTIONS: Question[] = [
  {
    kind: 'mcq',
    id: 'gre-qc-fixed',
    lessonId: 'gre-quant-comparison',
    difficulty: 1,
    prompt: 'Compare Quantity A and Quantity B.',
    stimulus: { quantities: { a: '2¹⁰', b: '10³' } },
    options: QC,
    correctIndex: 0,
    explanation: '2¹⁰ = 1,024 and 10³ = 1,000, so Quantity A is greater. With no variables, D is never correct — two fixed numbers always compare one way.',
    distractorNotes: [
      'Correct — 1,024 > 1,000.',
      '1,000 is smaller.',
      'Close (it’s why 2¹⁰ ≈ 10³ is a handy estimate) but not equal.',
      'Impossible here: no unknowns.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-qc-zones',
    lessonId: 'gre-quant-comparison',
    difficulty: 2,
    prompt: 'x < 0',
    stimulus: { quantities: { a: 'x³', b: 'x' } },
    options: QC,
    correctIndex: 3,
    explanation: 'Try x = −2: A = −8, B = −2 → B greater. Try x = −½: A = −⅛, B = −½ → A greater. Two allowed values disagree → **D**. The negative fraction zone is the one people forget.',
    distractorNotes: [
      'True for −1 < x < 0 only.',
      'True for x < −1 only.',
      'True only at x = −1.',
      'Correct.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-qc-square',
    lessonId: 'gre-quant-comparison',
    difficulty: 2,
    prompt: 'y² = 49',
    stimulus: { quantities: { a: 'y', b: '7' } },
    options: QC,
    correctIndex: 3,
    explanation: 'y = 7 (equal) or y = −7 (B greater). Different outcomes → **D**.',
    distractorNotes: [
      'y is never greater than 7 here.',
      'Only when y = −7.',
      'Only when y = 7 — the classic trap.',
      'Correct.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-qc-points',
    lessonId: 'gre-quant-comparison',
    difficulty: 2,
    prompt: 'A town’s unemployment rate rose from 4% to 5%.',
    stimulus: { quantities: { a: 'The percent increase in the unemployment rate', b: '1%' } },
    options: QC,
    correctIndex: 0,
    explanation: 'The rate rose by 1 percentage point, but the percent increase is (5 − 4)/4 = 25%. 25% > 1% → **A**.',
    distractorNotes: [
      'Correct.',
      'Confuses percentage points with percent change.',
      'The 1-point change is not a 1% change.',
      'All the numbers are given.',
    ],
  },
  {
    kind: 'mcq',
    id: 'gre-qc-simplify',
    lessonId: 'gre-quant-comparison',
    difficulty: 3,
    prompt: 'k is a positive integer.',
    stimulus: { quantities: { a: 'k/(k + 1)', b: '(k + 1)/(k + 2)' } },
    options: QC,
    correctIndex: 1,
    explanation: 'Both denominators are positive, so cross-multiply safely: compare k(k + 2) = k² + 2k with (k + 1)² = k² + 2k + 1. The second is always 1 bigger → **B**. (Try k = 1: ½ vs ⅔.)',
    distractorNotes: [
      'Test k = 1: ½ < ⅔.',
      'Correct.',
      'They differ by (k + 1)² − k(k + 2) = 1 after cross-multiplying.',
      'Cross-multiplying shows B is always bigger.',
    ],
  },
];
