import React from 'react';
import { type PowerPiece, splitPowers } from '@/lib/powers';

/**
 * The tiny bit of formatting question text needs: **bold**, line breaks, and
 * caret exponents drawn as raised powers (9^(x + 1) → 9ˣ⁺¹). Deliberately
 * nothing else. Prompts, options, and explanations are plain strings authored
 * in TS (and generated by the GRE bank), so a single `*` in "a * b" or
 * "dp[i][*]" must stay literal.
 */
export function RichText({ text }: { text: string }) {
  const lines = text.split('\n');
  return (
    <>
      {lines.map((line, li) => (
        <React.Fragment key={li}>
          {li > 0 && <br />}
          {line.split(/(\*\*[^*\n]+\*\*)/g).map((part, pi) =>
            part.startsWith('**') && part.endsWith('**') && part.length > 4 ? (
              <strong key={pi} className="font-semibold">
                <Powers text={part.slice(2, -2)} />
              </strong>
            ) : (
              <Powers key={pi} text={part} />
            ),
          )}
        </React.Fragment>
      ))}
    </>
  );
}

/** Plain text with its caret exponents raised: "2^x" → 2 with a superscript x. */
export function Powers({ text }: { text: string }) {
  return <>{text.includes('^') ? renderPieces(splitPowers(text)) : text}</>;
}

function renderPieces(pieces: PowerPiece[]): React.ReactNode[] {
  return pieces.map((p, i) =>
    typeof p === 'string' ? <React.Fragment key={i}>{p}</React.Fragment> : <sup key={i}>{renderPieces(p.sup)}</sup>,
  );
}

/** Multi-paragraph text (reading passages): blank lines separate paragraphs. */
export function Paragraphs({ text, className }: { text: string; className?: string }) {
  return (
    <div className={className}>
      {text
        .split(/\n\s*\n/)
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p, i) => (
          <p key={i} className="mb-3 last:mb-0">
            <RichText text={p} />
          </p>
        ))}
    </div>
  );
}
