import React from 'react';

/**
 * The tiny bit of formatting question text needs: **bold** and line breaks.
 * Deliberately nothing else — prompts, options, and explanations are plain
 * strings authored in TS (and generated by the GRE bank), so a single `*` in
 * "a * b" or "dp[i][*]" must stay literal.
 */
export function RichText({ text }: { text: string }) {
  const lines = text.split('\n');
  return (
    <>
      {lines.map((line, li) => (
        <React.Fragment key={li}>
          {li > 0 && <br />}
          {line.split(/(\*\*[^*\n]+\*\*)/g).map((part, pi) =>
            part.startsWith('**') && part.endsWith('**') && part.length > 4 ? (
              <strong key={pi} className="font-semibold">
                {part.slice(2, -2)}
              </strong>
            ) : (
              <React.Fragment key={pi}>{part}</React.Fragment>
            ),
          )}
        </React.Fragment>
      ))}
    </>
  );
}

/** Multi-paragraph text (reading passages): blank lines separate paragraphs. */
export function Paragraphs({ text, className }: { text: string; className?: string }) {
  return (
    <div className={className}>
      {text
        .split(/\n\s*\n/)
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p, i) => (
          <p key={i} className="mb-3 last:mb-0">
            <RichText text={p} />
          </p>
        ))}
    </div>
  );
}
