import type { CheatsheetData } from '@/lib/types';

// One cheatsheet per LLM lesson — the night-before quick reference. Uses the
// shared CheatsheetData shape with LLM-appropriate column headers/labels.
// Aggregated globally in content/cheatsheets.ts.

const H: [string, string, string] = ['Concept', 'What it is', 'Why it bites'];

export const LLM_CHEATSHEETS: CheatsheetData[] = [
  {
    lessonId: 'llm-foundations',
    opsHeaders: H,
    opsTable: [
      { op: 'the one function', complexity: 'tokens → P(next token)', note: 'everything else is a zoom-in on this' },
      { op: 'autoregressive', complexity: 'predict, append, repeat', note: 'why output streams token by token' },
      { op: 'parameters (weights)', complexity: 'the billions of learned numbers', note: '“70B” = 70B of them; they ARE the model' },
      { op: 'context window', complexity: 'max tokens it can condition on', note: 'its only working memory' },
      { op: 'training vs inference', complexity: 'learn once, frozen forever', note: 'chats never change the weights' },
      { op: 'base vs instruct', complexity: 'continuer vs assistant', note: 'chatting is a learned layer on top' },
    ],
    useWhen: 'Any time model behavior surprises you — trace it back to one clause of “frozen weights turn a context window of tokens into a distribution over the next token.”',
    dontUseWhen: 'You expect it to look facts up, remember past sessions, or know anything after its knowledge cutoff — none of that is in the mechanism.',
    stdlib: 'the transformer (Module 3) · pretraining + RLHF (Module 11) · scaling laws',
    stdlibLabel: 'See also',
    bullets: [
      'An LLM predicts the next token; generation is that prediction looped, each token conditioned on all prior ones.',
      'Training learns the weights once, then freezes them; every conversation is inference and changes nothing.',
      'It has no knowledge after its cutoff and no memory across sessions — apps fake memory by re-sending history in the context window.',
      'Base models only continue text; instruction tuning + RLHF turn that into the helpful assistant you chat with.',
      'It’s not a database: it outputs the most plausible-sounding continuation, so it states wrong facts as fluently as right ones.',
    ],
    gotchas: [
      'Confident tone is not a confidence score — plausibility is learned from text, not checked against truth.',
      'This one idea predicts the whole field: RAG (sources), tools (ground truth), and evals (measuring the damage) all exist because of it.',
    ],
  },
  {
    lessonId: 'tokenization',
    opsHeaders: H,
    opsTable: [
      { op: 'token', complexity: 'a sub-word chunk of bytes', note: 'not a word, not a char — the model’s unit' },
      { op: 'BPE', complexity: 'greedy merge of frequent pairs', note: 'builds the vocab; determines the splits' },
      { op: 'vocab size', complexity: '~50k–200k tokens', note: 'bigger = fewer tokens/word, larger embed matrix' },
      { op: 'context window', complexity: 'measured in TOKENS', note: 'not characters; non-English burns more' },
      { op: '~4 chars/token', complexity: 'English rule of thumb', note: '~0.75 words/token; code & rare langs worse' },
    ],
    useWhen: 'Estimating cost/context budget, debugging weird spelling/counting/math behavior, or handling non-English and code where token counts explode.',
    dontUseWhen: 'You need character-level operations — the model literally cannot see characters, only tokens.',
    stdlib: 'tiktoken (OpenAI) · the tokenizers library (HF) · llama tokenizer',
    stdlibLabel: 'Tools',
    bullets: [
      'The model sees token IDs, never letters — “strawberry” may be 3 tokens, so “how many r’s” is genuinely hard for it.',
      'Cost and context limits are billed in tokens; ~4 English chars ≈ 1 token, but rare languages can be 1 char ≈ 1+ tokens.',
      'BPE merges are frequency-driven and fixed at training — the split of a word is deterministic given the vocab.',
      'Numbers tokenize erratically (e.g. “1000” vs “1 000”), which is one reason raw arithmetic is unreliable.',
    ],
    gotchas: [
      'Trailing spaces and leading capitals change token IDs — “ dog” ≠ “dog”; prompt whitespace matters.',
      'Counting characters/words to estimate tokens undercounts code and non-English by a lot.',
    ],
  },
  {
    lessonId: 'embeddings',
    opsHeaders: H,
    opsTable: [
      { op: 'embedding', complexity: 'text → fixed-length vector', note: 'meaning as direction in space' },
      { op: 'cosine similarity', complexity: 'angle between vectors', note: 'the default relevance score' },
      { op: 'chunking', complexity: 'split docs before embedding', note: 'chunk size/overlap decides retrieval quality' },
      { op: 'vector DB', complexity: 'ANN index over embeddings', note: 'HNSW/IVF — approximate, sub-linear search' },
      { op: 'dimensionality', complexity: '~384–3072 dims', note: 'bigger ≠ always better; cost & storage grow' },
    ],
    useWhen: 'Semantic search, clustering, dedup, recommendations, and the retrieval half of any RAG system.',
    dontUseWhen: 'You need exact keyword/boolean matching (use BM25/lexical) or structured filters (use SQL) — embeddings blur specifics.',
    stdlib: 'OpenAI/Cohere/Voyage embed APIs · sentence-transformers · pgvector · FAISS · Pinecone/Weaviate/Qdrant',
    stdlibLabel: 'Tools',
    bullets: [
      'Cosine similarity compares direction, not magnitude — normalize and it’s just a dot product.',
      'Chunking is the highest-leverage RAG knob: too big dilutes relevance, too small loses context.',
      'ANN (HNSW) trades a tiny recall loss for enormous speed — exact search is O(n), HNSW is ~O(log n).',
      'Embeddings are model-specific: never mix vectors from two different embedding models in one index.',
    ],
    gotchas: [
      'High cosine similarity ≠ correct answer — retrieval finds “related,” not “true.”',
      'Re-embedding with a new model means re-indexing everything; version your embedding model.',
    ],
  },
  {
    lessonId: 'attention',
    opsHeaders: H,
    opsTable: [
      { op: 'self-attention', complexity: 'every token looks at every token', note: 'the mixing step; O(n²) in sequence length' },
      { op: 'Q/K/V', complexity: 'query · key · value projections', note: 'softmax(QKᵀ/√d)·V — the whole formula' },
      { op: 'multi-head', complexity: 'parallel attention subspaces', note: 'different heads learn different relations' },
      { op: 'positional encoding', complexity: 'inject order into a set op', note: 'RoPE/ALiBi; attention is order-blind without it' },
      { op: 'KV cache', complexity: 'reuse past keys/values', note: 'why generation is O(n) per token, not O(n²)' },
    ],
    useWhen: 'Reasoning about context-length cost, latency, the KV cache, and why long prompts are expensive.',
    dontUseWhen: 'You just need to ship a prompt — you can use the model without deriving attention, but the cost model helps.',
    stdlib: 'transformers (HF) · flash-attention · the “Attention Is All You Need” paper',
    stdlibLabel: 'References',
    bullets: [
      'Attention cost is quadratic in sequence length — doubling context ≈ 4× the attention compute.',
      'Q·Kᵀ scores how much each token attends to each other token; softmax makes it a weighted average of V.',
      'The KV cache stores past keys/values so each new token is O(n), not a full O(n²) recompute — it’s also your memory bottleneck.',
      'Positional encodings are what let a permutation-invariant operation know word order.',
    ],
    gotchas: [
      'Long context isn’t free even when it fits — attention compute and KV-cache memory both grow with it.',
      '“The model has 200k context” ≠ “it uses all 200k well” — see lost-in-the-middle in the RAG module.',
    ],
  },
  {
    lessonId: 'decoding',
    opsHeaders: H,
    opsTable: [
      { op: 'logits', complexity: 'raw per-token scores', note: 'softmax → probability distribution' },
      { op: 'temperature', complexity: 'flattens/sharpens the dist', note: '0 = greedy/deterministic, higher = more random' },
      { op: 'top-k', complexity: 'sample from k most likely', note: 'hard cutoff on candidate count' },
      { op: 'top-p (nucleus)', complexity: 'smallest set with cum. prob ≥ p', note: 'adaptive cutoff; the common default' },
      { op: 'greedy', complexity: 'always take argmax', note: 'deterministic, can loop/repeat' },
    ],
    useWhen: 'Tuning creativity vs reliability, forcing structured output, or debugging repetition and nondeterminism.',
    dontUseWhen: 'You need guaranteed-correct facts — no decoding setting fixes a model that doesn’t know; lower temp only reduces variance.',
    stdlib: 'temperature / top_p / seed params · logit_bias · constrained/JSON decoding · outlines / guidance',
    stdlibLabel: 'Controls',
    bullets: [
      'Temperature 0 (greedy) is your friend for extraction, classification, and tool-calls; higher temp for brainstorming.',
      'Top-p adapts the candidate set to the distribution’s shape; top-k is a fixed cutoff — top-p is usually preferred.',
      'Hallucination is fluent sampling from a wrong-but-confident distribution — it’s a feature of the mechanism, not a bug you can fully tune away.',
      'Even at temperature 0, batching/hardware can make outputs slightly nondeterministic across runs.',
    ],
    gotchas: [
      'Setting temperature high for “smarter” answers usually just adds noise; it does not add knowledge.',
      'Repetition loops come from greedy decoding on low-entropy text — a small temperature or repetition penalty breaks them.',
    ],
  },
  {
    lessonId: 'prompting',
    opsHeaders: H,
    opsTable: [
      { op: 'system prompt', complexity: 'the standing instructions', note: 'role, rules, format — highest-leverage text' },
      { op: 'few-shot', complexity: 'examples in the prompt', note: 'programming by demonstration at runtime' },
      { op: 'chain-of-thought', complexity: '“think step by step”', note: 'trades tokens for accuracy on reasoning' },
      { op: 'structured output', complexity: 'force JSON/schema', note: 'makes the model an API' },
      { op: 'prompt injection', complexity: 'untrusted text overrides you', note: 'the #1 agent security hole' },
    ],
    useWhen: 'Every LLM call — prompting is the cheapest, fastest lever, and the first thing to exhaust before RAG or fine-tuning.',
    dontUseWhen: 'The failure is missing knowledge (use RAG) or consistent style/format at scale (consider fine-tuning) — prompting can’t add facts.',
    stdlib: 'system/user/assistant roles · few-shot examples · CoT · response_format/JSON mode · prompt templates',
    stdlibLabel: 'Techniques',
    bullets: [
      'Order of precedence to try: prompt → few-shot → RAG → fine-tune. Stop at the cheapest one that works.',
      'Few-shot examples are runtime configuration: 2–5 well-chosen examples often beat paragraphs of instructions.',
      'Chain-of-thought helps genuine multi-step reasoning; it wastes tokens on lookup/format tasks.',
      'Anything you paste into the prompt from users or tools is untrusted — treat retrieved/tool text as potential injection.',
    ],
    gotchas: [
      'Instructions buried mid-prompt get ignored; put the load-bearing rules at the very start or very end.',
      '“Be concise” and a 5-paragraph example contradict each other — examples outvote adjectives.',
    ],
  },
  {
    lessonId: 'rag',
    opsHeaders: H,
    opsTable: [
      { op: 'pipeline', complexity: 'chunk→embed→retrieve→rerank→generate', note: 'each stage has its own failure mode' },
      { op: 'retrieval recall', complexity: 'did we fetch the right chunk?', note: 'if the answer isn’t retrieved, generation can’t save you' },
      { op: 'reranking', complexity: 'cross-encoder re-scores top-N', note: 'big precision win over pure vector top-k' },
      { op: 'hybrid search', complexity: 'lexical (BM25) + vector', note: 'catches exact terms embeddings miss' },
      { op: 'grounding', complexity: 'cite/limit to retrieved text', note: 'the main hallucination lever' },
    ],
    useWhen: 'The model needs knowledge it wasn’t trained on: private docs, fresh data, or anything that must be citable and current.',
    dontUseWhen: 'The knowledge is already in-weights and stable, the task is pure reasoning/format, or a simple SQL/API lookup would do.',
    stdlib: 'embeddings + vector DB · rerankers (Cohere/bge) · BM25 · LangChain/LlamaIndex · eval: Ragas',
    stdlibLabel: 'Stack',
    bullets: [
      'RAG is retrieval FIRST, generation second — most “LLM” bugs in RAG are actually retrieval bugs.',
      'Chunking + hybrid search + reranking are the three highest-leverage quality knobs, in that order.',
      'Lost-in-the-middle: models attend best to the START and END of context — put the best chunks at the edges.',
      'Ground the answer (“answer only from the context; say ‘I don’t know’ otherwise”) to slash hallucination.',
    ],
    gotchas: [
      'Stuffing more chunks isn’t better — it dilutes attention and can bury the answer in the middle.',
      'Vector-only search misses exact identifiers (SKUs, error codes, names) — add lexical/hybrid.',
    ],
  },
  {
    lessonId: 'tools',
    opsHeaders: H,
    opsTable: [
      { op: 'tool schema', complexity: 'name + JSON params + description', note: 'the model reads descriptions to decide' },
      { op: 'the loop', complexity: 'model → tool call → result → model', note: 'you execute; the model never runs code itself' },
      { op: 'JSON mode', complexity: 'forced schema-valid output', note: 'makes tool args reliable' },
      { op: 'parallel tools', complexity: 'multiple calls per turn', note: 'batch independent lookups' },
      { op: 'grounding', complexity: 'actions touch real systems', note: 'validate + authorize every call' },
    ],
    useWhen: 'The model needs live data or must take actions — search, DB queries, calculators, code execution, API calls.',
    dontUseWhen: 'A plain prompt answers it, or the action is irreversible and unsupervised — gate risky tools behind confirmation.',
    stdlib: 'OpenAI/Anthropic tool-calling · JSON schema · MCP (Model Context Protocol) · function registries',
    stdlibLabel: 'Standards',
    bullets: [
      'The model only EMITS a structured call; your code executes it and passes the result back — it’s a loop, not magic.',
      'Tool descriptions are prompt engineering: the model picks tools by their names and docstrings.',
      'Validate tool arguments before executing — the model can emit malformed or unsafe calls.',
      'Return errors as tool results, not exceptions — the model can often recover if you tell it what went wrong.',
    ],
    gotchas: [
      'Too many tools confuse selection; keep the toolset small and well-named.',
      'A tool that touches money/data/prod is an injection target — untrusted input can trick the model into calling it.',
    ],
  },
  {
    lessonId: 'agents',
    opsHeaders: H,
    opsTable: [
      { op: 'agent loop', complexity: 'perceive → decide → act → repeat', note: 'runs until a stop condition' },
      { op: 'ReAct', complexity: 'interleave reasoning + tool acts', note: 'the classic agent pattern' },
      { op: 'memory', complexity: 'scratchpad + long-term store', note: 'context is finite; externalize state' },
      { op: 'planning', complexity: 'decompose → subtasks', note: 'plan-then-execute vs react-as-you-go' },
      { op: 'stop condition', complexity: 'done / budget / max steps', note: 'without one, agents loop forever' },
    ],
    useWhen: 'Open-ended, multi-step tasks where the steps aren’t known in advance and the model must decide what to do next.',
    dontUseWhen: 'The steps ARE known — a fixed workflow/chain is cheaper, faster, more reliable, and easier to debug.',
    stdlib: 'tool-calling loop · ReAct · LangGraph · OpenAI Assistants/Agents · Claude agent SDKs',
    stdlibLabel: 'Frameworks',
    bullets: [
      'An agent is a loop around a model that chooses tools; autonomy is the whole point AND the whole risk.',
      'Always bound the loop: max steps, token budget, wall-clock, and a clear “done” signal.',
      'Memory ≠ context window — persist state externally and retrieve it, or the agent forgets across steps.',
      'Prefer the least autonomy that solves the task: workflow < single agent < multi-agent, in cost and unpredictability.',
    ],
    gotchas: [
      'Agents fail silently by wandering — log every step and add guardrails and human-in-the-loop for risky actions.',
      'Error compounding: a wrong early step poisons the rest; reflection/verification steps help.',
    ],
  },
  {
    lessonId: 'agentic-workflows',
    opsHeaders: H,
    opsTable: [
      { op: 'chaining', complexity: 'output of A → input of B', note: 'decompose a task into fixed steps' },
      { op: 'routing', complexity: 'classify → dispatch to handler', note: 'send each input to the right path' },
      { op: 'parallelization', complexity: 'fan-out → aggregate', note: 'sectioning or voting' },
      { op: 'orchestrator-worker', complexity: 'planner spawns sub-tasks', note: 'dynamic decomposition' },
      { op: 'evaluator-optimizer', complexity: 'generate → critique → revise', note: 'reflection loop' },
    ],
    useWhen: 'Composing reliable multi-step LLM systems — most production “agents” are actually structured workflows.',
    dontUseWhen: 'A single call suffices, or the task genuinely needs open-ended autonomy (then use an agent).',
    stdlib: 'LangGraph · control flow in plain code · Anthropic “Building effective agents” patterns',
    stdlibLabel: 'Patterns',
    bullets: [
      'Anthropic’s split: WORKFLOWS have predefined code paths; AGENTS direct their own process. Start with workflows.',
      'The five workhorse patterns: chaining, routing, parallelization, orchestrator-worker, evaluator-optimizer.',
      'Determinism is a feature — the more of the control flow you fix in code, the more testable and cheap it is.',
      'Add autonomy only where the task truly branches unpredictably; keep the rest as plain code.',
    ],
    gotchas: [
      'Reaching for a multi-agent swarm when a 3-step chain would do multiplies cost and failure surface.',
      'Every extra LLM hop adds latency, cost, and a new place to fail — count your hops.',
    ],
  },
  {
    lessonId: 'evaluation',
    opsHeaders: H,
    opsTable: [
      { op: 'golden set', complexity: 'curated input→expected pairs', note: 'your regression suite' },
      { op: 'LLM-as-judge', complexity: 'a model grades outputs', note: 'scalable but biased; calibrate it' },
      { op: 'RAG metrics', complexity: 'faithfulness, context recall/precision', note: 'separates retrieval vs generation faults' },
      { op: 'offline vs online', complexity: 'test set vs production traffic', note: 'both; A/B for real signal' },
      { op: 'cost/latency', complexity: 'tokens, $, TTFT, p95', note: 'quality is nothing without the budget' },
    ],
    useWhen: 'Always — before shipping, before every prompt/model change, and continuously in production. “Vibes” don’t scale.',
    dontUseWhen: 'Never skip it — but keep it proportional: a golden set of 20 good cases beats none.',
    stdlib: 'Ragas · promptfoo · OpenAI/Braintrust evals · LangSmith · custom LLM-judge rubrics',
    stdlibLabel: 'Tools',
    bullets: [
      'Build a golden set early; every prompt tweak is a diff against it, exactly like a test suite.',
      'LLM-as-judge scales human grading but inherits biases (length, position, self-preference) — calibrate against humans.',
      'For RAG, measure retrieval and generation separately or you’ll “fix” the wrong half.',
      'Track cost and latency as first-class metrics — a 2% quality gain for 3× the cost may not ship.',
    ],
    gotchas: [
      'A single anecdote is not an eval; you need enough cases to see a signal above noise.',
      'LLM judges rate longer/first answers higher — randomize order and control for length.',
    ],
  },
  {
    lessonId: 'fine-tuning',
    opsHeaders: H,
    opsTable: [
      { op: 'SFT', complexity: 'supervised fine-tune on examples', note: 'teach format/style/behavior, not facts' },
      { op: 'LoRA/PEFT', complexity: 'train small low-rank adapters', note: 'cheap; base weights frozen' },
      { op: 'RLHF/DPO', complexity: 'optimize to preferences', note: 'how base models get aligned' },
      { op: 'distillation', complexity: 'small model mimics big one', note: 'cut cost/latency' },
      { op: 'when NOT to', complexity: 'try prompt+RAG first', note: 'fine-tuning is the last, priciest lever' },
    ],
    useWhen: 'You need consistent style/format/behavior at scale, lower latency/cost via a smaller specialized model, or to bake in a narrow skill.',
    dontUseWhen: 'You need current or private FACTS (use RAG), or you haven’t exhausted prompting — fine-tuning teaches behavior, not knowledge.',
    stdlib: 'OpenAI/together fine-tune APIs · LoRA/QLoRA (peft) · TRL (SFT/DPO) · Axolotl · Unsloth',
    stdlibLabel: 'Tools',
    bullets: [
      'Decision order: prompt → few-shot → RAG → fine-tune. Fine-tuning is powerful and the easiest to over-reach for.',
      'LoRA freezes the base model and trains tiny low-rank matrices — most of fine-tuning’s value at a fraction of the cost.',
      'Fine-tuning teaches HOW to respond (tone, schema, task); RAG supplies WHAT to say (facts). They compose.',
      'Data quality dominates: a few hundred clean, consistent examples beat thousands of noisy ones.',
    ],
    gotchas: [
      'Fine-tuning to “add knowledge” bakes in a snapshot that goes stale and can’t cite sources — that’s RAG’s job.',
      'Catastrophic forgetting: overfit fine-tunes get worse at everything else.',
    ],
  },
  {
    lessonId: 'inference',
    opsHeaders: H,
    opsTable: [
      { op: 'latency vs throughput', complexity: 'per-request speed vs total tok/s', note: 'batching trades one for the other' },
      { op: 'TTFT vs TPOT', complexity: 'time-to-first-token vs per-token', note: 'prefill vs decode phases' },
      { op: 'continuous batching', complexity: 'pack requests dynamically', note: 'the big throughput win (vLLM)' },
      { op: 'KV cache', complexity: 'memory grows with context', note: 'the real capacity limit' },
      { op: 'quantization', complexity: 'lower-precision weights', note: 'int8/int4 — cheaper, slightly worse' },
    ],
    useWhen: 'Serving models yourself, sizing GPUs, hitting latency SLAs, or explaining the token bill and why long context costs more.',
    dontUseWhen: 'You’re using a hosted API and don’t care how the sausage is made — though the cost model still applies.',
    stdlib: 'vLLM · TensorRT-LLM · TGI · llama.cpp · GGUF/AWQ/GPTQ quantization',
    stdlibLabel: 'Serving',
    bullets: [
      'Two phases: prefill (process the prompt, sets TTFT) and decode (generate tokens, sets throughput) — they cost differently.',
      'Continuous batching keeps the GPU busy by swapping requests in/out per token — the core of modern serving throughput.',
      'The KV cache, not FLOPs, is usually what caps concurrent long-context requests — it’s memory-bound.',
      'Quantization (int8/int4) roughly halves/quarters memory and cost for a small, often acceptable quality hit.',
    ],
    gotchas: [
      'Long prompts are billed and cached every request — a 50k-token system prompt is a recurring tax (use prompt caching).',
      'Streaming improves perceived latency (TTFT) without changing total generation time.',
    ],
  },
];
