import type { Question } from '@/lib/types';

export const QUESTIONS: Question[] = [
  {
    kind: 'numeric',
    id: 'gre-int-divisors',
    lessonId: 'gre-integers',
    difficulty: 2,
    prompt: 'How many positive divisors does 72 have?',
    answer: 12,
    answerDisplay: '12',
    explanation: '72 = 2³ × 3². Number of divisors = (3 + 1)(2 + 1) = 12. (They are 1, 2, 3, 4, 6, 8, 9, 12, 18, 24, 36, 72.)',
  },
  {
    kind: 'mcq',
    id: 'gre-int-remainder',
    lessonId: 'gre-integers',
    difficulty: 2,
    prompt: 'When the positive integer k is divided by 6, the remainder is 4. What is the remainder when 3k is divided by 6?',
    options: ['0', '1', '2', '4', '12'],
    correctIndex: 0,
    explanation: 'Take k = 4: 3k = 12, and 12 ÷ 6 leaves remainder **0**. Check with k = 10: 3k = 30, remainder 0 again.',
    distractorNotes: [
      'Correct.',
      'Arithmetic slip — recompute 3 × 4 = 12.',
      'Not the remainder of 12 ÷ 6.',
      'Assumes the remainder doesn’t change when you multiply.',
      '12 isn’t reduced — a remainder must be less than the divisor.',
    ],
  },
  {
    kind: 'multi',
    id: 'gre-int-parity',
    lessonId: 'gre-integers',
    difficulty: 2,
    prompt: 'If a is an odd integer and b is an even integer, which of the following must be odd?\n\nIndicate all such expressions.',
    options: ['a + b', 'ab', 'a² + b', '2a + b', 'ab + 1'],
    correctIndices: [0, 2, 4],
    explanation: 'Test a = 1, b = 2: a + b = 3 (odd), ab = 2 (even), a² + b = 3 (odd), 2a + b = 4 (even), ab + 1 = 3 (odd). The rules confirm it for all values: odd + even = odd; anything × even = even; even + 1 = odd.',
    distractorNotes: [
      '✓ odd + even = odd.',
      '✗ anything times an even number is even.',
      '✓ odd² is odd; odd + even = odd.',
      '✗ 2a is even; even + even = even.',
      '✓ ab is even, so ab + 1 is odd.',
    ],
  },
  {
    kind: 'numeric',
    id: 'gre-int-consecutive',
    lessonId: 'gre-integers',
    difficulty: 2,
    prompt: 'The sum of 5 consecutive even integers is 130. What is the least of these integers?',
    answer: 22,
    answerDisplay: '22',
    explanation: 'Average = 130 ÷ 5 = 26 = the middle term. Consecutive EVEN integers step by 2: 22, 24, 26, 28, 30. The least is **22**.',
  },
  {
    kind: 'mcq',
    id: 'gre-int-prime',
    lessonId: 'gre-integers',
    difficulty: 1,
    prompt: 'Which of the following is prime?',
    options: ['51', '57', '87', '89', '91'],
    correctIndex: 3,
    explanation: 'Check divisibility by 2, 3, 5, 7 (enough, since 10² > 91). 51 = 3 × 17, 57 = 3 × 19, 87 = 3 × 29, 91 = 7 × 13 — only **89** is prime.',
    distractorNotes: ['3 × 17.', '3 × 19.', '3 × 29 (digit sum 15).', 'Correct.', '7 × 13 — the classic look-alike.'],
  },
];
